package cz.jtbank.konsolidace.subkons.common;
import oracle.jbo.ApplicationModule;
import cz.jtbank.konsolidace.common.KisException;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 * 
 * Generated interface. Do not modify.
 */

public interface SubkonsModule extends ApplicationModule 
{
  int currentUsersId();

  int subKonsolidace(String akce, int idSpol, int idSkup, int poradi, String mena, String nazev, java.sql.Date datumOd, java.sql.Date datumDo, String kursListek, String listKR, java.sql.Date datumArch, int krokClenu, String expFlag) throws KisException;

  void subKonsolidaceClen(String akce, int idSubkons, int idSpol, int idClenstvi, double pomer, java.sql.Date datumOd, java.sql.Date datumDo, java.sql.Date vazbyOd, java.sql.Date vazbyDo, String clen, String propisuj, java.sql.Date odOrig, int prestup) throws KisException;

  void subKonsolidaceMatka(int idSubkons, int idSpol) throws KisException;

  void subkonsPravidlo(String akce, int id, int idPoradi, int typ, int idSub, int idSpol, int idEtapa, java.sql.Date platnostOd, java.sql.Date platnostDo, String poznamka, int validaceRadek, int validaceList, double validaceHodnota) throws KisException;

  void subkonsPravidloDetail(String akce, int id, int idPrav, int idPoradi, int idPoradiPodminka, int typ, String poznamka, int radek, int list, double castka, String vzorec, String ucetZbytek, String podminka, int refSpol, int refSub, int idProtistrana) throws KisException;

  void addEtapa(int idSubkons, int poradi, String nazev, String zkratka) throws KisException;

  void modEtapa(int idEtapa, String nazev) throws KisException;

  void delEtapa(int idEtapa) throws KisException;

  String calculateSyntaxText(int idPrav, String vzorec) throws KisException;

  void exportExcel(java.sql.Date datum) throws KisException;

  String getExcels();

  void exportExcelKons(java.sql.Date datum) throws KisException;

  String getExcelsKons();

  void exportExcelSpravce(java.sql.Date datum) throws KisException;

  String getExcelsSpravce() throws KisException;

  void subVazbyVyjimky(String akce, int oSub, java.sql.Date oDatum, int oSpol1, int oSpol2, int sub, java.sql.Date datum, int spol1, int spol2) throws KisException;

  void setSubkonsOO(int idSpol, int idOO, int idTop) throws KisException;

  void typSubPravidla(int idCis, int idSub, int idSpol, java.sql.Date datum) throws KisException;

  void typSubkonsPravidlo(String akce, int id, int idPoradi, int typ, int idEtapa, String poznamka, int idDatumTyp) throws KisException;

  void typSubkonsPravidloDetail(String akce, int id, int idPrav, int idPoradi, int idPoradiPodminka, int typ, String poznamka, int radek, int list, String vzorec, String ucetZbytek, String podminka, int idProtistrana, String nulove, String matka) throws KisException;

  void addTypEtapa(int idCisEtapa, int poradi, String nazev, String zkratka) throws KisException;

  void modTypEtapa(int idEtapa, String nazev) throws KisException;

  void delTypEtapa(int idEtapa) throws KisException;

  void subClenRp(String akce, int idSub, int idSpol, String kdyPouzit, String aktPas, String vysl, String vazby, String doklad) throws KisException;

  void spolecnostList(String akce, int id, String nazev, String sdilene) throws KisException;

  void spolecnostListDetail(String akce, int id, int idList, int idSpol, java.sql.Date dtOd, java.sql.Date dtDo) throws KisException;


























  





                       
                       















  
  


}                                  
/*
  int currentUsersId();
  
  int subKonsolidace(String akce,
                           int idSpol,
                           int idSkup,
                           int poradi,
                           String mena,
                           String nazev,
                           java.sql.Date datumOd,
                           java.sql.Date datumDo,
                           String kursListek,
                           String listKR,
                           java.sql.Date datumArch,
                           int krokClenu,
                           String expFlag) throws KisException;

  void subKonsolidaceClen(String akce,
                                 int idSubkons,
                                 int idSpol,
                                 int idClenstvi,
                                 double pomer,
                                 java.sql.Date datumOd,
                                 java.sql.Date datumDo,
                                 java.sql.Date vazbyOd,
                                 java.sql.Date vazbyDo,
                                 String clen,
                                 String propisuj,
                                 java.sql.Date odOrig,
                                 int prestup) throws KisException;

  void subKonsolidaceMatka(int idSubkons,
                                  int idSpol) throws KisException;

  void subkonsPravidlo(String akce,
                           int id,
                           int idPoradi,
                           int typ,
                           int idSub,
                           int idSpol,
                           int idEtapa,
                           java.sql.Date platnostOd,
                           java.sql.Date platnostDo,
                           String poznamka,
                           int validaceRadek,
                           int validaceList,
                           double validaceHodnota) throws KisException;

  void subkonsPravidloDetail(String akce,
                                 int id,
                                 int idPrav,
                                 int idPoradi,
                                 int idPoradiPodminka,
                                 int typ,
                                 String poznamka,
                                 int radek,
                                 int list,
                                 double castka,
                                 String vzorec,
                                 String ucetZbytek,
                                 String podminka,
                                 int refSpol,
                                 int refSub,
                                 int idProtistrana) throws KisException;

  void addEtapa(int idSubkons,
                       int poradi,
                       String nazev,
                       String zkratka) throws KisException;
                       
  void modEtapa(int idEtapa,
                       String nazev) throws KisException;
                       
  void delEtapa(int idEtapa) throws KisException;

  String calculateSyntaxText(int idPrav,
                                  String vzorec) throws KisException;

  void exportExcel(java.sql.Date datum) throws KisException;

  String getExcels();

  void exportExcelKons(java.sql.Date datum) throws KisException;

  String getExcelsKons();

  void exportExcelSpravce(java.sql.Date datum) throws KisException;

  String getExcelsSpravce();

  void subVazbyVyjimky(String akce,
                     int oSub,
                     java.sql.Date oDatum,
                     int oSpol1,
                     int oSpol2,
                     int sub,
                     java.sql.Date datum,
                     int spol1,
                     int spol2) throws KisException;

  void setSubkonsOO(int idSpol,
                           int idOO,
                           int idTop) throws KisException;

  void typSubPravidla(int id,
                             int idSub,
                             int idSpol,
                             java.sql.Date datum) throws KisException;

  void typSubkonsPravidlo(String akce,
                           int id,
                           int idPoradi,
                           int typ,
                           int idEtapa,
                           String poznamka,
                           int idDatumTyp) throws KisException;

  void typSubkonsPravidloDetail(String akce,
                                 int id,
                                 int idPrav,
                                 int idPoradi,
                                 int idPoradiPodminka,
                                 int typ,
                                 String poznamka,
                                 int radek,
                                 int list,
                                 String vzorec,
                                 String ucetZbytek,
                                 String podminka,
                                 int idProtistrana,
                                 String nulove,
                                 String matka) throws KisException;

  void addTypEtapa(int idCisEtapa,
                       int poradi,
                       String nazev,
                       String zkratka) throws KisException;

  void modTypEtapa(int idEtapa,
                       String nazev) throws KisException;

  void delTypEtapa(int idEtapa) throws KisException;
  
  void subClenRp(String akce,
                        int idSub,
                        int idSpol,
                        String kdyPouzit,
                        String aktPas,
                        String vysl,
                        String vazby,
                        String doklad) throws KisException;
  
  void spolecnostList(String akce,
                             int id,
                             String nazev,
                             String sdilene) throws KisException;

  void spolecnostListDetail(String akce,
                                   int id,
                                   int idList,
                                   int idSpol,
                                   java.sql.Date dtOd,
                                   java.sql.Date dtDo) throws KisException;
*/