package cz.jtbank.konsolidace.mustky.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 * 
 * Generated interface. Do not modify.
 */

public interface VwKpBunkadefiniceuctuViewRow extends Row 
{
  String getSymbolString();

}