package cz.jtbank.konsolidace.doklady.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatDokladprotokolImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatDokladprotokolImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"IdDoklad_DISPLAYHINT", "Hide"},
    {"SHlaska_LABEL", "Text"},
    {"Id_DISPLAYHINT", "Hide"},
    {"CKod_LABEL", "Kód"},
    {"DtDatum_LABEL", "Datum"}};


}