package cz.jtbank.konsolidace.doklady.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwHkExcelDetailImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwHkExcelDetailImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPopis_LABEL", "Popis"},
    {"SExtprotistranaicoBanka_LABEL", "Banka kód"},
    {"NdCastkalocal_LABEL", "Èástka lokální"},
    {"SExtprotistranaEmitent_LABEL", "Emitent"},
    {"Testico_LABEL", "Test IÈ"},
    {"CUverovapozice_LABEL", "Úvìrová pozice"},
    {"NdCastkamena_LABEL", "Èástka v mìnì"},
    {"SExtprotistrana_LABEL", "Protistrana"},
    {"SExtprotistranaicoEo_LABEL", "Ekon. objekt IÈ"},
    {"CMenovapozice_LABEL", "Mìnová pozice"},
    {"SExtprotistranaEo_LABEL", "Ekon. objekt"},
    {"SExtprotistranaicoEmitent_LABEL", "Emitent IÈ"},
    {"Ucet_LABEL", "Úèet"},
    {"Datum_LABEL", "Datum"},
    {"IdInterni_LABEL", "Interní ID"},
    {"Textradek_LABEL", "Øádek text"},
    {"IdExtsystem_LABEL", "Externí ID"},
    {"SExtprotistranaBanka_LABEL", "Banka"},
    {"SExtprotistranaico_LABEL", "Protistrana IÈ"},
    {"SMena_LABEL", "Mìna"}};







}