package cz.jtbank.konsolidace.doklady.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpDokladvazbyvyparovaneImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpDokladvazbyvyparovaneImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPopis_LABEL", "Název úètu"},
    {"ParSUcet_LABEL", "Úèet"},
    {"NdCastkamenaoriginal_LABEL", "Èástka originální"},
    {"ParNdCastkavyparovat_LABEL", "Kontrolní èástka"},
    {"ParNdCastkalocal_LABEL", "Èástka v mìnì spoleènosti"},
    {"NdCastkavyparovat_LABEL", "Kontrolní èástka"},
    {"NlPoradilist_LABEL", "List"},
    {"NdCastkalocal_LABEL", "Èástka v mìnì spoleènosti"},
    {"ParSPopis_LABEL", "Název úètu"},
    {"SUcet_LABEL", "Úèet"},
    {"NdCastkamena_LABEL", "Èástka"},
    {"ParSMena_LABEL", "Mìna"},
    {"ParNdCastkamena_LABEL", "Èástka"},
    {"NlRadek_LABEL", "Øádek"},
    {"ParNlRadek_LABEL", "Øádek"},
    {"ParNdCastkamenaoriginal_LABEL", "Èástka originální"},
    {"ParNlPoradilist_LABEL", "List"},
    {"SMena_LABEL", "Mìna"}};


}