package cz.jtbank.konsolidace.cartesis;
import oracle.jbo.server.ApplicationModuleImpl;
import cz.jtbank.konsolidace.doklady.DatKurzlistExportViewImpl;
import cz.jtbank.konsolidace.common.*;
import java.io.*;
import cz.jtbank.konsolidace.admin.KpParametryViewImpl;
import java.sql.*;
import oracle.jbo.server.DBTransaction;

import org.apache.log4j.*;
import cz.jtbank.konsolidace.common.Logging;
import cz.jtbank.konsolidace.mustky.KpCisUcetunifViewImpl;
import cz.jtbank.konsolidace.mustky.KpCisUcetuniflangViewImpl;
import cz.jtbank.konsolidace.doklady.CisLocaleViewImpl;
import cz.jtbank.konsolidace.doklady.VwKpDokladzahlaviViewImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CartesisModuleImpl extends ApplicationModuleImpl implements cz.jtbank.konsolidace.cartesis.common.CartesisModule 
{
  static Logger logger = Logger.getLogger(ApplicationModuleImpl.class);
  static { logger.addAppender(Logging.getAppender(Logging.LOG_DEFAULT)); }

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public CartesisModuleImpl()
  {
  }

  /**
   * 
   * Container's getter for VwRepSpolecnostcartesisView1
   */
  public VwRepSpolecnostcartesisViewImpl getVwRepSpolecnostcartesisView1()
  {
    return (VwRepSpolecnostcartesisViewImpl)findViewObject("VwRepSpolecnostcartesisView1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("cz.jtbank.konsolidace.cartesis", "CartesisModuleLocal");
  }

  /**
   * 
   * Container's getter for DatKurzlistExportView1
   */
  public DatKurzlistExportViewImpl getDatKurzlistExportView1()
  {
    return (DatKurzlistExportViewImpl)findViewObject("DatKurzlistExportView1");
  }

  /**
   * 
   * Container's getter for VwRepOsobycartesisView1
   */
  public VwRepOsobycartesisViewImpl getVwRepOsobycartesisView1()
  {
    return (VwRepOsobycartesisViewImpl)findViewObject("VwRepOsobycartesisView1");
  }
  
  protected FileFilter getFileFilter(final String name) 
  {
    return new FileFilter() {
      public boolean accept(File pathname) 
      {
        return (pathname.getName().indexOf(name)>-1);
      }
    };
  }
  
  java.text.DateFormat df = java.text.DateFormat.getDateTimeInstance(java.text.DateFormat.MEDIUM, java.text.DateFormat.MEDIUM);

  public String getExcels(String type) 
  {
    StringBuffer buf = new StringBuffer();
    String dirName = Constants.XLS_FILES_PATH + Constants.DIR_CARTESIS;
    File dir = new File(dirName);
    FileFilter ff = getFileFilter(type);
    File[] arr = dir.listFiles(ff);
    if(arr != null) {
      for( int i=0; i<arr.length; i++ ) 
      {
        String name = arr[i].getName();
        buf.append("<a target=\"_blank\" href=\"excelservlet/"+name+"?file="+Constants.DIR_CARTESIS+"|5C" + name + "\">" + name+ "</a>");
        buf.append("&nbsp;" + df.format( new java.util.Date(arr[i].lastModified())) + "<br>"); 
      }
    }
    return buf.toString();
  }


  public String getCSVs(String aDir, String type) 
  {
    StringBuffer buf = new StringBuffer();
    String dirName = Constants.CSV_FILES_PATH + aDir;
    File dir = new File(dirName); 
    FileFilter ff = getFileFilter(type);
    File[] arr = dir.listFiles(ff);
    if(arr != null) {
      for( int i=0; i<arr.length; i++ ) 
      {
        String name = arr[i].getName();
        buf.append("<a target=\"_blank\" href=\"filesservlet/"+name+"?file=csv|5C"+aDir+"|5C" + name + "\">" + name+ "</a>");
        buf.append("&nbsp;" + df.format( new java.util.Date(arr[i].lastModified())) + "<br>"); 
      }
    }
    return buf.toString();
  }


  public String getCSVs(String type) 
  {
	return ( getCSVs( Constants.DIR_DATA, type) );
  }

  /**
   * 
   * Container's getter for KpParametryView1
   */
  public KpParametryViewImpl getKpParametryView1()
  {
    return (KpParametryViewImpl)findViewObject("KpParametryView1");
  }

  public void fillCartesisSpolecnost(java.sql.Date datum) throws KisException
  {
    CallableStatement st = null;
    try {
      if ( datum == null ) {
        st = getDBTransaction().createCallableStatement("begin db_jt.kap_report.p_fillCartesisSpolecnost; end;",0);
      } else {
        st = getDBTransaction().createCallableStatement("begin db_jt.kap_report.p_fillCartesisSpolecnost(?); end;",0);
        st.setDate(1, datum);
      }
      st.execute();
      logger.info("fillCartesisSpolecnost - dokonceno");
    }
    catch (SQLException e) 
    {
      e.printStackTrace();
      logger.error("Selhalo volání procedury db_jt.kap_report.p_fillCartesisSpolecnost",e);
      throw new KisException("Selhalo volání procedury db_jt.kap_report.p_fillCartesisSpolecnost",e);
    }
    finally 
    {
      try 
      {
        if(st != null) st.close();
      }
      catch(Exception e) {}
    }
  }

  /**
   * 
   * Container's getter for KpCisFlowView1
   */
  public KpCisFlowViewImpl getKpCisFlowView1()
  {
    return (KpCisFlowViewImpl)findViewObject("KpCisFlowView1");
  }

  /**
   * 
   * Container's getter for KpRelUcetunifflowView1
   */
  public KpRelUcetunifflowViewImpl getKpRelUcetunifflowView1()
  {
    return (KpRelUcetunifflowViewImpl)findViewObject("KpRelUcetunifflowView1");
  }

  /**
   * 
   * Container's getter for KpCisUcetunifView1
   */
  public KpCisUcetunifViewImpl getKpCisUcetunifView1()
  {
    return (KpCisUcetunifViewImpl)findViewObject("KpCisUcetunifView1");
  }

  /**
   * 
   * Container's getter for KpCisUcetuniflangView1
   */
  public KpCisUcetuniflangViewImpl getKpCisUcetuniflangView1()
  {
    return (KpCisUcetuniflangViewImpl)findViewObject("KpCisUcetuniflangView1");
  }

  /**
   * 
   * Container's getter for CisLocaleView1
   */
  public CisLocaleViewImpl getCisLocaleView1()
  {
    return (CisLocaleViewImpl)findViewObject("CisLocaleView1");
  }

  public void ucetUnifFlow(String akce,
                           int idUcet,
                           int idFlow,
                           int idOrigFlow) throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;

    //INSERT
    if("I".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("INSERT INTO DB_JT.KP_REL_UCETUNIFFLOW "+
                                            "(ID_CISUCETUNIF, ID_CISFLOW) "+
                                            "VALUES (?,?)",0);
        st.setInt(1, idUcet);
        st.setInt(2, idFlow);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury ucetUnifFlow akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    //UPDATE
    else if("U".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("UPDATE DB_JT.KP_REL_UCETUNIFFLOW "+
                                            "SET ID_CISFLOW=? "+
                                            "WHERE ID_CISUCETUNIF=? AND ID_CISFLOW=?",0);
        st.setInt(1, idFlow);
        st.setInt(2, idUcet);
        st.setInt(3, idOrigFlow);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury ucetUnifFlow akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    //DELETE
    else if("D".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("DELETE FROM DB_JT.KP_REL_UCETUNIFFLOW "+
                                            "WHERE ID_CISUCETUNIF=? AND ID_CISFLOW=?",0);
        st.setInt(1, idUcet);
        st.setInt(2, idOrigFlow);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury ucetUnifFlow akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    dbTran.commit();
  }

  /**
   * 
   * Container's getter for KpDatZdaFlowZustatekView1
   */
  public KpDatZdaFlowZustatekViewImpl getKpDatZdaFlowZustatekView1()
  {
    return (KpDatZdaFlowZustatekViewImpl)findViewObject("KpDatZdaFlowZustatekView1");
  }

  /**
   * 
   * Container's getter for VwKpDokladzahlaviView1
   */
  public VwKpDokladzahlaviViewImpl getVwKpDokladzahlaviView1()
  {
    return (VwKpDokladzahlaviViewImpl)findViewObject("VwKpDokladzahlaviView1");
  }

  /**
   * 
   * Container's getter for KpDatZdaFlowZustatekLocalView1
   */
  public KpDatZdaFlowZustatekLocalViewImpl getKpDatZdaFlowZustatekLocalView1()
  {
    return (KpDatZdaFlowZustatekLocalViewImpl)findViewObject("KpDatZdaFlowZustatekLocalView1");
  }

  /**
   * 
   * Container's getter for KpDatZdaFlowProtistranaView1
   */
  public KpDatZdaFlowProtistranaViewImpl getKpDatZdaFlowProtistranaView1()
  {
    return (KpDatZdaFlowProtistranaViewImpl)findViewObject("KpDatZdaFlowProtistranaView1");
  }

  /**
   * 
   * Container's getter for KpDatZdaFlowProtistranaLocalView1
   */
  public KpDatZdaFlowProtistranaLocalViewImpl getKpDatZdaFlowProtistranaLocalView1()
  {
    return (KpDatZdaFlowProtistranaLocalViewImpl)findViewObject("KpDatZdaFlowProtistranaLocalView1");
  }

  /**
   * 
   * Container's getter for KpDatZdaFlowSegmentLocalView1
   */
  public KpDatZdaFlowSegmentLocalViewImpl getKpDatZdaFlowSegmentLocalView1()
  {
    return (KpDatZdaFlowSegmentLocalViewImpl)findViewObject("KpDatZdaFlowSegmentLocalView1");
  }
}