package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatDokladzdrojdatagregaceImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDDOKLAD = 1;
  protected static final int SMENA = 2;
  protected static final int SUCET = 3;
  protected static final int IDKTGUCETNISPOLECNOST = 4;
  protected static final int IDKTGSPOLECNOST = 5;
  protected static final int IDCISRADEKTEXT = 6;
  protected static final int CMENOVAPOZICE = 7;
  protected static final int CUVEROVAPOZICE = 8;
  protected static final int NDCASTKAMENA = 9;
  protected static final int NDCASTKALOCAL = 10;
  protected static final int NDCASTKACNB = 11;
  protected static final int CLIST = 12;
  protected static final int SEVIDOVATPROTISTRANU = 13;
  protected static final int CKONTOKORENT = 14;
  protected static final int IDDOKLADPOLOZKA = 15;
  protected static final int KPKTGUCETNISPOLECNOST = 16;


  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatDokladzdrojdatagregaceImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.KpDatDokladzdrojdatagregace");
    }
    return mDefinitionObject;
  }



  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgspolecnost, using the alias name IdKtgspolecnost
   */
  public Number getIdKtgspolecnost()
  {
    return (Number)getAttributeInternal(IDKTGSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgspolecnost
   */
  public void setIdKtgspolecnost(Number value)
  {
    setAttributeInternal(IDKTGSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisradektext, using the alias name IdCisradektext
   */
  public Number getIdCisradektext()
  {
    return (Number)getAttributeInternal(IDCISRADEKTEXT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisradektext
   */
  public void setIdCisradektext(Number value)
  {
    setAttributeInternal(IDCISRADEKTEXT, value);
  }

  /**
   * 
   * Gets the attribute value for CMenovapozice, using the alias name CMenovapozice
   */
  public String getCMenovapozice()
  {
    return (String)getAttributeInternal(CMENOVAPOZICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CMenovapozice
   */
  public void setCMenovapozice(String value)
  {
    setAttributeInternal(CMENOVAPOZICE, value);
  }

  /**
   * 
   * Gets the attribute value for CUverovapozice, using the alias name CUverovapozice
   */
  public String getCUverovapozice()
  {
    return (String)getAttributeInternal(CUVEROVAPOZICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CUverovapozice
   */
  public void setCUverovapozice(String value)
  {
    setAttributeInternal(CUVEROVAPOZICE, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkacnb, using the alias name NdCastkacnb
   */
  public Number getNdCastkacnb()
  {
    return (Number)getAttributeInternal(NDCASTKACNB);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkacnb
   */
  public void setNdCastkacnb(Number value)
  {
    setAttributeInternal(NDCASTKACNB, value);
  }

  /**
   * 
   * Gets the attribute value for CList, using the alias name CList
   */
  public String getCList()
  {
    return (String)getAttributeInternal(CLIST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CList
   */
  public void setCList(String value)
  {
    setAttributeInternal(CLIST, value);
  }

  /**
   * 
   * Gets the attribute value for SEvidovatprotistranu, using the alias name SEvidovatprotistranu
   */
  public String getSEvidovatprotistranu()
  {
    return (String)getAttributeInternal(SEVIDOVATPROTISTRANU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SEvidovatprotistranu
   */
  public void setSEvidovatprotistranu(String value)
  {
    setAttributeInternal(SEVIDOVATPROTISTRANU, value);
  }

  /**
   * 
   * Gets the attribute value for CKontokorent, using the alias name CKontokorent
   */
  public String getCKontokorent()
  {
    return (String)getAttributeInternal(CKONTOKORENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CKontokorent
   */
  public void setCKontokorent(String value)
  {
    setAttributeInternal(CKONTOKORENT, value);
  }

  /**
   * 
   * Gets the attribute value for IdDokladpolozka, using the alias name IdDokladpolozka
   */
  public Number getIdDokladpolozka()
  {
    return (Number)getAttributeInternal(IDDOKLADPOLOZKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDokladpolozka
   */
  public void setIdDokladpolozka(Number value)
  {
    setAttributeInternal(IDDOKLADPOLOZKA, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDDOKLAD:
        return getIdDoklad();
      case SMENA:
        return getSMena();
      case SUCET:
        return getSUcet();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case IDKTGSPOLECNOST:
        return getIdKtgspolecnost();
      case IDCISRADEKTEXT:
        return getIdCisradektext();
      case CMENOVAPOZICE:
        return getCMenovapozice();
      case CUVEROVAPOZICE:
        return getCUverovapozice();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case NDCASTKACNB:
        return getNdCastkacnb();
      case CLIST:
        return getCList();
      case SEVIDOVATPROTISTRANU:
        return getSEvidovatprotistranu();
      case CKONTOKORENT:
        return getCKontokorent();
      case IDDOKLADPOLOZKA:
        return getIdDokladpolozka();
      case KPKTGUCETNISPOLECNOST:
        return getKpKtgUcetnispolecnost();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case IDKTGSPOLECNOST:
        setIdKtgspolecnost((Number)value);
        return;
      case IDCISRADEKTEXT:
        setIdCisradektext((Number)value);
        return;
      case CMENOVAPOZICE:
        setCMenovapozice((String)value);
        return;
      case CUVEROVAPOZICE:
        setCUverovapozice((String)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case NDCASTKACNB:
        setNdCastkacnb((Number)value);
        return;
      case CLIST:
        setCList((String)value);
        return;
      case SEVIDOVATPROTISTRANU:
        setSEvidovatprotistranu((String)value);
        return;
      case CKONTOKORENT:
        setCKontokorent((String)value);
        return;
      case IDDOKLADPOLOZKA:
        setIdDokladpolozka((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the associated entity KpKtgUcetnispolecnostImpl
   */
  public KpKtgUcetnispolecnostImpl getKpKtgUcetnispolecnost()
  {
    return (KpKtgUcetnispolecnostImpl)getAttributeInternal(KPKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpKtgUcetnispolecnostImpl
   */
  public void setKpKtgUcetnispolecnost(KpKtgUcetnispolecnostImpl value)
  {
    setAttributeInternal(KPKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }



}