package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatDokladrozdilyImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDDOKLAD = 1;
  protected static final int SMENA = 2;
  protected static final int SUCET = 3;
  protected static final int IDKTGSPOLECNOST = 4;
  protected static final int NDCASTKAMENA = 5;
  protected static final int SMENAIFRS = 6;
  protected static final int SUCETIFRS = 7;
  protected static final int IDKTGSPOLECNOSTIFRS = 8;
  protected static final int NDCASTKAMENAIFRS = 9;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatDokladrozdilyImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.KpDatDokladrozdily");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgspolecnost, using the alias name IdKtgspolecnost
   */
  public Number getIdKtgspolecnost()
  {
    return (Number)getAttributeInternal(IDKTGSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgspolecnost
   */
  public void setIdKtgspolecnost(Number value)
  {
    setAttributeInternal(IDKTGSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SMenaIfrs, using the alias name SMenaIfrs
   */
  public String getSMenaIfrs()
  {
    return (String)getAttributeInternal(SMENAIFRS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMenaIfrs
   */
  public void setSMenaIfrs(String value)
  {
    setAttributeInternal(SMENAIFRS, value);
  }

  /**
   * 
   * Gets the attribute value for SUcetIfrs, using the alias name SUcetIfrs
   */
  public String getSUcetIfrs()
  {
    return (String)getAttributeInternal(SUCETIFRS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetIfrs
   */
  public void setSUcetIfrs(String value)
  {
    setAttributeInternal(SUCETIFRS, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgspolecnostIfrs, using the alias name IdKtgspolecnostIfrs
   */
  public Number getIdKtgspolecnostIfrs()
  {
    return (Number)getAttributeInternal(IDKTGSPOLECNOSTIFRS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgspolecnostIfrs
   */
  public void setIdKtgspolecnostIfrs(Number value)
  {
    setAttributeInternal(IDKTGSPOLECNOSTIFRS, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamenaIfrs, using the alias name NdCastkamenaIfrs
   */
  public Number getNdCastkamenaIfrs()
  {
    return (Number)getAttributeInternal(NDCASTKAMENAIFRS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamenaIfrs
   */
  public void setNdCastkamenaIfrs(Number value)
  {
    setAttributeInternal(NDCASTKAMENAIFRS, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDDOKLAD:
        return getIdDoklad();
      case SMENA:
        return getSMena();
      case SUCET:
        return getSUcet();
      case IDKTGSPOLECNOST:
        return getIdKtgspolecnost();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case SMENAIFRS:
        return getSMenaIfrs();
      case SUCETIFRS:
        return getSUcetIfrs();
      case IDKTGSPOLECNOSTIFRS:
        return getIdKtgspolecnostIfrs();
      case NDCASTKAMENAIFRS:
        return getNdCastkamenaIfrs();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case IDKTGSPOLECNOST:
        setIdKtgspolecnost((Number)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case SMENAIFRS:
        setSMenaIfrs((String)value);
        return;
      case SUCETIFRS:
        setSUcetIfrs((String)value);
        return;
      case IDKTGSPOLECNOSTIFRS:
        setIdKtgspolecnostIfrs((Number)value);
        return;
      case NDCASTKAMENAIFRS:
        setNdCastkamenaIfrs((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }
}