package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpDokladmenovapoziceImpl extends EntityImpl 
{
  protected static final int IDDOKLAD = 0;
  protected static final int SMENA = 1;
  protected static final int NDCASTKAMENA = 2;
  protected static final int NDCASTKALOCAL = 3;
  protected static final int SUCET = 4;
  protected static final int SPOPIS = 5;
  protected static final int NDCASTKACNB = 6;
  protected static final int CMENOVAPOZICE = 7;
  protected static final int SLOCALE = 8;
  protected static final int SUCETUNIF = 9;
  protected static final int SPOPISORIGINAL = 10;

















  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpDokladmenovapoziceImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.VwKpDokladmenovapozice");
    }
    return mDefinitionObject;
  }


















  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOKLAD:
        return getIdDoklad();
      case SMENA:
        return getSMena();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case SUCET:
        return getSUcet();
      case SPOPIS:
        return getSPopis();
      case NDCASTKACNB:
        return getNdCastkacnb();
      case CMENOVAPOZICE:
        return getCMenovapozice();
      case SLOCALE:
        return getSLocale();
      case SUCETUNIF:
        return getSUcetunif();
      case SPOPISORIGINAL:
        return getSPopisoriginal();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case SPOPIS:
        setSPopis((String)value);
        return;
      case NDCASTKACNB:
        setNdCastkacnb((Number)value);
        return;
      case CMENOVAPOZICE:
        setCMenovapozice((String)value);
        return;
      case SLOCALE:
        setSLocale((String)value);
        return;
      case SUCETUNIF:
        setSUcetunif((String)value);
        return;
      case SPOPISORIGINAL:
        setSPopisoriginal((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }


  /**
   * 
   * Gets the attribute value for NdCastkacnb, using the alias name NdCastkacnb
   */
  public Number getNdCastkacnb()
  {
    return (Number)getAttributeInternal(NDCASTKACNB);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkacnb
   */
  public void setNdCastkacnb(Number value)
  {
    setAttributeInternal(NDCASTKACNB, value);
  }


  /**
   * 
   * Gets the attribute value for CMenovapozice, using the alias name CMenovapozice
   */
  public String getCMenovapozice()
  {
    return (String)getAttributeInternal(CMENOVAPOZICE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CMenovapozice
   */
  public void setCMenovapozice(String value)
  {
    setAttributeInternal(CMENOVAPOZICE, value);
  }


  /**
   * 
   * Gets the attribute value for SLocale, using the alias name SLocale
   */
  public String getSLocale()
  {
    return (String)getAttributeInternal(SLOCALE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SLocale
   */
  public void setSLocale(String value)
  {
    setAttributeInternal(SLOCALE, value);
  }


  /**
   * 
   * Gets the attribute value for SUcetunif, using the alias name SUcetunif
   */
  public String getSUcetunif()
  {
    return (String)getAttributeInternal(SUCETUNIF);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetunif
   */
  public void setSUcetunif(String value)
  {
    setAttributeInternal(SUCETUNIF, value);
  }


  /**
   * 
   * Gets the attribute value for SPopisoriginal, using the alias name SPopisoriginal
   */
  public String getSPopisoriginal()
  {
    return (String)getAttributeInternal(SPOPISORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopisoriginal
   */
  public void setSPopisoriginal(String value)
  {
    setAttributeInternal(SPOPISORIGINAL, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idDoklad, String sMena, String sUcet, String sPopis, String cMenovapozice, String sLocale, String sUcetunif)
  {
    return new Key(new Object[] {idDoklad, sMena, sUcet, sPopis, cMenovapozice, sLocale, sUcetunif});
  }












}