package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpDokladvazbyvyparovaneImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDDOKLAD = 1;
  protected static final int IDKTGUCETNISKUPINA = 2;
  protected static final int IDKTGUCETNISPOLECNOSTFROM = 3;
  protected static final int IDKTGUCETNISPOLECNOSTTO = 4;
  protected static final int SMENA = 5;
  protected static final int SUCET = 6;
  protected static final int NDCASTKAMENA = 7;
  protected static final int NDCASTKALOCAL = 8;
  protected static final int NDCASTKAVYPAROVAT = 9;
  protected static final int PARIDKTGUCETNISPOLECNOSTFROM = 10;
  protected static final int PARIDKTGUCETNISPOLECNOSTTO = 11;
  protected static final int PARSMENA = 12;
  protected static final int PARSUCET = 13;
  protected static final int PARNDCASTKAMENA = 14;
  protected static final int PARNDCASTKALOCAL = 15;
  protected static final int PARNDCASTKAVYPAROVAT = 16;
  protected static final int SPOPIS = 17;
  protected static final int PARSPOPIS = 18;
  protected static final int NLPORADILIST = 19;
  protected static final int NLRADEK = 20;
  protected static final int PARNLPORADILIST = 21;
  protected static final int PARNLRADEK = 22;
  protected static final int NDCASTKAMENAORIGINAL = 23;
  protected static final int NDCASTKALOCALORIGINAL = 24;
  protected static final int PARNDCASTKAMENAORIGINAL = 25;
  protected static final int PARNDCASTKALOCALORIGINAL = 26;
  protected static final int SLOCALE = 27;
  protected static final int IDPAR1 = 28;
  protected static final int IDPAR2 = 29;
  protected static final int NLUSERINDEXVAZBA1 = 30;
  protected static final int NLUSERINDEXVAZBA2 = 31;
  protected static final int SUCTYORIGINAL1 = 32;
  protected static final int SUCTYORIGINAL2 = 33;
  protected static final int CPOCITATVAZBY1 = 34;
  protected static final int CPOCITATVAZBY2 = 35;















  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpDokladvazbyvyparovaneImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.VwKpDokladvazbyvyparovane");
    }
    return mDefinitionObject;
  }
















  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetniskupina, using the alias name IdKtgucetniskupina
   */
  public Number getIdKtgucetniskupina()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISKUPINA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetniskupina
   */
  public void setIdKtgucetniskupina(Number value)
  {
    setAttributeInternal(IDKTGUCETNISKUPINA, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnostfrom, using the alias name IdKtgucetnispolecnostfrom
   */
  public Number getIdKtgucetnispolecnostfrom()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOSTFROM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnostfrom
   */
  public void setIdKtgucetnispolecnostfrom(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOSTFROM, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnostto, using the alias name IdKtgucetnispolecnostto
   */
  public Number getIdKtgucetnispolecnostto()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOSTTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnostto
   */
  public void setIdKtgucetnispolecnostto(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOSTTO, value);
  }



  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkavyparovat, using the alias name NdCastkavyparovat
   */
  public Number getNdCastkavyparovat()
  {
    return (Number)getAttributeInternal(NDCASTKAVYPAROVAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkavyparovat
   */
  public void setNdCastkavyparovat(Number value)
  {
    setAttributeInternal(NDCASTKAVYPAROVAT, value);
  }

  /**
   * 
   * Gets the attribute value for ParIdktgucetnispolecnostfrom, using the alias name ParIdktgucetnispolecnostfrom
   */
  public Number getParIdktgucetnispolecnostfrom()
  {
    return (Number)getAttributeInternal(PARIDKTGUCETNISPOLECNOSTFROM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParIdktgucetnispolecnostfrom
   */
  public void setParIdktgucetnispolecnostfrom(Number value)
  {
    setAttributeInternal(PARIDKTGUCETNISPOLECNOSTFROM, value);
  }

  /**
   * 
   * Gets the attribute value for ParIdktgucetnispolecnostto, using the alias name ParIdktgucetnispolecnostto
   */
  public Number getParIdktgucetnispolecnostto()
  {
    return (Number)getAttributeInternal(PARIDKTGUCETNISPOLECNOSTTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParIdktgucetnispolecnostto
   */
  public void setParIdktgucetnispolecnostto(Number value)
  {
    setAttributeInternal(PARIDKTGUCETNISPOLECNOSTTO, value);
  }



  /**
   * 
   * Gets the attribute value for ParSMena, using the alias name ParSMena
   */
  public String getParSMena()
  {
    return (String)getAttributeInternal(PARSMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParSMena
   */
  public void setParSMena(String value)
  {
    setAttributeInternal(PARSMENA, value);
  }

  /**
   * 
   * Gets the attribute value for ParSUcet, using the alias name ParSUcet
   */
  public String getParSUcet()
  {
    return (String)getAttributeInternal(PARSUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParSUcet
   */
  public void setParSUcet(String value)
  {
    setAttributeInternal(PARSUCET, value);
  }

  /**
   * 
   * Gets the attribute value for ParNdCastkamena, using the alias name ParNdCastkamena
   */
  public Number getParNdCastkamena()
  {
    return (Number)getAttributeInternal(PARNDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNdCastkamena
   */
  public void setParNdCastkamena(Number value)
  {
    setAttributeInternal(PARNDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for ParNdCastkalocal, using the alias name ParNdCastkalocal
   */
  public Number getParNdCastkalocal()
  {
    return (Number)getAttributeInternal(PARNDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNdCastkalocal
   */
  public void setParNdCastkalocal(Number value)
  {
    setAttributeInternal(PARNDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for ParNdCastkavyparovat, using the alias name ParNdCastkavyparovat
   */
  public Number getParNdCastkavyparovat()
  {
    return (Number)getAttributeInternal(PARNDCASTKAVYPAROVAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNdCastkavyparovat
   */
  public void setParNdCastkavyparovat(Number value)
  {
    setAttributeInternal(PARNDCASTKAVYPAROVAT, value);
  }

  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDDOKLAD:
        return getIdDoklad();
      case IDKTGUCETNISKUPINA:
        return getIdKtgucetniskupina();
      case IDKTGUCETNISPOLECNOSTFROM:
        return getIdKtgucetnispolecnostfrom();
      case IDKTGUCETNISPOLECNOSTTO:
        return getIdKtgucetnispolecnostto();
      case SMENA:
        return getSMena();
      case SUCET:
        return getSUcet();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case NDCASTKAVYPAROVAT:
        return getNdCastkavyparovat();
      case PARIDKTGUCETNISPOLECNOSTFROM:
        return getParIdktgucetnispolecnostfrom();
      case PARIDKTGUCETNISPOLECNOSTTO:
        return getParIdktgucetnispolecnostto();
      case PARSMENA:
        return getParSMena();
      case PARSUCET:
        return getParSUcet();
      case PARNDCASTKAMENA:
        return getParNdCastkamena();
      case PARNDCASTKALOCAL:
        return getParNdCastkalocal();
      case PARNDCASTKAVYPAROVAT:
        return getParNdCastkavyparovat();
      case SPOPIS:
        return getSPopis();
      case PARSPOPIS:
        return getParSPopis();
      case NLPORADILIST:
        return getNlPoradilist();
      case NLRADEK:
        return getNlRadek();
      case PARNLPORADILIST:
        return getParNlPoradilist();
      case PARNLRADEK:
        return getParNlRadek();
      case NDCASTKAMENAORIGINAL:
        return getNdCastkamenaoriginal();
      case NDCASTKALOCALORIGINAL:
        return getNdCastkalocaloriginal();
      case PARNDCASTKAMENAORIGINAL:
        return getParNdCastkamenaoriginal();
      case PARNDCASTKALOCALORIGINAL:
        return getParNdCastkalocaloriginal();
      case SLOCALE:
        return getSLocale();
      case IDPAR1:
        return getIdPar1();
      case IDPAR2:
        return getIdPar2();
      case NLUSERINDEXVAZBA1:
        return getNlUserindexvazba1();
      case NLUSERINDEXVAZBA2:
        return getNlUserindexvazba2();
      case SUCTYORIGINAL1:
        return getSUctyoriginal1();
      case SUCTYORIGINAL2:
        return getSUctyoriginal2();
      case CPOCITATVAZBY1:
        return getCPocitatvazby1();
      case CPOCITATVAZBY2:
        return getCPocitatvazby2();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case IDKTGUCETNISKUPINA:
        setIdKtgucetniskupina((Number)value);
        return;
      case IDKTGUCETNISPOLECNOSTFROM:
        setIdKtgucetnispolecnostfrom((Number)value);
        return;
      case IDKTGUCETNISPOLECNOSTTO:
        setIdKtgucetnispolecnostto((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case NDCASTKAVYPAROVAT:
        setNdCastkavyparovat((Number)value);
        return;
      case PARIDKTGUCETNISPOLECNOSTFROM:
        setParIdktgucetnispolecnostfrom((Number)value);
        return;
      case PARIDKTGUCETNISPOLECNOSTTO:
        setParIdktgucetnispolecnostto((Number)value);
        return;
      case PARSMENA:
        setParSMena((String)value);
        return;
      case PARSUCET:
        setParSUcet((String)value);
        return;
      case PARNDCASTKAMENA:
        setParNdCastkamena((Number)value);
        return;
      case PARNDCASTKALOCAL:
        setParNdCastkalocal((Number)value);
        return;
      case PARNDCASTKAVYPAROVAT:
        setParNdCastkavyparovat((Number)value);
        return;
      case SPOPIS:
        setSPopis((String)value);
        return;
      case PARSPOPIS:
        setParSPopis((String)value);
        return;
      case NLPORADILIST:
        setNlPoradilist((Number)value);
        return;
      case NLRADEK:
        setNlRadek((Number)value);
        return;
      case PARNLPORADILIST:
        setParNlPoradilist((Number)value);
        return;
      case PARNLRADEK:
        setParNlRadek((Number)value);
        return;
      case NDCASTKAMENAORIGINAL:
        setNdCastkamenaoriginal((Number)value);
        return;
      case NDCASTKALOCALORIGINAL:
        setNdCastkalocaloriginal((Number)value);
        return;
      case PARNDCASTKAMENAORIGINAL:
        setParNdCastkamenaoriginal((Number)value);
        return;
      case PARNDCASTKALOCALORIGINAL:
        setParNdCastkalocaloriginal((Number)value);
        return;
      case SLOCALE:
        setSLocale((String)value);
        return;
      case IDPAR1:
        setIdPar1((Number)value);
        return;
      case IDPAR2:
        setIdPar2((Number)value);
        return;
      case NLUSERINDEXVAZBA1:
        setNlUserindexvazba1((Number)value);
        return;
      case NLUSERINDEXVAZBA2:
        setNlUserindexvazba2((Number)value);
        return;
      case SUCTYORIGINAL1:
        setSUctyoriginal1((String)value);
        return;
      case SUCTYORIGINAL2:
        setSUctyoriginal2((String)value);
        return;
      case CPOCITATVAZBY1:
        setCPocitatvazby1((String)value);
        return;
      case CPOCITATVAZBY2:
        setCPocitatvazby2((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }

  /**
   * 
   * Gets the attribute value for ParSPopis, using the alias name ParSPopis
   */
  public String getParSPopis()
  {
    return (String)getAttributeInternal(PARSPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParSPopis
   */
  public void setParSPopis(String value)
  {
    setAttributeInternal(PARSPOPIS, value);
  }


  /**
   * 
   * Gets the attribute value for NlPoradilist, using the alias name NlPoradilist
   */
  public Number getNlPoradilist()
  {
    return (Number)getAttributeInternal(NLPORADILIST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlPoradilist
   */
  public void setNlPoradilist(Number value)
  {
    setAttributeInternal(NLPORADILIST, value);
  }

  /**
   * 
   * Gets the attribute value for NlRadek, using the alias name NlRadek
   */
  public Number getNlRadek()
  {
    return (Number)getAttributeInternal(NLRADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlRadek
   */
  public void setNlRadek(Number value)
  {
    setAttributeInternal(NLRADEK, value);
  }

  /**
   * 
   * Gets the attribute value for ParNlPoradilist, using the alias name ParNlPoradilist
   */
  public Number getParNlPoradilist()
  {
    return (Number)getAttributeInternal(PARNLPORADILIST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNlPoradilist
   */
  public void setParNlPoradilist(Number value)
  {
    setAttributeInternal(PARNLPORADILIST, value);
  }

  /**
   * 
   * Gets the attribute value for ParNlRadek, using the alias name ParNlRadek
   */
  public Number getParNlRadek()
  {
    return (Number)getAttributeInternal(PARNLRADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNlRadek
   */
  public void setParNlRadek(Number value)
  {
    setAttributeInternal(PARNLRADEK, value);
  }


  /**
   * 
   * Gets the attribute value for NdCastkamenaoriginal, using the alias name NdCastkamenaoriginal
   */
  public Number getNdCastkamenaoriginal()
  {
    return (Number)getAttributeInternal(NDCASTKAMENAORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamenaoriginal
   */
  public void setNdCastkamenaoriginal(Number value)
  {
    setAttributeInternal(NDCASTKAMENAORIGINAL, value);
  }

  /**
   * 
   * Gets the attribute value for ParNdCastkamenaoriginal, using the alias name ParNdCastkamenaoriginal
   */
  public Number getParNdCastkamenaoriginal()
  {
    return (Number)getAttributeInternal(PARNDCASTKAMENAORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNdCastkamenaoriginal
   */
  public void setParNdCastkamenaoriginal(Number value)
  {
    setAttributeInternal(PARNDCASTKAMENAORIGINAL, value);
  }


  /**
   * 
   * Gets the attribute value for SLocale, using the alias name SLocale
   */
  public String getSLocale()
  {
    return (String)getAttributeInternal(SLOCALE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SLocale
   */
  public void setSLocale(String value)
  {
    setAttributeInternal(SLOCALE, value);
  }


  /**
   * 
   * Gets the attribute value for NdCastkalocaloriginal, using the alias name NdCastkalocaloriginal
   */
  public Number getNdCastkalocaloriginal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCALORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocaloriginal
   */
  public void setNdCastkalocaloriginal(Number value)
  {
    setAttributeInternal(NDCASTKALOCALORIGINAL, value);
  }

  /**
   * 
   * Gets the attribute value for ParNdCastkalocaloriginal, using the alias name ParNdCastkalocaloriginal
   */
  public Number getParNdCastkalocaloriginal()
  {
    return (Number)getAttributeInternal(PARNDCASTKALOCALORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ParNdCastkalocaloriginal
   */
  public void setParNdCastkalocaloriginal(Number value)
  {
    setAttributeInternal(PARNDCASTKALOCALORIGINAL, value);
  }


  /**
   * 
   * Gets the attribute value for IdPar1, using the alias name IdPar1
   */
  public Number getIdPar1()
  {
    return (Number)getAttributeInternal(IDPAR1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdPar1
   */
  public void setIdPar1(Number value)
  {
    setAttributeInternal(IDPAR1, value);
  }

  /**
   * 
   * Gets the attribute value for IdPar2, using the alias name IdPar2
   */
  public Number getIdPar2()
  {
    return (Number)getAttributeInternal(IDPAR2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdPar2
   */
  public void setIdPar2(Number value)
  {
    setAttributeInternal(IDPAR2, value);
  }

  /**
   * 
   * Gets the attribute value for NlUserindexvazba1, using the alias name NlUserindexvazba1
   */
  public Number getNlUserindexvazba1()
  {
    return (Number)getAttributeInternal(NLUSERINDEXVAZBA1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlUserindexvazba1
   */
  public void setNlUserindexvazba1(Number value)
  {
    setAttributeInternal(NLUSERINDEXVAZBA1, value);
  }

  /**
   * 
   * Gets the attribute value for NlUserindexvazba2, using the alias name NlUserindexvazba2
   */
  public Number getNlUserindexvazba2()
  {
    return (Number)getAttributeInternal(NLUSERINDEXVAZBA2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlUserindexvazba2
   */
  public void setNlUserindexvazba2(Number value)
  {
    setAttributeInternal(NLUSERINDEXVAZBA2, value);
  }


  /**
   * 
   * Gets the attribute value for SUctyoriginal1, using the alias name SUctyoriginal1
   */
  public String getSUctyoriginal1()
  {
    return (String)getAttributeInternal(SUCTYORIGINAL1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUctyoriginal1
   */
  public void setSUctyoriginal1(String value)
  {
    setAttributeInternal(SUCTYORIGINAL1, value);
  }

  /**
   * 
   * Gets the attribute value for SUctyoriginal2, using the alias name SUctyoriginal2
   */
  public String getSUctyoriginal2()
  {
    return (String)getAttributeInternal(SUCTYORIGINAL2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUctyoriginal2
   */
  public void setSUctyoriginal2(String value)
  {
    setAttributeInternal(SUCTYORIGINAL2, value);
  }


  /**
   * 
   * Gets the attribute value for CPocitatvazby1, using the alias name CPocitatvazby1
   */
  public String getCPocitatvazby1()
  {
    return (String)getAttributeInternal(CPOCITATVAZBY1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CPocitatvazby1
   */
  public void setCPocitatvazby1(String value)
  {
    setAttributeInternal(CPOCITATVAZBY1, value);
  }

  /**
   * 
   * Gets the attribute value for CPocitatvazby2, using the alias name CPocitatvazby2
   */
  public String getCPocitatvazby2()
  {
    return (String)getAttributeInternal(CPOCITATVAZBY2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CPocitatvazby2
   */
  public void setCPocitatvazby2(String value)
  {
    setAttributeInternal(CPOCITATVAZBY2, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id, String sLocale)
  {
    return new Key(new Object[] {id, sLocale});
  }







}