package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwTmpProjekttogenImpl extends EntityImpl 
{
  protected static final int IDKTGPROJEKT = 0;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwTmpProjekttogenImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.VwTmpProjekttogen");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for IdKtgprojekt, using the alias name IdKtgprojekt
   */
  public Number getIdKtgprojekt()
  {
    return (Number)getAttributeInternal(IDKTGPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgprojekt
   */
  public void setIdKtgprojekt(Number value)
  {
    setAttributeInternal(IDKTGPROJEKT, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGPROJEKT:
        return getIdKtgprojekt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGPROJEKT:
        setIdKtgprojekt((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idKtgprojekt)
  {
    return new Key(new Object[] {idKtgprojekt});
  }
}