-- DB_DSA Schema - Data Staging Area
-- Generated from legacy PL/SQL sources
-- Target: Oracle 23c Free

SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

-- ==========================================
-- TABLES
-- ==========================================

-- Table: ADMIN_MAIL_NOTIFICATION


  CREATE TABLE "ADMIN_MAIL_NOTIFICATION" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"LOADPROTISTRANY" CHAR(1 BYTE), 
	"LOADCRM" CHAR(1 BYTE), 
	"ESS_ZMENY_CRM" CHAR(1 BYTE), 
	"ESS_ZMENY_QCZ" CHAR(1 BYTE), 
	"AKTIVNI" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: BCK_KP_S_TOPAS_EMITENTI


  CREATE TABLE "BCK_KP_S_TOPAS_EMITENTI" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"EID" NUMBER(*,0), 
	"ICO" VARCHAR2(10 BYTE), 
	"NAZEV" VARCHAR2(56 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"ULICE" VARCHAR2(32 BYTE), 
	"PSC" VARCHAR2(6 BYTE), 
	"OBEC" VARCHAR2(40 BYTE), 
	"WWW" VARCHAR2(100 BYTE)
   ) ; 

   ;


-- Table: KP_CIS_RKC_INVALID_ICO_QUA


  CREATE TABLE "KP_CIS_RKC_INVALID_ICO_QUA" 
   (	"FIKTIVNI_NUMBER0" VARCHAR2(20 BYTE), 
	"INVALID_RKC_ICO" VARCHAR2(35 BYTE), 
	"RKC_REQUESTED_NAME" VARCHAR2(80 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50 BYTE)
   ) ; 

   ;


-- Table: KP_KTG_PROTISTRANAVYJIMKY


  CREATE TABLE "KP_KTG_PROTISTRANAVYJIMKY" 
   (	"ID" NUMBER(*,0), 
	"ID_DATABAZE" NUMBER(*,0), 
	"S_UCETMASKA" VARCHAR2(10 BYTE), 
	"S_PROTISTRANA" VARCHAR2(10 BYTE), 
	"NL_POZICEOD" NUMBER(*,0) DEFAULT 1
   ) ; 

   ;


-- Table: KP_LOG_CRM_CUST_GROUP_ESS


  CREATE TABLE "KP_LOG_CRM_CUST_GROUP_ESS" 
   (	"ID_LOG" NUMBER(38,0), 
	"DT_LOG" DATE, 
	"CUST_GROUP_NAME" VARCHAR2(100 BYTE), 
	"CUST_GROUP_CODE" VARCHAR2(8 BYTE), 
	"CUST_STRUCT_NAME" VARCHAR2(31 BYTE), 
	"CUST_STRUCT_CODE" VARCHAR2(3 BYTE), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"KIS_VALID" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: KP_LOG_CRM_CUST_GROUP_MEM_ESS


  CREATE TABLE "KP_LOG_CRM_CUST_GROUP_MEM_ESS" 
   (	"ID_LOG" NUMBER(38,0), 
	"DT_LOG" DATE, 
	"CUST_GROUP_NAME" VARCHAR2(100 BYTE), 
	"CUST_GROUP_CODE" VARCHAR2(8 BYTE), 
	"MEMBER_NAME" VARCHAR2(160 BYTE), 
	"MEM_ICO" VARCHAR2(100 BYTE), 
	"MEM_KLID" VARCHAR2(10 BYTE), 
	"MEM_NUMBER0_QCZ" VARCHAR2(10 BYTE), 
	"MEM_NUMBER0_QSK" VARCHAR2(10 BYTE), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"KIS_VALID" CHAR(1 BYTE), 
	"KIS_ID" NUMBER(38,0)
   ) ; 

   ;


-- Table: KP_LOG_PROTISTRANA


  CREATE TABLE "KP_LOG_PROTISTRANA" 
   (	"ID" NUMBER(*,0), 
	"ID_DATABAZE" NUMBER(*,0), 
	"ID_SPOLECNOST" NUMBER(*,0), 
	"S_ICO" VARCHAR2(35 BYTE), 
	"S_NAZEV" VARCHAR2(200 BYTE), 
	"S_NUMBER0" VARCHAR2(20 BYTE), 
	"FIRMA_ID" NUMBER(*,0), 
	"EO_ID" NUMBER(*,0), 
	"BANKA_ID" NUMBER(*,0), 
	"DOID" VARCHAR2(10 BYTE), 
	"KID" NUMBER(*,0), 
	"PLATINST" VARCHAR2(10 BYTE), 
	"AKCE" CHAR(1 BYTE), 
	"DT_ZMENA" DATE, 
	"S_POM_ICO" VARCHAR2(20 BYTE), 
	"EID" NUMBER(*,0), 
	"DATUMZALOZENI" DATE, 
	"ULICE" VARCHAR2(40 BYTE), 
	"PSC" VARCHAR2(10 BYTE), 
	"MESTO" VARCHAR2(40 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"DIC" VARCHAR2(15 BYTE), 
	"UCETSCP" VARCHAR2(12 BYTE), 
	"REGRMS" VARCHAR2(9 BYTE), 
	"EKONOM_SEKTOR" VARCHAR2(10 BYTE), 
	"TYPOSOBY" CHAR(1 BYTE), 
	"S_AKCE" CHAR(1 BYTE), 
	"DT_DATUMZMENY" DATE DEFAULT SYSDATE
   ) ; 

   ;


-- Table: KP_LOG_QUAESTOR_CUST_GROUP


  CREATE TABLE "KP_LOG_QUAESTOR_CUST_GROUP" 
   (	"ID_LOG" NUMBER(38,0), 
	"DT_LOG" DATE, 
	"NUMBER0" VARCHAR2(20 BYTE), 
	"CUST_GROUP_NAME" VARCHAR2(35 BYTE), 
	"CUST_GROUP_CODE" VARCHAR2(5 BYTE), 
	"CUST_STRUC_NAME" VARCHAR2(35 BYTE), 
	"CUST_STRUC_CODE" VARCHAR2(3 BYTE), 
	"MAIN_INDICATOR" CHAR(1 BYTE), 
	"S_DBLINK" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- Table: KP_LOG_QUAESTOR_RELATION


  CREATE TABLE "KP_LOG_QUAESTOR_RELATION" 
   (	"ID_LOG" NUMBER(38,0), 
	"DT_LOG" DATE, 
	"NUMBER0" VARCHAR2(20 BYTE), 
	"SEARCH_NAME" VARCHAR2(80 BYTE), 
	"SEARCH_IDENTIFICAT" VARCHAR2(35 BYTE), 
	"DATE_UPDATE" DATE, 
	"POM_ICO" VARCHAR2(20 BYTE), 
	"FK_RESIDE_COUNTRY" VARCHAR2(3 BYTE), 
	"INDICATOR_PC" CHAR(1 BYTE), 
	"ENONOM_SEKTOR" VARCHAR2(10 BYTE), 
	"KATEGORIEKOEF" NUMBER(6,3), 
	"OKEC" VARCHAR2(50 BYTE), 
	"DATE_OF_BIRTH_OR_F" DATE, 
	"STREET" VARCHAR2(35 BYTE), 
	"HOUSE_NUMBER_COMPL" VARCHAR2(12 BYTE), 
	"POSTCODE" VARCHAR2(9 BYTE), 
	"CITY" VARCHAR2(35 BYTE), 
	"S_DBLINK" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- Table: KP_RADICIMPORTU


  CREATE TABLE "KP_RADICIMPORTU" 
   (	"ID_FRONTA" NUMBER(*,0), 
	"S_DBLINK" VARCHAR2(32 BYTE), 
	"C_STAV" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: KP_REL_PROTISTRANA


  CREATE TABLE "KP_REL_PROTISTRANA" 
   (	"ID" NUMBER(*,0), 
	"ID_DATABAZE" NUMBER(*,0), 
	"ID_SPOLECNOST" NUMBER(*,0), 
	"S_ICO" VARCHAR2(35 BYTE), 
	"S_NAZEV" VARCHAR2(200 BYTE), 
	"S_NUMBER0" VARCHAR2(20 BYTE), 
	"FIRMA_ID" NUMBER(*,0), 
	"EO_ID" NUMBER(*,0), 
	"BANKA_ID" NUMBER(*,0), 
	"DOID" VARCHAR2(10 BYTE), 
	"KID" NUMBER(*,0), 
	"PLATINST" VARCHAR2(10 BYTE), 
	"AKCE" CHAR(1 BYTE), 
	"DT_ZMENA" DATE, 
	"S_POM_ICO" VARCHAR2(20 BYTE), 
	"EID" NUMBER(*,0), 
	"DATUMZALOZENI" DATE, 
	"ULICE" VARCHAR2(40 BYTE), 
	"PSC" VARCHAR2(10 BYTE), 
	"MESTO" VARCHAR2(40 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"DIC" VARCHAR2(15 BYTE), 
	"UCETSCP" VARCHAR2(12 BYTE), 
	"REGRMS" VARCHAR2(9 BYTE), 
	"EKONOM_SEKTOR" VARCHAR2(10 BYTE), 
	"TYPOSOBY" CHAR(1 BYTE)
   ) ; 

   ;



-- Table: KP_S_CRM_CUST_GROUP_ESS


  CREATE TABLE "KP_S_CRM_CUST_GROUP_ESS" 
   (	"CUST_GROUP_NAME" NVARCHAR2(100), 
	"CUST_GROUP_CODE" NVARCHAR2(8), 
	"CUST_STRUCT_NAME" VARCHAR2(31 BYTE), 
	"CUST_STRUCT_CODE" VARCHAR2(3 BYTE), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"KIS_VALID" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: KP_S_CRM_CUST_GROUP_MEM_ESS


  CREATE TABLE "KP_S_CRM_CUST_GROUP_MEM_ESS" 
   (	"CUST_GROUP_NAME" NVARCHAR2(100), 
	"CUST_GROUP_CODE" NVARCHAR2(8), 
	"MEMBER_NAME" NVARCHAR2(160), 
	"MEM_ICO" NVARCHAR2(100), 
	"MEM_KLID" VARCHAR2(10 BYTE), 
	"MEM_NUMBER0_QCZ" VARCHAR2(10 BYTE), 
	"MEM_NUMBER0_QSK" VARCHAR2(10 BYTE), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"KIS_VALID" CHAR(1 BYTE), 
	"KIS_ID" NUMBER(38,0)
   ) ; 

   ;


-- Table: KP_S_MANUAL


  CREATE TABLE "KP_S_MANUAL" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"S_EXTID" VARCHAR2(20 BYTE), 
	"S_NAZEV" VARCHAR2(256 BYTE), 
	"ID_KTGSPOLECNOST" NUMBER(*,0), 
	"ID_KTGSPOLECNOSTAUTO" NUMBER(*,0), 
	"DT_DATUM" DATE, 
	"S_UZIVATEL" VARCHAR2(30 BYTE), 
	 CONSTRAINT "PK_KPSMANUAL" PRIMARY KEY ("S_DBLINK", "S_EXTID") ENABLE
   ) ; 
  ORGANIZATION INDEX 

 PCTTHRESHOLD 50;



-- Table: KP_S_MANUALTEXT


  CREATE TABLE "KP_S_MANUALTEXT" 
   (	"ID" NUMBER(*,0), 
	"S_DBLINK" VARCHAR2(30 BYTE), 
	"S_TEXT" VARCHAR2(256 BYTE)
   ) ; 

   ;


-- Table: KP_S_QUAESTOR_CUST_GROUP


  CREATE TABLE "KP_S_QUAESTOR_CUST_GROUP" 
   (	"NUMBER0" VARCHAR2(20 BYTE), 
	"CUST_GROUP_NAME" VARCHAR2(35 BYTE), 
	"CUST_GROUP_CODE" VARCHAR2(5 BYTE), 
	"CUST_STRUC_NAME" VARCHAR2(35 BYTE), 
	"CUST_STRUC_CODE" VARCHAR2(3 BYTE), 
	"MAIN_INDICATOR" CHAR(1 BYTE), 
	"S_DBLINK" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- Table: KP_S_QUAESTOR_RELATION


  CREATE TABLE "KP_S_QUAESTOR_RELATION" 
   (	"NUMBER0" VARCHAR2(20 BYTE), 
	"SEARCH_NAME" VARCHAR2(80 BYTE), 
	"SEARCH_IDENTIFICAT" VARCHAR2(35 BYTE), 
	"DATE_UPDATE" DATE, 
	"POM_ICO" VARCHAR2(20 BYTE), 
	"FK_RESIDE_COUNTRY" VARCHAR2(3 BYTE), 
	"INDICATOR_PC" CHAR(1 BYTE), 
	"ENONOM_SEKTOR" VARCHAR2(10 BYTE), 
	"KATEGORIEKOEF" NUMBER(6,3), 
	"OKEC" VARCHAR2(50 BYTE), 
	"DATE_OF_BIRTH_OR_F" DATE, 
	"STREET" VARCHAR2(35 BYTE), 
	"HOUSE_NUMBER_COMPL" VARCHAR2(12 BYTE), 
	"POSTCODE" VARCHAR2(9 BYTE), 
	"CITY" VARCHAR2(35 BYTE), 
	"S_DBLINK" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- Table: KP_S_SEP


  CREATE TABLE "KP_S_SEP" 
   (	"SEP_ID" NUMBER(*,0), 
	"ICO" VARCHAR2(20 BYTE), 
	"RC" VARCHAR2(20 BYTE), 
	"NAZEV" VARCHAR2(128 BYTE), 
	"ID_KTGSPOLECNOST" NUMBER(*,0), 
	"COUNTRY" CHAR(2 BYTE), 
	"FLAG_IGNOROVAT" CHAR(1 BYTE) DEFAULT '0', 
	"POMCOUNT" NUMBER(*,0)
   ) ; 

   ;



-- Table: KP_S_SEP_PROBLEM_BILANCE


  CREATE TABLE "KP_S_SEP_PROBLEM_BILANCE" 
   (	"ID" NUMBER, 
	"ID_DATABAZE" NUMBER(38,0), 
	"SEP_ID" NUMBER(38,0), 
	"ID_DOKLAD" NUMBER(38,0), 
	"VALID" CHAR(1 BYTE), 
	"DATUM" DATE, 
	"UPDATE_VALID" DATE
   ) ; 

   ;



-- Table: KP_S_SEP_STALKER


  CREATE TABLE "KP_S_SEP_STALKER" 
   (	"DBLINK" VARCHAR2(30 BYTE), 
	"STALKER_SEPID" NUMBER(38,0), 
	"STALKER_NAME" VARCHAR2(200 BYTE), 
	"SEP_ID" NUMBER(38,0), 
	"NAZEV" VARCHAR2(200 BYTE), 
	"ICO" VARCHAR2(35 BYTE), 
	"RC" VARCHAR2(35 BYTE), 
	"COUNTRY" CHAR(3 BYTE), 
	"TARGET_SYNC" CHAR(1 BYTE), 
	"FLAG_IGNOROVAT" CHAR(1 BYTE), 
	"TARGET_TYPE" CHAR(1 BYTE), 
	"S_POM_ICO" VARCHAR2(20 BYTE), 
	"ULICE" VARCHAR2(40 BYTE), 
	"PSC" VARCHAR2(10 BYTE), 
	"MESTO" VARCHAR2(40 BYTE), 
	"DIC" VARCHAR2(15 BYTE), 
	"NACE" CHAR(18 BYTE)
   ) ; 

   ;



-- Table: KP_S_SPIN_EK_OBJEKT


  CREATE TABLE "KP_S_SPIN_EK_OBJEKT" 
   (	"EO_ID" NUMBER(*,0), 
	"NAZOV" VARCHAR2(50 BYTE), 
	"MANDANT_ID" NUMBER(*,0)
   ) ; 

   ;


-- Table: KP_S_SPIN_EO_FIRMA


  CREATE TABLE "KP_S_SPIN_EO_FIRMA" 
   (	"EO_ID" NUMBER(*,0), 
	"FIRMA_ID" NUMBER(*,0)
   ) ; 

   ;


-- Table: KP_S_SPIN_FIRMA


  CREATE TABLE "KP_S_SPIN_FIRMA" 
   (	"FIRMA_ID" NUMBER(*,0), 
	"ICO" VARCHAR2(15 BYTE), 
	"NAZOV_FIRMY" VARCHAR2(200 BYTE), 
	"FIRMA_LCTSTAMP" DATE, 
	"MANDANT_ID" NUMBER(*,0), 
	"TYP_FIRMY_ID" NUMBER(*,0), 
	"ULICE" VARCHAR2(50 BYTE), 
	"NAZOV_MESTA" VARCHAR2(30 BYTE), 
	"PSC" VARCHAR2(10 BYTE), 
	"STAT" VARCHAR2(2 BYTE)
   ) ; 

   ;


-- Table: KP_S_SPIN_PEN_USTAV


  CREATE TABLE "KP_S_SPIN_PEN_USTAV" 
   (	"BANKA_ID" NUMBER(*,0), 
	"NAZOV_BANKY" VARCHAR2(50 BYTE), 
	"KOD_BANKY" VARCHAR2(15 BYTE), 
	"CISLO_POBOCKY" VARCHAR2(10 BYTE)
   ) ; 

   ;


-- Table: KP_S_TOPAS_DODODBER


  CREATE TABLE "KP_S_TOPAS_DODODBER" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"DOID" VARCHAR2(10 BYTE), 
	"ICO" VARCHAR2(35 BYTE), 
	"NAZEV" VARCHAR2(100 BYTE), 
	"DATOP" DATE, 
	"DIC" VARCHAR2(35 BYTE), 
	"ULICE" VARCHAR2(50 BYTE), 
	"PSC" VARCHAR2(20 BYTE), 
	"OBEC" VARCHAR2(50 BYTE), 
	"ZEME" VARCHAR2(3 BYTE)
   ) ; 

   ;


-- Table: KP_S_TOPAS_EMITENTI


  CREATE TABLE "KP_S_TOPAS_EMITENTI" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"EID" NUMBER(*,0), 
	"ICO" VARCHAR2(11 BYTE), 
	"NAZEV" VARCHAR2(56 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"ULICE" VARCHAR2(32 BYTE), 
	"PSC" VARCHAR2(6 BYTE), 
	"OBEC" VARCHAR2(40 BYTE), 
	"WWW" VARCHAR2(100 BYTE)
   ) ; 

   ;


-- Table: KP_S_TOPAS_KLIENTI


  CREATE TABLE "KP_S_TOPAS_KLIENTI" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"KID" NUMBER(*,0), 
	"ICO" VARCHAR2(11 BYTE), 
	"NAZEV" VARCHAR2(56 BYTE), 
	"JMENO" VARCHAR2(30 BYTE), 
	"DATOP" DATE, 
	"TYP" CHAR(1 BYTE), 
	"ULICE" VARCHAR2(40 BYTE), 
	"PSC" VARCHAR2(20 BYTE), 
	"OBEC" VARCHAR2(40 BYTE), 
	"STAT" VARCHAR2(3 BYTE), 
	"UCETSCP" VARCHAR2(12 BYTE), 
	"REGRMS" VARCHAR2(9 BYTE), 
	"KODSTAT" VARCHAR2(2 BYTE), 
	"FINALICO" VARCHAR2(20 BYTE)
   ) ; 

   ;


-- Table: KP_S_TOPAS_PLATINSTITUCE


  CREATE TABLE "KP_S_TOPAS_PLATINSTITUCE" 
   (	"S_DBLINK" VARCHAR2(30 BYTE), 
	"PLATINST" VARCHAR2(10 BYTE), 
	"NAZEV" VARCHAR2(100 BYTE)
   ) ; 

   ;


-- Table: KP_TMP_EPERSPEKTIVAOSOBYPB


  CREATE TABLE "KP_TMP_EPERSPEKTIVAOSOBYPB" 
   (	"OSOBA_ID" NUMBER(38,0), 
	"PRIVATNI_BANKER" VARCHAR2(100 BYTE), 
	"ICO" VARCHAR2(20 BYTE), 
	"NAZEV" VARCHAR2(100 BYTE), 
	"SCP_KLIENT_ID" VARCHAR2(30 BYTE), 
	"ULICE" VARCHAR2(80 BYTE), 
	"MESTO" VARCHAR2(80 BYTE), 
	"PSC" VARCHAR2(10 BYTE), 
	"ICO_CIZINEC" VARCHAR2(20 BYTE)
   ) ; 

   ;


-- Table: KP_TMP_PBKLIENT


  CREATE TABLE "KP_TMP_PBKLIENT" 
   (	"ID_DATABAZE" NUMBER(*,0), 
	"S_ICO" VARCHAR2(20 BYTE), 
	"S_NAZEV" VARCHAR2(100 BYTE), 
	"S_ULICE" VARCHAR2(80 BYTE), 
	"S_MESTO" VARCHAR2(80 BYTE), 
	"S_PSC" VARCHAR2(10 BYTE), 
	"S_STAT" VARCHAR2(5 BYTE), 
	"S_PRIVATNIBANKER" VARCHAR2(100 BYTE), 
	"C_PERSONCORP" CHAR(1 BYTE), 
	"NUMBER0" VARCHAR2(20 BYTE), 
	"KID" NUMBER(*,0), 
	"STREDISKO" VARCHAR2(20 BYTE), 
	"SHORT_NAME" VARCHAR2(20 BYTE)
   ) ; 

   ;


-- Table: KP_TMP_ZDROJDAT


  CREATE TABLE "KP_TMP_ZDROJDAT" 
   (	"ID_EXTSYSTEM" VARCHAR2(20 BYTE), 
	"ID_EXTSYSTEM2" VARCHAR2(35 BYTE), 
	"C_EXTSYSTEM" CHAR(1 BYTE), 
	"S_MENA" VARCHAR2(3 BYTE), 
	"C_STRANA" CHAR(1 BYTE), 
	"S_UCET" VARCHAR2(10 BYTE), 
	"ND_CASTKAMENA" NUMBER(18,2), 
	"ND_CASTKALOCAL" NUMBER(18,2), 
	"S_EXTPROTISTRANA" VARCHAR2(30 BYTE), 
	"S_POPIS" VARCHAR2(128 BYTE), 
	"DATUM" DATE, 
	"S_EXTPROTISTRANA_EO" VARCHAR2(30 BYTE), 
	"S_EXTPROTISTRANA_BANKA" VARCHAR2(30 BYTE), 
	"S_EXTPROTISTRANAICO" VARCHAR2(20 BYTE), 
	"S_EXTPROTISTRANAICO_EO" VARCHAR2(20 BYTE), 
	"S_EXTPROTISTRANAICO_BANKA" VARCHAR2(20 BYTE), 
	"KID" NUMBER(*,0), 
	"DOID" VARCHAR2(10 BYTE), 
	"PLATINST" VARCHAR2(10 BYTE), 
	"BANKA_ID" NUMBER(*,0), 
	"FIRMA_ID" NUMBER(*,0), 
	"EO_ID" NUMBER(*,0), 
	"NUMBER0" NUMBER(*,0), 
	"ID_PROTI_1" NUMBER(*,0), 
	"ID_PROTI_2" NUMBER(*,0), 
	"ID_PROTI_3" NUMBER(*,0), 
	"S_EXTPROTISTRANA_EMITENT" VARCHAR2(15 BYTE), 
	"S_EXTPROTISTRANAICO_EMITENT" VARCHAR2(20 BYTE), 
	"EMITENT_ID" NUMBER(*,0), 
	"ID_PROTI_4" NUMBER(*,0), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"ID_KTGODBOR" NUMBER(*,0), 
	"ID_FRONTA" NUMBER(*,0)
   ) ; 

   ;


-- Table: PLSQL_PROFILER_DATA


  CREATE TABLE "PLSQL_PROFILER_DATA" 
   (	"RUNID" NUMBER, 
	"UNIT_NUMBER" NUMBER, 
	"LINE#" NUMBER, 
	"TOTAL_OCCUR" NUMBER, 
	"TOTAL_TIME" NUMBER, 
	"MIN_TIME" NUMBER, 
	"MAX_TIME" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" NUMBER, 
	"SPARE4" NUMBER
   ) ; 

   ;



-- Table: PLSQL_PROFILER_RUNS


  CREATE TABLE "PLSQL_PROFILER_RUNS" 
   (	"RUNID" NUMBER, 
	"RELATED_RUN" NUMBER, 
	"RUN_OWNER" VARCHAR2(32 BYTE), 
	"RUN_DATE" DATE, 
	"RUN_COMMENT" VARCHAR2(2047 BYTE), 
	"RUN_TOTAL_TIME" NUMBER, 
	"RUN_SYSTEM_INFO" VARCHAR2(2047 BYTE), 
	"RUN_COMMENT1" VARCHAR2(2047 BYTE), 
	"SPARE1" VARCHAR2(256 BYTE)
   ) ; 

   ;



-- Table: PLSQL_PROFILER_UNITS


  CREATE TABLE "PLSQL_PROFILER_UNITS" 
   (	"RUNID" NUMBER, 
	"UNIT_NUMBER" NUMBER, 
	"UNIT_TYPE" VARCHAR2(32 BYTE), 
	"UNIT_OWNER" VARCHAR2(32 BYTE), 
	"UNIT_NAME" VARCHAR2(32 BYTE), 
	"UNIT_TIMESTAMP" DATE, 
	"TOTAL_TIME" NUMBER DEFAULT 0, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER
   ) ; 

   ;



-- Table: Q_ALL_GENERATION


  CREATE TABLE "Q_ALL_GENERATION" 
   (	"KIND" CHAR(1 BYTE), 
	"GEN_DATE" DATE, 
	"TIME_GENERATED" DATE, 
	"FK_GEN_ID" CHAR(20 BYTE), 
	"GEN_DATE_FROM" DATE, 
	"Q_FROM" CHAR(3 BYTE)
   ) ; 

   ;


-- Table: Q_REP_BOOKING


  CREATE TABLE "Q_REP_BOOKING" 
   (	"BOOKING_ID" CHAR(20 BYTE), 
	"PC_ID" CHAR(20 BYTE), 
	"PROD_NUMBER" CHAR(35 BYTE), 
	"DESCRIPTION" CHAR(50 BYTE), 
	"BOOK_CURRENCY" CHAR(3 BYTE), 
	"BOOK_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"GL_SYNTETIC" VARCHAR2(35 BYTE), 
	"AMOUNT" NUMBER(15,2), 
	"LC_AMOUNT" NUMBER(15,2), 
	"OWNER_ID" CHAR(20 BYTE), 
	"IND_DEBIT_CREDIT" CHAR(1 BYTE), 
	"BOOK_NUMBER" VARCHAR2(30 BYTE), 
	"REFERENCE0" CHAR(20 BYTE), 
	"TOPAS_PROTISTRANA" VARCHAR2(10 BYTE), 
	"EKONOM_SEKTOR" VARCHAR2(20 BYTE), 
	"AVAIL_KONTOKORENT" NUMBER(15,2), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"TOPAS_KID" NUMBER(*,0), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"ID_KTGODBOR" NUMBER(*,0), 
	"VYJIMKAPROTISTRANA" CHAR(1 BYTE), 
	"TOPSECUR_PROTISTRANA" VARCHAR2(10 BYTE), 
	"PC_PROD_KIND" CHAR(3 BYTE), 
	"PC_PROD_TYPE" CHAR(3 BYTE), 
	"PC_STATUS" CHAR(2 BYTE), 
	"INTEREST" NUMBER(8,5), 
	"PROD_NUMBER_2" CHAR(35 BYTE), 
	"XIDSL" NUMBER(*,0), 
	"ID_FRONTA" NUMBER(*,0), 
	"JOINPCID" CHAR(20 BYTE), 
	"C_TYPTRANSAKCE" CHAR(1 BYTE), 
	"ID_KTGCENNYPAPIR" NUMBER(*,0), 
	"TOPAS_EMITENT" NUMBER(*,0)
   ) ; 

   ;


-- Table: Q_REP_BOOKING_QCZ


  CREATE TABLE "Q_REP_BOOKING_QCZ" 
   (	"BOOKING_ID" CHAR(20 BYTE), 
	"PC_ID" CHAR(20 BYTE), 
	"PROD_NUMBER" CHAR(35 BYTE), 
	"DESCRIPTION" CHAR(50 BYTE), 
	"BOOK_CURRENCY" CHAR(3 BYTE), 
	"BOOK_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"GL_SYNTETIC" VARCHAR2(35 BYTE), 
	"AMOUNT" NUMBER(15,2), 
	"LC_AMOUNT" NUMBER(15,2), 
	"OWNER_ID" CHAR(20 BYTE), 
	"IND_DEBIT_CREDIT" CHAR(1 BYTE), 
	"BOOK_NUMBER" VARCHAR2(30 BYTE), 
	"REFERENCE0" CHAR(20 BYTE), 
	"TOPAS_PROTISTRANA" VARCHAR2(10 BYTE), 
	"EKONOM_SEKTOR" VARCHAR2(20 BYTE), 
	"AVAIL_KONTOKORENT" NUMBER(15,2), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"TOPAS_KID" NUMBER(*,0), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"ID_KTGODBOR" NUMBER(*,0), 
	"VYJIMKAPROTISTRANA" CHAR(1 BYTE), 
	"TOPSECUR_PROTISTRANA" VARCHAR2(10 BYTE), 
	"PC_PROD_KIND" CHAR(3 BYTE), 
	"PC_PROD_TYPE" CHAR(3 BYTE), 
	"PC_STATUS" CHAR(2 BYTE), 
	"INTEREST" NUMBER(8,5), 
	"PROD_NUMBER_2" CHAR(35 BYTE), 
	"XIDSL" NUMBER(*,0), 
	"ID_FRONTA" NUMBER(*,0), 
	"JOINPCID" CHAR(20 BYTE), 
	"C_TYPTRANSAKCE" CHAR(1 BYTE), 
	"ID_KTGCENNYPAPIR" NUMBER(*,0), 
	"TOPAS_EMITENT" NUMBER(*,0), 
	"FK_GEN_ID" CHAR(20 BYTE)
   ) ; 

   ;


-- Table: Q_REP_BOOKING_QSK


  CREATE TABLE "Q_REP_BOOKING_QSK" 
   (	"BOOKING_ID" CHAR(20 BYTE), 
	"PC_ID" CHAR(20 BYTE), 
	"PROD_NUMBER" CHAR(35 BYTE), 
	"DESCRIPTION" CHAR(50 BYTE), 
	"BOOK_CURRENCY" CHAR(3 BYTE), 
	"BOOK_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"GL_SYNTETIC" VARCHAR2(35 BYTE), 
	"AMOUNT" NUMBER(15,2), 
	"LC_AMOUNT" NUMBER(15,2), 
	"OWNER_ID" CHAR(20 BYTE), 
	"IND_DEBIT_CREDIT" CHAR(1 BYTE), 
	"BOOK_NUMBER" VARCHAR2(30 BYTE), 
	"REFERENCE0" CHAR(20 BYTE), 
	"TOPAS_PROTISTRANA" VARCHAR2(10 BYTE), 
	"EKONOM_SEKTOR" VARCHAR2(20 BYTE), 
	"AVAIL_KONTOKORENT" NUMBER(15,2), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"TOPAS_KID" NUMBER(*,0), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"ID_KTGODBOR" NUMBER(*,0), 
	"VYJIMKAPROTISTRANA" CHAR(1 BYTE), 
	"TOPSECUR_PROTISTRANA" VARCHAR2(10 BYTE), 
	"PC_PROD_KIND" CHAR(3 BYTE), 
	"PC_PROD_TYPE" CHAR(3 BYTE), 
	"PC_STATUS" CHAR(2 BYTE), 
	"INTEREST" NUMBER(8,5), 
	"PROD_NUMBER_2" CHAR(35 BYTE), 
	"XIDSL" NUMBER(*,0), 
	"ID_FRONTA" NUMBER(*,0), 
	"JOINPCID" CHAR(20 BYTE), 
	"C_TYPTRANSAKCE" CHAR(1 BYTE), 
	"ID_KTGCENNYPAPIR" NUMBER(*,0), 
	"TOPAS_EMITENT" NUMBER(*,0), 
	"FK_GEN_ID" CHAR(20 BYTE)
   ) ; 

   ;


-- Table: Q_REP_KONTROLA


  CREATE TABLE "Q_REP_KONTROLA" 
   (	"ID" NUMBER, 
	"DATUM" DATE, 
	"KIND" CHAR(1 BYTE), 
	"GL_SYNTETIC" CHAR(35 BYTE), 
	"BOOK_CURRENCY" CHAR(3 BYTE), 
	"BIS_BALANCE" NUMBER(15,2), 
	"FEIS_BALANCE" NUMBER(15,2), 
	"DIFFERENCE" NUMBER(15,2), 
	"FK_GEN_ID" CHAR(20 BYTE), 
	"QSOURCE" CHAR(3 BYTE), 
	"DATE_INSERT" DATE
   ) ; 

   ;



-- Table: TMP_ID


  CREATE GLOBAL TEMPORARY TABLE "TMP_ID" 
   (	"ID" NUMBER(*,0)
   ) ON COMMIT PRESERVE ROWS ;


-- Table: TR_TABLE1


  CREATE TABLE "TR_TABLE1" 
   (	"ID" NUMBER(*,0), 
	"MSG" VARCHAR2(100 BYTE)
   ) ; 

   ;


-- Table: T_AIX_POHYBY


  CREATE TABLE "T_AIX_POHYBY" 
   (	"UDID" NUMBER(20,0), 
	"UPID" NUMBER(20,0), 
	"M1D0" NUMBER(10,0), 
	"DATUM" DATE, 
	"UCET" NVARCHAR2(20), 
	"STREDISKO" NVARCHAR2(15), 
	"PROTIUCET" NVARCHAR2(20), 
	"PROTISTREDISKO" NVARCHAR2(15), 
	"TEXT" NVARCHAR2(100), 
	"CASTKA" NUMBER(32,16), 
	"MENA" NVARCHAR2(3), 
	"CASTKAMENY" NUMBER(32,16), 
	"KURZ" NUMBER(38,6), 
	"JEDNOTKA" NUMBER(10,0), 
	"DOID" NVARCHAR2(20), 
	"PARZNAK" NVARCHAR2(30), 
	"VYPZNAK" NUMBER(10,0), 
	"DATUMSPLAT" DATE, 
	"ZAKAZKA" NVARCHAR2(30), 
	"CINNOST" NVARCHAR2(30), 
	"DATUMDPH" DATE, 
	"RELACEDPH" NUMBER(10,0), 
	"SAZBADPH" NUMBER(32,16), 
	"EXPORTLOCK" NUMBER(10,0), 
	"OPID" NUMBER(10,0), 
	"DATOP" NUMBER(10,0), 
	"TOPZKRATKA" NUMBER(10,0), 
	"MANAZER_ID" NVARCHAR2(30), 
	"PROJEKT_ID" NVARCHAR2(30), 
	"XIDSL" NUMBER(10,0), 
	"DOKLAD" VARCHAR2(30 BYTE), 
	"ID_FRONTA" NUMBER(*,0), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"VYJIMKAPROTISTRANA" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: T_AIX_POHYBY_MEZZANINE


  CREATE TABLE "T_AIX_POHYBY_MEZZANINE" 
   (	"UDID" NUMBER(20,0), 
	"UPID" NUMBER(20,0), 
	"M1D0" NUMBER(10,0), 
	"DATUM" DATE, 
	"UCET" NVARCHAR2(20), 
	"STREDISKO" NVARCHAR2(15), 
	"PROTIUCET" NVARCHAR2(20), 
	"PROTISTREDISKO" NVARCHAR2(15), 
	"TEXT" NVARCHAR2(100), 
	"CASTKA" NUMBER(32,16), 
	"MENA" NVARCHAR2(3), 
	"CASTKAMENY" NUMBER(32,16), 
	"KURZ" NUMBER(38,6), 
	"JEDNOTKA" NUMBER(10,0), 
	"DOID" NVARCHAR2(20), 
	"PARZNAK" NVARCHAR2(30), 
	"VYPZNAK" NUMBER(10,0), 
	"DATUMSPLAT" DATE, 
	"ZAKAZKA" NVARCHAR2(30), 
	"CINNOST" NVARCHAR2(30), 
	"DATUMDPH" DATE, 
	"RELACEDPH" NUMBER(10,0), 
	"SAZBADPH" NUMBER(32,16), 
	"EXPORTLOCK" NUMBER(10,0), 
	"OPID" NUMBER(10,0), 
	"DATOP" NUMBER(10,0), 
	"TOPZKRATKA" NUMBER(10,0), 
	"MANAZER_ID" NVARCHAR2(30), 
	"PROJEKT_ID" NVARCHAR2(30), 
	"XIDSL" NUMBER(10,0), 
	"DOKLAD" VARCHAR2(30 BYTE), 
	"ID_FRONTA" NUMBER(*,0), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"VYJIMKAPROTISTRANA" CHAR(1 BYTE)
   ) ; 

   ;


-- Table: T_UCET_POHYBY


  CREATE TABLE "T_UCET_POHYBY" 
   (	"UPID" NUMBER(12,0), 
	"UDID" NUMBER(12,0), 
	"DATUM" DATE, 
	"M1D0" CHAR(1 BYTE), 
	"DATUMSPLAT" DATE, 
	"CASTKA" NUMBER(19,2), 
	"UCET" VARCHAR2(20 BYTE), 
	"STREDISKO" VARCHAR2(30 BYTE), 
	"PROTIUCET" VARCHAR2(20 BYTE), 
	"PROTISTREDISKO" VARCHAR2(30 BYTE), 
	"DOID" VARCHAR2(60 BYTE), 
	"PARZNAK" VARCHAR2(30 BYTE), 
	"ZAKAZKA" VARCHAR2(30 BYTE), 
	"CINNOST" VARCHAR2(30 BYTE), 
	"MENA" VARCHAR2(3 BYTE), 
	"CASTKAMENY" NUMBER(19,2), 
	"KURZ" NUMBER(21,9), 
	"JEDNOTKA" NUMBER(15,6), 
	"TEXT" VARCHAR2(50 BYTE), 
	"OPID" NUMBER(6,0), 
	"DATOP" DATE, 
	"CISLO" NUMBER(9,0), 
	"PORADI" NUMBER(5,0), 
	"PLID" NUMBER(11,0), 
	"TOPEXTDOKLAD" VARCHAR2(20 BYTE), 
	"TOPZKRATKA" VARCHAR2(30 BYTE), 
	"TYPDOKL" VARCHAR2(3 BYTE), 
	"PLATINST" VARCHAR2(10 BYTE), 
	"DOID_ICO" VARCHAR2(20 BYTE), 
	"KLIENT_ICO" VARCHAR2(20 BYTE), 
	"PLATINST_ICO" VARCHAR2(20 BYTE), 
	"KID" NUMBER(*,0), 
	"VYJIMKAPROTISTRANA" VARCHAR2(1 BYTE) DEFAULT '0', 
	"EMITENT_ID" NUMBER(*,0), 
	"EMITENT_ICO" VARCHAR2(10 BYTE), 
	"EMITENT_ZKRATKA" VARCHAR2(15 BYTE), 
	"POCATECNISTAV" CHAR(1 BYTE), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"ID_KTGODBOR" NUMBER(*,0), 
	"XIDSL" NUMBER(*,0), 
	"DOKLAD" VARCHAR2(30 BYTE), 
	"ID_FRONTA" NUMBER(*,0), 
	"C_ZNAKUCET" CHAR(1 BYTE), 
	"UCTOVANODNE" DATE, 
	"X_ISIT_BUDGET_ID" VARCHAR2(20 BYTE)
   ) ; 

    ENABLE ROW MOVEMENT ;



-- ==========================================
-- CONSTRAINTS
-- ==========================================

-- Constraints for: ADMIN_MAIL_NOTIFICATION


  ALTER TABLE "ADMIN_MAIL_NOTIFICATION" ADD CONSTRAINT "MAIL_NOTIFICATION_1_UNIQUE" UNIQUE ("USER_ID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_CIS_RKC_INVALID_ICO_QUA


  ALTER TABLE "KP_CIS_RKC_INVALID_ICO_QUA" MODIFY ("FIKTIVNI_NUMBER0" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_RKC_INVALID_ICO_QUA" MODIFY ("INVALID_RKC_ICO" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_RKC_INVALID_ICO_QUA" MODIFY ("RKC_REQUESTED_NAME" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_RKC_INVALID_ICO_QUA" ADD CONSTRAINT "PK_RKC_INVALID_ICO" PRIMARY KEY ("FIKTIVNI_NUMBER0")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_KTG_PROTISTRANAVYJIMKY


  ALTER TABLE "KP_KTG_PROTISTRANAVYJIMKY" MODIFY ("ID_DATABAZE" CONSTRAINT "NN_KPKTGPROTIVYJIMKY_IDDB" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROTISTRANAVYJIMKY" MODIFY ("NL_POZICEOD" CONSTRAINT "NN_KPPROTISTRANAVYJIMKY" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROTISTRANAVYJIMKY" ADD CONSTRAINT "PK_KPKTGPROTISTRANAVYJIMKY" PRIMARY KEY ("ID")
  USING INDEX "PK_KPKTGPROTISTRANAVYJIMKY"  ENABLE;


-- Constraints for: KP_LOG_QUAESTOR_CUST_GROUP


  ALTER TABLE "KP_LOG_QUAESTOR_CUST_GROUP" ADD CONSTRAINT "PK_LOG_QUAESTOR_CUST_GROUP" PRIMARY KEY ("ID_LOG", "DT_LOG", "NUMBER0", "CUST_GROUP_CODE")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_LOG_QUAESTOR_RELATION


  ALTER TABLE "KP_LOG_QUAESTOR_RELATION" ADD CONSTRAINT "PK_LOG_QUAESTOR_RELATION" PRIMARY KEY ("ID_LOG", "DT_LOG", "NUMBER0")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_RADICIMPORTU


  ALTER TABLE "KP_RADICIMPORTU" MODIFY ("S_DBLINK" CONSTRAINT "NN_KPRADICIMPORT_LINK" NOT NULL ENABLE);
  ALTER TABLE "KP_RADICIMPORTU" ADD CONSTRAINT "PK_KPRADICIMPORT" PRIMARY KEY ("ID_FRONTA")
  USING INDEX "PK_KPRADICIMPORT"  ENABLE;


-- Constraints for: KP_REL_PROTISTRANA


  ALTER TABLE "KP_REL_PROTISTRANA" MODIFY ("ID_DATABAZE" CONSTRAINT "NN_KPRELPROTI_IDDB" NOT NULL ENABLE);
  ALTER TABLE "KP_REL_PROTISTRANA" ADD CONSTRAINT "PK_KPREL_PROTISTRANA" PRIMARY KEY ("ID")
  USING INDEX "PK_KPREL_PROTISTRANA"  ENABLE;


-- Constraints for: KP_S_MANUAL


  ALTER TABLE "KP_S_MANUAL" ADD CONSTRAINT "PK_KPSMANUAL" PRIMARY KEY ("S_DBLINK", "S_EXTID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_S_MANUALTEXT


  ALTER TABLE "KP_S_MANUALTEXT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_S_MANUALTEXT" MODIFY ("S_DBLINK" NOT NULL ENABLE);
  ALTER TABLE "KP_S_MANUALTEXT" MODIFY ("S_TEXT" NOT NULL ENABLE);
  ALTER TABLE "KP_S_MANUALTEXT" ADD CONSTRAINT "PK_KPSMANUALTEXT" PRIMARY KEY ("ID")
  USING INDEX "PK_KPSMANUALTEXT"  ENABLE;


-- Constraints for: KP_S_SEP


  ALTER TABLE "KP_S_SEP" MODIFY ("SEP_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_S_SEP" ADD CONSTRAINT "PK_KPSSEP" PRIMARY KEY ("SEP_ID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_S_SEP_STALKER


  ALTER TABLE "KP_S_SEP_STALKER" MODIFY ("DBLINK" NOT NULL ENABLE);
  ALTER TABLE "KP_S_SEP_STALKER" MODIFY ("STALKER_SEPID" NOT NULL ENABLE);
  ALTER TABLE "KP_S_SEP_STALKER" MODIFY ("SEP_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_S_SEP_STALKER" ADD CONSTRAINT "PK_KP_S_SEP_STALKER" PRIMARY KEY ("STALKER_SEPID", "SEP_ID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: KP_S_SPIN_EK_OBJEKT


  ALTER TABLE "KP_S_SPIN_EK_OBJEKT" ADD CONSTRAINT "PK_KPSSPINEKOBJ" PRIMARY KEY ("EO_ID")
  USING INDEX "PK_KPSSPINEKOBJ"  ENABLE;


-- Constraints for: KP_S_SPIN_EO_FIRMA


  ALTER TABLE "KP_S_SPIN_EO_FIRMA" ADD CONSTRAINT "PK_KPSSPINEOFIRMA" PRIMARY KEY ("EO_ID", "FIRMA_ID")
  USING INDEX "PK_KPSSPINEOFIRMA"  ENABLE;


-- Constraints for: KP_S_SPIN_FIRMA


  ALTER TABLE "KP_S_SPIN_FIRMA" ADD CONSTRAINT "PK_KPSSPINFIRMA" PRIMARY KEY ("FIRMA_ID")
  USING INDEX "PK_KPSSPINFIRMA"  ENABLE;


-- Constraints for: KP_S_SPIN_PEN_USTAV


  ALTER TABLE "KP_S_SPIN_PEN_USTAV" ADD CONSTRAINT "PK_KPSSPINPUSTAV" PRIMARY KEY ("BANKA_ID")
  USING INDEX "PK_KPSSPINPUSTAV"  ENABLE;


-- Constraints for: KP_S_TOPAS_DODODBER


  ALTER TABLE "KP_S_TOPAS_DODODBER" ADD CONSTRAINT "PK_KPSTOPASDODODBER" PRIMARY KEY ("S_DBLINK", "DOID")
  USING INDEX "PK_KPSTOPASDODODBER"  ENABLE;


-- Constraints for: KP_S_TOPAS_EMITENTI


  ALTER TABLE "KP_S_TOPAS_EMITENTI" ADD CONSTRAINT "PK_KPSTOPASEMITENTI" PRIMARY KEY ("S_DBLINK", "EID")
  USING INDEX "PK_KPSTOPASEMITENTI"  ENABLE;


-- Constraints for: KP_S_TOPAS_KLIENTI


  ALTER TABLE "KP_S_TOPAS_KLIENTI" ADD CONSTRAINT "PK_KPSTOPASKLIENT" PRIMARY KEY ("S_DBLINK", "KID")
  USING INDEX "PK_KPSTOPASKLIENT"  ENABLE;


-- Constraints for: KP_S_TOPAS_PLATINSTITUCE


  ALTER TABLE "KP_S_TOPAS_PLATINSTITUCE" ADD CONSTRAINT "PK_KPSTOPASPLATINST" PRIMARY KEY ("S_DBLINK", "PLATINST")
  USING INDEX "PK_KPSTOPASPLATINST"  ENABLE;


-- Constraints for: KP_TMP_EPERSPEKTIVAOSOBYPB


  ALTER TABLE "KP_TMP_EPERSPEKTIVAOSOBYPB" MODIFY ("OSOBA_ID" NOT NULL ENABLE);


-- Constraints for: KP_TMP_PBKLIENT


  ALTER TABLE "KP_TMP_PBKLIENT" MODIFY ("ID_DATABAZE" CONSTRAINT "NN_KTGPBKIENT_IDDB" NOT NULL ENABLE);
  ALTER TABLE "KP_TMP_PBKLIENT" MODIFY ("S_ICO" CONSTRAINT "NN_KTGPBKIENT_ICO" NOT NULL ENABLE);


-- Constraints for: KP_TMP_ZDROJDAT


  ALTER TABLE "KP_TMP_ZDROJDAT" MODIFY ("ID_FRONTA" CONSTRAINT "NN_TMPZDROJDAT_FRONTA" NOT NULL ENABLE);


-- Constraints for: PLSQL_PROFILER_DATA


  ALTER TABLE "PLSQL_PROFILER_DATA" MODIFY ("LINE#" NOT NULL ENABLE);
  ALTER TABLE "PLSQL_PROFILER_DATA" ADD PRIMARY KEY ("RUNID", "UNIT_NUMBER", "LINE#")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: PLSQL_PROFILER_RUNS


  ALTER TABLE "PLSQL_PROFILER_RUNS" ADD PRIMARY KEY ("RUNID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: PLSQL_PROFILER_UNITS


  ALTER TABLE "PLSQL_PROFILER_UNITS" MODIFY ("TOTAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "PLSQL_PROFILER_UNITS" ADD PRIMARY KEY ("RUNID", "UNIT_NUMBER")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: Q_REP_BOOKING


  ALTER TABLE "Q_REP_BOOKING" MODIFY ("BOOKING_ID" CONSTRAINT "NN_QREPBOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("PC_ID" CONSTRAINT "NN_QREPBOOKING_PC_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("PROD_NUMBER" CONSTRAINT "NN_QREPBOOKING_PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("BOOK_CURRENCY" CONSTRAINT "NN_QREPBOOKING_BOOK_CURR" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("BOOK_DATE" CONSTRAINT "NN_QREPBOOKING_BOOKDATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("EFFECTIVE_DATE" CONSTRAINT "NN_QREPBOOKING_EFFDATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("GL_SYNTETIC" CONSTRAINT "NN_QREPBOOKING_GLSYNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("AMOUNT" CONSTRAINT "NN_QREPBOOKING_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("LC_AMOUNT" CONSTRAINT "NN_QREPBOOKING_AMOUNTLC" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("OWNER_ID" CONSTRAINT "NN_QREPBOOKING_OWNER" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("IND_DEBIT_CREDIT" CONSTRAINT "NN_QREPBOOKING_DEBCRED" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" MODIFY ("ID_FRONTA" CONSTRAINT "NN_REPBOOKING_FRONTA" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING" ADD CONSTRAINT "PK_QREPBOOKING" PRIMARY KEY ("ID_FRONTA", "BOOKING_ID")
  USING INDEX "PK_QREPBOOKING"  ENABLE;


-- Constraints for: Q_REP_BOOKING_BCK_2011


  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("PC_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("PROD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("BOOK_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("GL_SYNTETIC" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("LC_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("IND_DEBIT_CREDIT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_BCK_2011" MODIFY ("ID_FRONTA" NOT NULL ENABLE);


-- Constraints for: Q_REP_BOOKING_QCZ


  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("PC_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("PROD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("BOOK_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("GL_SYNTETIC" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("LC_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("IND_DEBIT_CREDIT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QCZ" MODIFY ("ID_FRONTA" NOT NULL ENABLE);


-- Constraints for: Q_REP_BOOKING_QSK


  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("PC_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("PROD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("BOOK_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("GL_SYNTETIC" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("LC_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("IND_DEBIT_CREDIT" NOT NULL ENABLE);
  ALTER TABLE "Q_REP_BOOKING_QSK" MODIFY ("ID_FRONTA" NOT NULL ENABLE);


-- Constraints for: Q_REP_KONTROLA


  ALTER TABLE "Q_REP_KONTROLA" ADD PRIMARY KEY ("ID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: TMP_ID


  ALTER TABLE "TMP_ID" ADD PRIMARY KEY ("ID") ENABLE;


-- Constraints for: TR_TABLE1


  ALTER TABLE "TR_TABLE1" ADD PRIMARY KEY ("ID")
  USING INDEX    COMPUTE STATISTICS 
  
    ENABLE;


-- Constraints for: T_AIX_POHYBY


  ALTER TABLE "T_AIX_POHYBY" MODIFY ("UDID" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("UPID" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("UCET" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("PROTIUCET" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("CASTKA" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("MENA" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("CASTKAMENY" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY" MODIFY ("JEDNOTKA" NOT NULL ENABLE);


-- Constraints for: T_AIX_POHYBY_MEZZANINE


  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("UDID" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("UPID" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("UCET" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("PROTIUCET" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("CASTKA" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("MENA" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("CASTKAMENY" NOT NULL ENABLE);
  ALTER TABLE "T_AIX_POHYBY_MEZZANINE" MODIFY ("JEDNOTKA" NOT NULL ENABLE);


-- Constraints for: T_UCET_POHYBY


  ALTER TABLE "T_UCET_POHYBY" MODIFY ("ID_FRONTA" CONSTRAINT "NN_REPPOHYBY_FRONTA" NOT NULL ENABLE);


-- ==========================================
-- REFERENTIAL CONSTRAINTS
-- ==========================================

-- Ref Constraints for: PLSQL_PROFILER_DATA


  ALTER TABLE "PLSQL_PROFILER_DATA" ADD FOREIGN KEY ("RUNID", "UNIT_NUMBER")
	  REFERENCES "PLSQL_PROFILER_UNITS" ("RUNID", "UNIT_NUMBER") ENABLE;


-- Ref Constraints for: PLSQL_PROFILER_UNITS


  ALTER TABLE "PLSQL_PROFILER_UNITS" ADD FOREIGN KEY ("RUNID")
	  REFERENCES "PLSQL_PROFILER_RUNS" ("RUNID") ENABLE;


-- Schema creation completed
COMMIT;
