--------------------------------------------------------
--  DDL for Table KP_DAT_DOKUMENT
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_DAT_DOKUMENT" 
   (	"ID" NUMBER, 
	"ID_CISDOKUMENT" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"DT_DATUMZADANI" DATE DEFAULT sysdate, 
	"ID_ZADAVATEL" NUMBER, 
	"S_POPIS" VARCHAR2(500 BYTE), 
	"ID_TYPTRANSAKCE" NUMBER, 
	"S_MENA" VARCHAR2(3 BYTE), 
	"S_PISEMNE" VARCHAR2(3 BYTE), 
	"C_TYPIZOVANATRAN" CHAR(1 BYTE), 
	"DT_TYPIZOVANAOD" DATE, 
	"DT_TYPIZOVANADO" DATE, 
	"DT_DATUMZAUCTOVANI" DATE, 
	"ID_SPOLECNOST" NUMBER, 
	"S_CISLODOKLADU" VARCHAR2(20 BYTE), 
	"DT_DATUMSPLATNOSTI" DATE, 
	"ID_APPUSER" NUMBER, 
	"ID_ZAUCT" NUMBER, 
	"S_PROTISTRANA" VARCHAR2(100 BYTE), 
	"ID_CISSTATUS" NUMBER DEFAULT 0, 
	"C_POKLADNITRANSAKCE" CHAR(1 BYTE) DEFAULT '0', 
	"ID_GESTOR" NUMBER, 
	"DT_GESTORSCHVALENO" DATE, 
	"DT_POZADDATUMUHRADY" DATE, 
	"DT_REALDATUMUHRADY" DATE, 
	"DT_GESTORZAMITNUTO" DATE, 
	"S_GESTORZAMITNUTO" VARCHAR2(100 BYTE), 
	"DT_ZADAVATELZAMITNUTO" DATE, 
	"S_ZADAVATELZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_TYPIZLINK" NUMBER, 
	"S_DUVODZRUSENI" VARCHAR2(50 BYTE), 
	"ID_UCSPOLUHRADA" NUMBER, 
	"DT_ZAUCTUHRADA" DATE, 
	"ID_ZAUCTUHRADA" NUMBER, 
	"ID_TYPPRECENENI" NUMBER, 
	"S_UCET" VARCHAR2(10 BYTE), 
	"S_UCET2" VARCHAR2(10 BYTE), 
	"C_DPH" CHAR(1 BYTE) DEFAULT '0', 
	"ID_BUDGET" NUMBER(*,0), 
	"ID_TTDEVELOPER" NUMBER(*,0), 
	"ID_CISUHRADA" NUMBER(*,0), 
	"DT_UCETNIZAMITNUTO" DATE, 
	"S_UCETNIZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_KTGUCETNISPOLECNOST2" NUMBER(*,0), 
	"S_UCETB" VARCHAR2(10 BYTE), 
	"S_UCETB2" VARCHAR2(10 BYTE), 
	"CERPAT_REZERVU" VARCHAR2(1 BYTE), 
	"DT_NAVYSENI_SCHVALENO" DATE, 
	"DT_NAVYSENI_ZAMITNUTO" DATE, 
	"S_NAVYSENI_ZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_NAVYSENI_MB" NUMBER, 
	"CISLOFA" VARCHAR2(20 BYTE), 
	"DATPRIJ" DATE, 
	"DATDPH" DATE, 
	"CASTKA" NUMBER(27,2), 
	"FEIS_PRENOS" CHAR(1 BYTE), 
	"DATODES" DATE, 
	"TYP_FKT" NUMBER(*,0), 
	"C_CAPEX_OPEX" VARCHAR2(1 BYTE), 
	"S_FEISTEXT" VARCHAR2(250 BYTE), 
	"DATVYSTAVENI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

