-- KIS Banking Application - Schema Creation
-- Generated from legacy PL/SQL sources
-- Target: Oracle 23c Free

SET ECHO ON
SET FEEDBACK ON
SET DEFINE OFF

-- ==========================================
-- TABLES
-- ==========================================

-- Table: KP_DAT_DOKUMENT


  CREATE TABLE "KP_DAT_DOKUMENT" 
   (	"ID" NUMBER, 
	"ID_CISDOKUMENT" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"DT_DATUMZADANI" DATE DEFAULT sysdate, 
	"ID_ZADAVATEL" NUMBER, 
	"S_POPIS" VARCHAR2(500 BYTE), 
	"ID_TYPTRANSAKCE" NUMBER, 
	"S_MENA" VARCHAR2(3 BYTE), 
	"S_PISEMNE" VARCHAR2(3 BYTE), 
	"C_TYPIZOVANATRAN" CHAR(1 BYTE), 
	"DT_TYPIZOVANAOD" DATE, 
	"DT_TYPIZOVANADO" DATE, 
	"DT_DATUMZAUCTOVANI" DATE, 
	"ID_SPOLECNOST" NUMBER, 
	"S_CISLODOKLADU" VARCHAR2(20 BYTE), 
	"DT_DATUMSPLATNOSTI" DATE, 
	"ID_APPUSER" NUMBER, 
	"ID_ZAUCT" NUMBER, 
	"S_PROTISTRANA" VARCHAR2(100 BYTE), 
	"ID_CISSTATUS" NUMBER DEFAULT 0, 
	"C_POKLADNITRANSAKCE" CHAR(1 BYTE) DEFAULT '0', 
	"ID_GESTOR" NUMBER, 
	"DT_GESTORSCHVALENO" DATE, 
	"DT_POZADDATUMUHRADY" DATE, 
	"DT_REALDATUMUHRADY" DATE, 
	"DT_GESTORZAMITNUTO" DATE, 
	"S_GESTORZAMITNUTO" VARCHAR2(100 BYTE), 
	"DT_ZADAVATELZAMITNUTO" DATE, 
	"S_ZADAVATELZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_TYPIZLINK" NUMBER, 
	"S_DUVODZRUSENI" VARCHAR2(50 BYTE), 
	"ID_UCSPOLUHRADA" NUMBER, 
	"DT_ZAUCTUHRADA" DATE, 
	"ID_ZAUCTUHRADA" NUMBER, 
	"ID_TYPPRECENENI" NUMBER, 
	"S_UCET" VARCHAR2(10 BYTE), 
	"S_UCET2" VARCHAR2(10 BYTE), 
	"C_DPH" CHAR(1 BYTE) DEFAULT '0', 
	"ID_BUDGET" NUMBER(*,0), 
	"ID_TTDEVELOPER" NUMBER(*,0), 
	"ID_CISUHRADA" NUMBER(*,0), 
	"DT_UCETNIZAMITNUTO" DATE, 
	"S_UCETNIZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_KTGUCETNISPOLECNOST2" NUMBER(*,0), 
	"S_UCETB" VARCHAR2(10 BYTE), 
	"S_UCETB2" VARCHAR2(10 BYTE), 
	"CERPAT_REZERVU" VARCHAR2(1 BYTE), 
	"DT_NAVYSENI_SCHVALENO" DATE, 
	"DT_NAVYSENI_ZAMITNUTO" DATE, 
	"S_NAVYSENI_ZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_NAVYSENI_MB" NUMBER, 
	"CISLOFA" VARCHAR2(20 BYTE), 
	"DATPRIJ" DATE, 
	"DATDPH" DATE, 
	"CASTKA" NUMBER(27,2), 
	"FEIS_PRENOS" CHAR(1 BYTE), 
	"DATODES" DATE, 
	"TYP_FKT" NUMBER(*,0), 
	"C_CAPEX_OPEX" VARCHAR2(1 BYTE), 
	"S_FEISTEXT" VARCHAR2(250 BYTE), 
	"DATVYSTAVENI" DATE
   ) ; 

   ;



-- Table: KP_DAT_DOKUMENTRADEK


  CREATE TABLE "KP_DAT_DOKUMENTRADEK" 
   (	"ID" NUMBER, 
	"ID_DOKUMENT" NUMBER, 
	"ID_ODBOR" NUMBER, 
	"ID_PROJEKT" NUMBER, 
	"ND_CASTKA" NUMBER(15,2), 
	"ID_ODBOROO" NUMBER, 
	"DT_SCHVALENOODBOR" DATE, 
	"ID_PROJEKTMAN" NUMBER, 
	"DT_SCHVALENOPROJEKT" DATE, 
	"ID_UCSPOLOO" NUMBER, 
	"DT_SCHVALENOUCSPOL" DATE, 
	"ID_UCSPOLTOP" NUMBER, 
	"DT_SCHVALENOTOP" DATE, 
	"S_KOMENTAR" VARCHAR2(100 BYTE), 
	"DT_DATUMPREFAKT" DATE, 
	"ID_PREFAKT" NUMBER, 
	"C_KPREFAKT" CHAR(1 BYTE), 
	"DT_DATUMZADANI" DATE DEFAULT sysdate, 
	"C_REMOVED" CHAR(1 BYTE) DEFAULT '0', 
	"C_ZOBJEDNAVKY" CHAR(1 BYTE) DEFAULT '0', 
	"ID_ZAMITNUTO" NUMBER, 
	"DT_ZAMITNUTO" DATE, 
	"S_ZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_DOKUMENTORIG" NUMBER, 
	"ID_ODBOROOREAL" NUMBER, 
	"ID_PROJEKTMANREAL" NUMBER, 
	"ID_UCSPOLOOREAL" NUMBER, 
	"ID_UCSPOLTOPREAL" NUMBER, 
	"ID_TYPTRANSAKCE" NUMBER(*,0), 
	"ND_OBJ_CASTKA_VOLNA" NUMBER(15,2), 
	"ID_OBJ_RADEK" NUMBER, 
	"ID_BANKAR" NUMBER, 
	"S_ISIT_BUDGET" VARCHAR2(20 BYTE), 
	"C_AKTIVACE_HNED" CHAR(1 BYTE), 
	"DT_AKTIVACE" DATE, 
	"S_SMLOUVA_CISLO" VARCHAR2(100 BYTE), 
	"ID_TYP_SW" NUMBER(8,2), 
	"ID_APLIKACE" NUMBER(8,2), 
	"ID_DRUH_NAKLADU" NUMBER(8,2)
   ) ; 

   ;



-- Table: KP_DAT_BUDGET


  CREATE TABLE "KP_DAT_BUDGET" 
   (	"ID" NUMBER, 
	"ID_KTGODBOR" NUMBER, 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"DT_SCHVALITDO" DATE
   ) ; 

   ;


-- Table: KP_DAT_BUDGETPOLOZKA


  CREATE TABLE "KP_DAT_BUDGETPOLOZKA" 
   (	"ID" NUMBER, 
	"ID_BUDGET" NUMBER, 
	"ID_CISTYPTRAN" NUMBER, 
	"ND_CASTKA" NUMBER(17,2) DEFAULT 0, 
	"S_MENA" VARCHAR2(3 BYTE), 
	"ID_ODBOROO" NUMBER, 
	"DT_SCHVALENOODBOR" DATE, 
	"ID_GESTOR" NUMBER, 
	"DT_SCHVALENOGESTOR" DATE, 
	"ID_UCSPOLOO" NUMBER, 
	"DT_SCHVALENOUCSPOL" DATE, 
	"ID_UCSPOLTOP" NUMBER, 
	"DT_SCHVALENOTOP" DATE, 
	"S_POZNAMKA" VARCHAR2(250 BYTE), 
	"ID_APPUSER" NUMBER
   ) ; 

   ;


-- Table: KP_CIS_DOKUMENT


  CREATE TABLE "KP_CIS_DOKUMENT" 
   (	"ID" NUMBER, 
	"S_POPIS" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- Table: KP_CIS_DOKUMENTSTATUS


  CREATE TABLE "KP_CIS_DOKUMENTSTATUS" 
   (	"ID" NUMBER, 
	"S_POPIS" VARCHAR2(50 BYTE)
   ) ; 

   ;


-- Table: KP_KTG_ODBOR


  CREATE TABLE "KP_KTG_ODBOR" 
   (	"ID" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"S_NAZEV" VARCHAR2(50 BYTE), 
	"S_KOD" VARCHAR2(6 BYTE), 
	"ID_ODPOVEDNAOSOBA" NUMBER, 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"ID_USEK" NUMBER, 
	"ID_KAT" NUMBER, 
	"ID_TYPKAT" NUMBER, 
	"ND_DOCUROVEN1" NUMBER(15,2) DEFAULT 0, 
	"C_BUDGETING" CHAR(1 BYTE) DEFAULT '0', 
	"C_ARCHIVNI" CHAR(1 BYTE) DEFAULT '0', 
	"ID_SPONZOR" NUMBER, 
	"ID_IFRSSEGMENT" NUMBER(*,0), 
	"ID_IFRSSUBSEGMENT" NUMBER(*,0), 
	"ID_MNGSEGMENT" NUMBER(*,0)
   ) ; 

   ;


-- Table: KP_KTG_SPOLECNOST


  CREATE TABLE "KP_KTG_SPOLECNOST" 
   (	"ID" NUMBER(*,0), 
	"S_ICO" VARCHAR2(20 BYTE), 
	"S_NAZEV" VARCHAR2(256 BYTE), 
	"S_POM_ICO" VARCHAR2(20 BYTE), 
	"S_COUNTRY" VARCHAR2(3 BYTE), 
	"C_INDICATOR_PC" CHAR(1 BYTE), 
	"S_EKONOM_SEKTOR" VARCHAR2(10 BYTE), 
	"KATEGORIEKOEF" NUMBER(6,3), 
	"S_OKEC" VARCHAR2(50 BYTE), 
	"ID_KTGSPOLECNOST" NUMBER(*,0), 
	"S_HLAVNIUCETNISKUPINA" VARCHAR2(5 BYTE), 
	"S_KODKATEGORIEPROTISTRANA" CHAR(3 BYTE), 
	"C_LICENCE" CHAR(1 BYTE) DEFAULT '0', 
	"C_LIKVIDACE" CHAR(1 BYTE) DEFAULT '0', 
	"C_SPOLECNERIZENY" CHAR(1 BYTE) DEFAULT '0', 
	"DT_DATUMZALOZENI" DATE, 
	"S_ULICE" VARCHAR2(40 BYTE), 
	"S_PSC" VARCHAR2(10 BYTE), 
	"S_MESTO" VARCHAR2(40 BYTE), 
	"S_DIC" VARCHAR2(15 BYTE), 
	"S_UCETSCP" VARCHAR2(12 BYTE), 
	"S_REGRMS" VARCHAR2(9 BYTE), 
	"DT_QUESTORUPDATE" DATE, 
	"ID_KTG_EXTERNIRATING" NUMBER(*,0), 
	"C_ZONA" CHAR(1 BYTE), 
	"ID_UCETNISYSTEM" NUMBER(*,0), 
	"S_ZVLASTNIVZTAHKJINEMUCLENURKC" VARCHAR2(5 BYTE), 
	"C_EVIEXTDODAVATEL" CHAR(1 BYTE) DEFAULT '0', 
	"C_SKUPINAIC" CHAR(1 BYTE) DEFAULT '0', 
	"C_VPRECHODU" CHAR(1 BYTE) DEFAULT '0', 
	"S_KODKATEGORIEPROTISTRANA_2" CHAR(3 BYTE), 
	"S_COUNTRY_PK" VARCHAR2(3 BYTE), 
	"S_UA_UNIF_COUNTRY" VARCHAR2(3 BYTE), 
	"S_UA_UNIF_ESA" VARCHAR2(25 CHAR), 
	"S_UA_UNIF_NACE" VARCHAR2(25 CHAR), 
	"S_UA_UNIF_LEI" VARCHAR2(250 CHAR), 
	"C_UA_UNIF_DEFAULT_FLAG" CHAR(1 BYTE), 
	"S_UA_UNIF_SHADOW_BANK" VARCHAR2(1 BYTE)
   ) ; 

   ;



-- Table: KP_KTG_UCETNISPOLECNOST


  CREATE TABLE "KP_KTG_UCETNISPOLECNOST" 
   (	"ID" NUMBER(*,0), 
	"ID_CISSUBJECT" NUMBER(*,0), 
	"S_ICO" VARCHAR2(20 BYTE), 
	"SPIN_ID" NUMBER(*,0), 
	"TOPAS_ID" VARCHAR2(30 BYTE), 
	"QUEST_ID" CHAR(20 BYTE), 
	"C_EXTSYSTEM" CHAR(1 BYTE), 
	"S_NAZEV" VARCHAR2(128 BYTE), 
	"C_POCITATROZVAHU" CHAR(1 BYTE) DEFAULT '1', 
	"S_SOUBORPREDPONA" VARCHAR2(20 BYTE), 
	"S_MENA" VARCHAR2(3 BYTE), 
	"S_DBLINK" VARCHAR2(32 BYTE), 
	"C_AUTOMATICKEGENEROVANI" CHAR(1 BYTE) DEFAULT '1', 
	"ID_KATEGORIE" NUMBER(*,0), 
	"C_RKC" CHAR(1 BYTE), 
	"S_ZKRATKA" VARCHAR2(35 BYTE), 
	"DT_LASTCLOSEDATE" DATE, 
	"DT_DATUMARCHIVACE" DATE, 
	"C_OPCE" CHAR(1 BYTE) DEFAULT '0', 
	"ID_CISKATSPOL" NUMBER DEFAULT 0, 
	"ID_ZODPOVEDNAUCETNI" NUMBER, 
	"ID_ODPOVEDNAOSOBA" NUMBER, 
	"ID_ADMINISTRATOR" NUMBER, 
	"DT_RELATIVEDATE" DATE, 
	"ID_TOPMNG" NUMBER, 
	"S_POZNAMKA" VARCHAR2(10 BYTE), 
	"C_DANOVAZTRATA" CHAR(1 BYTE) DEFAULT '0', 
	"ID_CISOPCE" NUMBER DEFAULT 1, 
	"ND_DOCUROVEN2" NUMBER(15,2) DEFAULT 0, 
	"S_LOCALE" VARCHAR2(6 BYTE), 
	"C_DOCDISPLAY" CHAR(1 BYTE) DEFAULT '0', 
	"C_PREHLEDDISPLAY" CHAR(1 BYTE) DEFAULT '1', 
	"ID_CISNOMINEE" NUMBER DEFAULT 1, 
	"NL_ROKPOCSTAVIMPORTSYSTEM" NUMBER(*,0), 
	"ID_TYPPROJEKTU" NUMBER, 
	"ID_KTGODBOR" NUMBER(*,0), 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"DT_UCETNIOBDOBISTART" DATE, 
	"DT_UCETNIOBDOBIKONEC" DATE, 
	"C_ONLINE" CHAR(1 BYTE) DEFAULT '1', 
	"DT_ONLINEOD" DATE, 
	"C_NOCNIZPRACOVANI" CHAR(1 BYTE) DEFAULT '0', 
	"ID_CISNASTROJUCETNIVYJIMKY" NUMBER(*,0), 
	"ID_CISDATABAZE" NUMBER(*,0), 
	"S_SKUPINALIKE" VARCHAR2(3 BYTE), 
	"ND_BUDGETNAVYSENI_OO" NUMBER(15,2) DEFAULT 0, 
	"ND_BUDGETNAVYSENI_TOP" NUMBER(15,2) DEFAULT 1000, 
	"S_DUVODOFFLINE" VARCHAR2(100 BYTE), 
	"S_UZIVATEL" VARCHAR2(30 BYTE), 
	"ID_MNGSEGMENT" NUMBER(*,0), 
	"ID_SPRAVCEKONSOLIDACE" NUMBER(*,0), 
	"ID_MNGSEGMENTBOSS" NUMBER(*,0), 
	"ID_CENTRALA" NUMBER(*,0), 
	"C_UCETNICTVI_V_IFRS" CHAR(1 BYTE) DEFAULT '0', 
	"C_IFRSPRIMARNI" CHAR(1 BYTE) DEFAULT '0', 
	"DT_UNIFIKOVANEDOKLADY" DATE, 
	"C_FEIS_UCETTYP" CHAR(1 BYTE) DEFAULT '?', 
	"C_TESTOVATMAJUCAST" CHAR(1 BYTE) DEFAULT '0', 
	"C_POCITEJMUPOZICI" CHAR(1 BYTE) DEFAULT '1', 
	"C_MULTISEGMENT" CHAR(1 BYTE) DEFAULT '0', 
	"C_EXPORTJAKOPROTISTRANA" CHAR(1 BYTE) DEFAULT '0', 
	"ID_CISDATABAZE_PARTY" NUMBER(38,0)
   ) ; 

   ;



-- Table: KP_KTG_PROJEKT


  CREATE TABLE "KP_KTG_PROJEKT" 
   (	"ID" NUMBER, 
	"S_NAZEV" VARCHAR2(100 BYTE), 
	"S_CISLOOLD" VARCHAR2(6 BYTE), 
	"ID_STATUS" NUMBER, 
	"DT_DATUMSTATUSZMENA" DATE, 
	"ID_NAVRHUJE" NUMBER, 
	"ID_SPONZOR" NUMBER, 
	"ID_TOP" NUMBER, 
	"ID_PMANAGER" NUMBER, 
	"ID_KATEGORIE" NUMBER, 
	"ID_TYPKATEGORIE" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"ND_NAKLADY" NUMBER(15,2), 
	"S_MENANAKLADY" VARCHAR2(3 BYTE), 
	"ND_INVESTICE" NUMBER(15,2), 
	"S_MENAINVESTICE" VARCHAR2(3 BYTE), 
	"ND_OCENENI" NUMBER(15,2), 
	"S_MENAOCENENI" VARCHAR2(3 BYTE), 
	"DT_STARTOCENENI" DATE, 
	"ID_FREKVENCE" NUMBER, 
	"DT_KONECOCENENI" DATE, 
	"S_POPIS" VARCHAR2(250 BYTE), 
	"S_UZIVATEL" VARCHAR2(20 BYTE), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"ND_DOCUROVEN1" NUMBER(15,2) DEFAULT 0, 
	"ID_PROJEKTNAVRH" NUMBER, 
	"DT_MEMORANDUMDALSI" DATE, 
	"NL_MEMORANDUMMESICU" NUMBER(*,0), 
	"ID_IFRSSEGMENT" NUMBER(*,0), 
	"ID_IFRSSUBSEGMENT" NUMBER(*,0), 
	"ID_MNGSEGMENT" NUMBER(*,0), 
	"ID_TYPBILANCE" NUMBER(*,0), 
	"ID_TYPBUDGETU" NUMBER(*,0), 
	"C_SLEDUJEBUDGET" CHAR(1 BYTE) DEFAULT '0', 
	"ND_BUDGETNAVYSENI_PM" NUMBER(15,2) DEFAULT 0, 
	"ND_BUDGETNAVYSENI_TOP" NUMBER(15,2) DEFAULT 1000, 
	"ID_MNGSEGMENTBOSS" NUMBER(*,0), 
	"C_POUZITMNGSEGMENT" CHAR(1 BYTE) DEFAULT '0'
   ) ; 

   ;


-- Table: KP_CIS_TYPTRANSAKCE


  CREATE TABLE "KP_CIS_TYPTRANSAKCE" 
   (	"ID" NUMBER, 
	"S_POPIS" VARCHAR2(50 BYTE), 
	"S_KOD" VARCHAR2(30 BYTE), 
	"ID_GESTOR_CZ" NUMBER, 
	"ID_GESTOR_SK" NUMBER, 
	"ID_GESTOR_Z" NUMBER, 
	"ID_TYPTRANSAKCEGROUP" NUMBER(*,0), 
	"DT_PLATNOSTOD" DATE DEFAULT to_date('01.01.2005','DD.MM.YYYY'), 
	"DT_PLATNOSTDO" DATE DEFAULT to_date('01.01.2099','DD.MM.YYYY'), 
	"C_PROZASTUPCE" CHAR(1 BYTE) DEFAULT '1', 
	"ND_BUDGETNAVYSENI_GESTOR" NUMBER(15,2) DEFAULT 0, 
	"C_DEVELOPER" CHAR(1 BYTE) DEFAULT '0', 
	"S_KOMENTAR" VARCHAR2(2000 BYTE), 
	"C_SPECIAL" CHAR(1 BYTE) DEFAULT '0', 
	"C_PODVOJNEMIS" CHAR(1 BYTE) DEFAULT '0', 
	"ND_UROVENPROJEKT" NUMBER, 
	"ND_UROVENSPOLECNOST" NUMBER, 
	"ND_UROVENTOP" NUMBER, 
	"S_MENAUP" VARCHAR2(3 BYTE), 
	"S_MENAUS" VARCHAR2(3 BYTE), 
	"S_MENAUT" VARCHAR2(3 BYTE), 
	"C_TISKMAJETEK" CHAR(1 BYTE) DEFAULT '0', 
	"C_BUDGETOVAT" CHAR(1 BYTE) DEFAULT '1', 
	"C_CAPEX_OPEX" CHAR(1 BYTE) DEFAULT 'O'
   ) ; 

   ;


-- Table: KP_CIS_MENA


  CREATE TABLE "KP_CIS_MENA" 
   (	"ID" VARCHAR2(3 BYTE), 
	"S_POPIS" VARCHAR2(64 BYTE), 
	"DT_LASTKURZ" DATE, 
	"DT_LASTKURZAVG" DATE, 
	"DT_NBS_LASTKURZ" DATE, 
	"DT_NBS_LASTKURZAVG" DATE, 
	"CCP_ZDROJ" VARCHAR2(30 BYTE), 
	"CCP_ZPUSOB_VYPOCTU" VARCHAR2(30 BYTE), 
	"CCP_NBS_ZDROJ" VARCHAR2(30 BYTE), 
	"CCP_NBS_ZPUSOB_VYPOCTU" VARCHAR2(30 BYTE)
   ) ; 

   ;


-- ==========================================
-- CONSTRAINTS
-- ==========================================

-- Constraints for: KP_DAT_DOKUMENT


  ALTER TABLE "KP_DAT_DOKUMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_DOKUMENT" MODIFY ("ID_CISDOKUMENT" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "PK_DATDOKUMENT" PRIMARY KEY ("ID")
  USING INDEX "PK_DATDOKUMENT"  ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "CH_KP_DAT_DOCUMENT_CERPAR_R" CHECK (cerpat_rezervu in ('T', 'F') and cerpat_rezervu is not null) ENABLE;


-- Constraints for: KP_DAT_DOKUMENTRADEK


  ALTER TABLE "KP_DAT_DOKUMENTRADEK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" MODIFY ("ID_DOKUMENT" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "PK_DATDOKUMENTRADEK" PRIMARY KEY ("ID")
  USING INDEX "PK_DATDOKUMENTRADEK"  ENABLE;


-- Constraints for: KP_DAT_BUDGET


  ALTER TABLE "KP_DAT_BUDGET" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGET" MODIFY ("DT_PLATNOSTOD" CONSTRAINT "NN_DATBUDGET_PLATNOSTOD" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGET" MODIFY ("DT_PLATNOSTDO" CONSTRAINT "NN_DATBUDGET_PLATNOSTDO" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGET" ADD CONSTRAINT "CH_BUDGET_ODBORPROJEKT" CHECK ((id_ktgOdbor is null or id_ktgProjekt is null) and (id_ktgOdbor is not null or id_ktgProjekt is not null)) ENABLE;
  ALTER TABLE "KP_DAT_BUDGET" ADD CONSTRAINT "PK_DATBUDGET" PRIMARY KEY ("ID")
  USING INDEX "PK_DATBUDGET"  ENABLE;


-- Constraints for: KP_DAT_BUDGETPOLOZKA


  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" MODIFY ("ID_BUDGET" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" MODIFY ("ID_CISTYPTRAN" NOT NULL ENABLE);
  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" ADD CONSTRAINT "PK_DATBUDGETPOLOZKA" PRIMARY KEY ("ID")
  USING INDEX "PK_DATBUDGETPOLOZKA"  ENABLE;


-- Constraints for: KP_CIS_DOKUMENT


  ALTER TABLE "KP_CIS_DOKUMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_DOKUMENT" ADD CONSTRAINT "PK_CISDOKUMENT" PRIMARY KEY ("ID")
  USING INDEX "PK_CISDOKUMENT"  ENABLE;


-- Constraints for: KP_CIS_DOKUMENTSTATUS


  ALTER TABLE "KP_CIS_DOKUMENTSTATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_DOKUMENTSTATUS" ADD CONSTRAINT "PK_CISDOKUMENTSTATUS" PRIMARY KEY ("ID")
  USING INDEX "PK_CISDOKUMENTSTATUS"  ENABLE;


-- Constraints for: KP_KTG_ODBOR


  ALTER TABLE "KP_KTG_ODBOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_ODBOR" ADD CONSTRAINT "PK_KTGODBOR" PRIMARY KEY ("ID")
  USING INDEX "PK_KTGODBOR"  ENABLE;


-- Constraints for: KP_KTG_SPOLECNOST


  ALTER TABLE "KP_KTG_SPOLECNOST" MODIFY ("ID" CONSTRAINT "NN_KPKTGSPOLECNOST_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_SPOLECNOST" MODIFY ("S_ICO" CONSTRAINT "NN_KTGSPOLECNOST_ICO" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_SPOLECNOST" MODIFY ("S_NAZEV" CONSTRAINT "NN_KTGSPOLECNOST_NAZEV" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "CN_KTGSPOLECNOST_RIZENY" CHECK ( c_spolecneRizeny  is not null and c_spolecneRizeny in ('0','1') ) ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "CN_KTGSPOLECNOST_LIKVIDACE" CHECK ( c_likvidace  is not null and c_likvidace in ('0','1') ) ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "CN_KTGSPOLECNOST_LICENCE" CHECK ( c_licence  is not null and c_licence in ('0','1') ) ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "UN_KTGSPOLECNOST_ICO" UNIQUE ("S_ICO")
  USING INDEX "UN_KTGSPOLECNOST_ICO"  ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "PK_KPKTGSPOLECNOST" PRIMARY KEY ("ID")
  USING INDEX "PK_KPKTGSPOLECNOST"  ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "CH_KTGSPOLECNOST_VPRECHODU" CHECK (c_vPrechodu in ('0','1')) ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "CH_KTGSPOLECNOST_SKUPIC" CHECK (c_skupinaIc in ('0','1')) ENABLE;


-- Constraints for: KP_KTG_UCETNISPOLECNOST


  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("ID" CONSTRAINT "NN_KPUCSPOLECNOST_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("ID_CISSUBJECT" CONSTRAINT "NN_KPUCSPOLECNOST_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("S_ICO" CONSTRAINT "NN_KPUCSPOLECNOST_ICO" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("S_SOUBORPREDPONA" CONSTRAINT "NN_KPUCSPOLECNOST_SOUBOR" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("S_MENA" CONSTRAINT "NN_KPUCSPOLECNOST_MENA" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("S_DBLINK" CONSTRAINT "NN_KPUCSPOLECNOST_DBLINK" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("ID_KATEGORIE" CONSTRAINT "NN_KPUCSPOLECNOST_KATEG" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("S_LOCALE" CONSTRAINT "NN_KPKTGUCTSPOLLOCALE" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("DT_UCETNIOBDOBISTART" CONSTRAINT "NN_KPUCSPOLECNOST_UCOBDSTART" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("DT_UCETNIOBDOBIKONEC" CONSTRAINT "NN_KPUCSPOLECNOST_UCOBDKONEC" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("ID_CISDATABAZE" CONSTRAINT "NN_KPUCSPOLECNOST_DB" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" MODIFY ("C_FEIS_UCETTYP" CONSTRAINT "NN_KPKTGUCSPOL_FEISTYP" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPUCSPOLECNOST_AUTGENER" CHECK ( c_automatickeGenerovani is not null and c_automatickeGenerovani in ( '0', '1', 'm' ) ) ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPUCSPOLECNOST_NOCNI" CHECK ( c_nocniZpracovani is not null and c_nocniZpracovani in ( '0', '1' ) ) ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "UN_KPUCSPOLECNOST_QUESTID" UNIQUE ("QUEST_ID")
  USING INDEX "UN_KPUCSPOLECNOST_QUESTID"  ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "UN_KPUCSPOLECNOST_TOPASID" UNIQUE ("TOPAS_ID")
  USING INDEX "UN_KPUCSPOLECNOST_TOPASID"  ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "UN_KPUCSPOLECNOST_SPINID" UNIQUE ("SPIN_ID")
  USING INDEX "UN_KPUCSPOLECNOST_SPINID"  ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "UN_KPUCSPOLECNOST_ICO" UNIQUE ("S_ICO")
  USING INDEX "UN_KPUCSPOLECNOST_ICO"  ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "PK_KPUCSPOLECNOST" PRIMARY KEY ("ID")
  USING INDEX "PK_KPUCSPOLECNOST"  ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPUCSPOLECNOST_RKC" CHECK ( c_rkc is not null and c_rkc in ( '0', '1' ) ) ENABLE NOVALIDATE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPUCSPOLECNOST_ROZVAHA" CHECK ( c_pocitatRozvahu is not null and c_pocitatRozvahu in ( '0', '1' ) ) ENABLE NOVALIDATE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPKTGUCETSPOL_TESTMU" CHECK ( c_testovatMajUcast is not null and  c_testovatMajUcast in ( '0', '1' )) ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPKTGUCETSPOL_UCIFRS" CHECK ( c_ucetnictvi_v_IFRS is not null and  c_ucetnictvi_v_IFRS in ( '0', '1' )) ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPKTGUCETSPOL_POCITEJMU" CHECK ( c_pocitejMUPozici is not null and  c_pocitejMUPozici in ( '0', '1' )) ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "CN_KPUCSPOLECNOST_EXTSYSTEM" CHECK (c_extSystem is not null and c_extSystem in ( 'Q', 'S', 'T', 'M', 'K', 'I', 'A' )) ENABLE;


-- Constraints for: KP_KTG_PROJEKT


  ALTER TABLE "KP_KTG_PROJEKT" MODIFY ("ID" CONSTRAINT "NN_KPKTGPROJEKT_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROJEKT" MODIFY ("S_NAZEV" CONSTRAINT "NN_KPKTGPROJEKT_NAZEV" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROJEKT" MODIFY ("DT_PLATNOSTOD" CONSTRAINT "NN_KPKTGPROJEKT_PLATNOSTOD" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROJEKT" MODIFY ("DT_PLATNOSTDO" CONSTRAINT "NN_KPKTGPROJEKT_PLATNOSTDO" NOT NULL ENABLE);
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "PK_KPPROJEKT" PRIMARY KEY ("ID")
  USING INDEX "PK_KPPROJEKT"  ENABLE;
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "CH_KPKTGPROJEKT_PMS" CHECK (c_pouzitMngSegment in ('0','1')) ENABLE;


-- Constraints for: KP_CIS_TYPTRANSAKCE


  ALTER TABLE "KP_CIS_TYPTRANSAKCE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" MODIFY ("DT_PLATNOSTOD" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" MODIFY ("DT_PLATNOSTDO" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" MODIFY ("C_CAPEX_OPEX" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" ADD CONSTRAINT "PK_CISTYPTRANSAKCE" PRIMARY KEY ("ID")
  USING INDEX "PK_CISTYPTRANSAKCE"  ENABLE;


-- Constraints for: KP_CIS_MENA


  ALTER TABLE "KP_CIS_MENA" MODIFY ("ID" CONSTRAINT "NN_KPCISMENA_ID" NOT NULL ENABLE);
  ALTER TABLE "KP_CIS_MENA" ADD CONSTRAINT "PK_KPCISMENA" PRIMARY KEY ("ID")
  USING INDEX "PK_KPCISMENA"  ENABLE;


-- ==========================================
-- REFERENTIAL CONSTRAINTS (Foreign Keys)
-- ==========================================

-- Ref Constraints for: KP_DAT_DOKUMENT


  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENTAPPUSER" FOREIGN KEY ("ID_ZADAVATEL")
	  REFERENCES "KTG_APPUSER" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENTCIS" FOREIGN KEY ("ID_CISDOKUMENT")
	  REFERENCES "KP_CIS_DOKUMENT" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENTTYPTRAN" FOREIGN KEY ("ID_TYPTRANSAKCE")
	  REFERENCES "KP_CIS_TYPTRANSAKCE" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENT_TTDEVELOPER" FOREIGN KEY ("ID_TTDEVELOPER")
	  REFERENCES "KP_CIS_TYPTRANSAKCE" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENT_TYPLINK" FOREIGN KEY ("ID_TYPIZLINK")
	  REFERENCES "KP_DAT_DOKUMENT" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENT_TYPPRECENENI" FOREIGN KEY ("ID_TYPPRECENENI")
	  REFERENCES "KP_CIS_PROJEKTCASHFLOWTYP" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENT" ADD CONSTRAINT "FK_DOKUMENT_UCSPOLUHRADA" FOREIGN KEY ("ID_UCSPOLUHRADA")
	  REFERENCES "KP_KTG_UCETNISPOLECNOST" ("ID") ENABLE;


-- Ref Constraints for: KP_DAT_DOKUMENTRADEK


  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "FK_DOKRADEKDOKUMENT" FOREIGN KEY ("ID_DOKUMENT")
	  REFERENCES "KP_DAT_DOKUMENT" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "FK_ISIT_BUDGET" FOREIGN KEY ("S_ISIT_BUDGET")
	  REFERENCES "KP_CIS_ISIT_BUDGET" ("S_KOD") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "FK_DOKU_RADEK_IS_DRUH_NAKL" FOREIGN KEY ("ID_DRUH_NAKLADU")
	  REFERENCES "KP_CIS_ISIT_DRUH_NAKLADU" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "FK_DOKU_RADEK_ISIT_TYP_SW" FOREIGN KEY ("ID_TYP_SW")
	  REFERENCES "KP_CIS_ISIT_TYP_SW" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_DOKUMENTRADEK" ADD CONSTRAINT "FK_DOKU_RADEK_ISIT_APLIKACE" FOREIGN KEY ("ID_APLIKACE")
	  REFERENCES "KP_CIS_ISIT_APLIKACE" ("ID") ENABLE;


-- Ref Constraints for: KP_DAT_BUDGET


  ALTER TABLE "KP_DAT_BUDGET" ADD CONSTRAINT "FK_DATBUDGET_ODBOR" FOREIGN KEY ("ID_KTGODBOR")
	  REFERENCES "KP_KTG_ODBOR" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_BUDGET" ADD CONSTRAINT "FK_DATBUDGET_PROJEKT" FOREIGN KEY ("ID_KTGPROJEKT")
	  REFERENCES "KP_KTG_PROJEKT" ("ID") ENABLE;


-- Ref Constraints for: KP_DAT_BUDGETPOLOZKA


  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" ADD CONSTRAINT "FK_DATBUDGETPOLOZKA_BUDGET" FOREIGN KEY ("ID_BUDGET")
	  REFERENCES "KP_DAT_BUDGET" ("ID") ENABLE;
  ALTER TABLE "KP_DAT_BUDGETPOLOZKA" ADD CONSTRAINT "FK_DATBUDGETPOLOZKA_TT" FOREIGN KEY ("ID_CISTYPTRAN")
	  REFERENCES "KP_CIS_TYPTRANSAKCE" ("ID") ENABLE;


-- Ref Constraints for: KP_KTG_ODBOR


  ALTER TABLE "KP_KTG_ODBOR" ADD CONSTRAINT "FK_ODBORUCSPOL" FOREIGN KEY ("ID_KTGUCETNISPOLECNOST")
	  REFERENCES "KP_KTG_UCETNISPOLECNOST" ("ID") DISABLE;
  ALTER TABLE "KP_KTG_ODBOR" ADD CONSTRAINT "FK_ODBOR_IFRSSEGMENT" FOREIGN KEY ("ID_IFRSSEGMENT")
	  REFERENCES "KP_CIS_IFRSSEGMENT" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_ODBOR" ADD CONSTRAINT "FK_ODBOR_IFRSSUBSEGMENT" FOREIGN KEY ("ID_IFRSSUBSEGMENT")
	  REFERENCES "KP_CIS_IFRSSUBSEGMENT" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_ODBOR" ADD CONSTRAINT "FK_ODBOR_MNGSEGMENT" FOREIGN KEY ("ID_MNGSEGMENT")
	  REFERENCES "KP_CIS_MNGSEGMENT" ("ID") ENABLE;


-- Ref Constraints for: KP_KTG_SPOLECNOST


  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "FK_KPSPOLECNOST" FOREIGN KEY ("ID_KTG_EXTERNIRATING")
	  REFERENCES "KP_KTG_EXTERNIRATING" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "FK_KP_KTG_SPOLEC" FOREIGN KEY ("ID_KTGSPOLECNOST")
	  REFERENCES "KP_KTG_UCETNISPOLECNOST" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_SPOLECNOST" ADD CONSTRAINT "FK_KP_KTG_SPOLECZEME" FOREIGN KEY ("S_COUNTRY")
	  REFERENCES "KP_CIS_STAT" ("ID") ENABLE;


-- Ref Constraints for: KP_KTG_UCETNISPOLECNOST


  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOLECNOST_DB" FOREIGN KEY ("ID_CISDATABAZE")
	  REFERENCES "KP_CIS_DATABAZE" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOLECNOST_KATEG" FOREIGN KEY ("ID_KATEGORIE")
	  REFERENCES "KP_CIS_SPOLECNOSTKATEGORIE" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOLECNOST_KATSPOL" FOREIGN KEY ("ID_CISKATSPOL")
	  REFERENCES "KP_CIS_KATSPOL" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOLECNOST_LOCALE" FOREIGN KEY ("S_LOCALE")
	  REFERENCES "CIS_LOCALE" ("S_LOCALE") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOLECNOST_SUBJECT" FOREIGN KEY ("ID_CISSUBJECT")
	  REFERENCES "KP_CIS_SUBJECT" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_ADMIN" FOREIGN KEY ("ID_ADMINISTRATOR")
	  REFERENCES "KTG_APPUSER" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_ODBOR" FOREIGN KEY ("ID_KTGODBOR")
	  REFERENCES "KP_KTG_ODBOR" ("ID") DISABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_ODPOS" FOREIGN KEY ("ID_ODPOVEDNAOSOBA")
	  REFERENCES "KTG_APPUSER" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_PROJEKT" FOREIGN KEY ("ID_KTGPROJEKT")
	  REFERENCES "KP_KTG_PROJEKT" ("ID") DISABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_ZODPUC" FOREIGN KEY ("ID_ZODPOVEDNAUCETNI")
	  REFERENCES "KTG_APPUSER" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KTGUCETNISPOLECNOST_MNGSEG" FOREIGN KEY ("ID_MNGSEGMENT")
	  REFERENCES "KP_CIS_MNGSEGMENT" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KTGUCETNISPOL_TYPPROJ" FOREIGN KEY ("ID_TYPPROJEKTU")
	  REFERENCES "KP_CIS_TYPPROJEKTU" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_CENTRALA" FOREIGN KEY ("ID_CENTRALA")
	  REFERENCES "KP_KTG_UCETNISPOLECNOST" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_UCETNISPOLECNOST" ADD CONSTRAINT "FK_KPUCSPOL_SPRAVCE" FOREIGN KEY ("ID_SPRAVCEKONSOLIDACE")
	  REFERENCES "KTG_APPUSER" ("ID") ENABLE;


-- Ref Constraints for: KP_KTG_PROJEKT


  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "FK_KPKTGPROJEKT_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "KP_CIS_PROJEKTSTATUS" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "FK_KTGPROJEKT_NAVRH" FOREIGN KEY ("ID_PROJEKTNAVRH")
	  REFERENCES "KP_KTG_PROJEKTNAVRH" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "FK_PROJEKT_MNGSEGMENT" FOREIGN KEY ("ID_MNGSEGMENT")
	  REFERENCES "KP_CIS_MNGSEGMENT" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "FK_PROJEKT_TYPBILANCE" FOREIGN KEY ("ID_TYPBILANCE")
	  REFERENCES "KP_CIS_TYPPROJEKTOVEBILANCE" ("ID") ENABLE;
  ALTER TABLE "KP_KTG_PROJEKT" ADD CONSTRAINT "FK_PROJEKT_TYPBUDGETU" FOREIGN KEY ("ID_TYPBUDGETU")
	  REFERENCES "KP_CIS_TYPBUDGETUPROJEKTU" ("ID") ENABLE;


-- Ref Constraints for: KP_CIS_TYPTRANSAKCE


  ALTER TABLE "KP_CIS_TYPTRANSAKCE" ADD CONSTRAINT "FK_CISTYPTRANSAKCE_TTGROUP" FOREIGN KEY ("ID_TYPTRANSAKCEGROUP")
	  REFERENCES "KP_CIS_TYPTRANSAKCEGROUP" ("ID") ENABLE;
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" ADD CONSTRAINT "FK_TYPTRANSAKCE_MENAUP" FOREIGN KEY ("S_MENAUP")
	  REFERENCES "KP_CIS_MENA" ("ID") ENABLE;
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" ADD CONSTRAINT "FK_TYPTRANSAKCE_MENAUS" FOREIGN KEY ("S_MENAUS")
	  REFERENCES "KP_CIS_MENA" ("ID") ENABLE;
  ALTER TABLE "KP_CIS_TYPTRANSAKCE" ADD CONSTRAINT "FK_TYPTRANSAKCE_MENAUT" FOREIGN KEY ("S_MENAUT")
	  REFERENCES "KP_CIS_MENA" ("ID") ENABLE;


-- Schema creation completed
COMMIT;
