--------------------------------------------------------
--  DDL for Table KP_DAT_DOKUMENT
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_DAT_DOKUMENT" 
   (	"ID" NUMBER, 
	"ID_CISDOKUMENT" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"DT_DATUMZADANI" DATE DEFAULT sysdate, 
	"ID_ZADAVATEL" NUMBER, 
	"S_POPIS" VARCHAR2(500 BYTE), 
	"ID_TYPTRANSAKCE" NUMBER, 
	"S_MENA" VARCHAR2(3 BYTE), 
	"S_PISEMNE" VARCHAR2(3 BYTE), 
	"C_TYPIZOVANATRAN" CHAR(1 BYTE), 
	"DT_TYPIZOVANAOD" DATE, 
	"DT_TYPIZOVANADO" DATE, 
	"DT_DATUMZAUCTOVANI" DATE, 
	"ID_SPOLECNOST" NUMBER, 
	"S_CISLODOKLADU" VARCHAR2(20 BYTE), 
	"DT_DATUMSPLATNOSTI" DATE, 
	"ID_APPUSER" NUMBER, 
	"ID_ZAUCT" NUMBER, 
	"S_PROTISTRANA" VARCHAR2(100 BYTE), 
	"ID_CISSTATUS" NUMBER DEFAULT 0, 
	"C_POKLADNITRANSAKCE" CHAR(1 BYTE) DEFAULT '0', 
	"ID_GESTOR" NUMBER, 
	"DT_GESTORSCHVALENO" DATE, 
	"DT_POZADDATUMUHRADY" DATE, 
	"DT_REALDATUMUHRADY" DATE, 
	"DT_GESTORZAMITNUTO" DATE, 
	"S_GESTORZAMITNUTO" VARCHAR2(100 BYTE), 
	"DT_ZADAVATELZAMITNUTO" DATE, 
	"S_ZADAVATELZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_TYPIZLINK" NUMBER, 
	"S_DUVODZRUSENI" VARCHAR2(50 BYTE), 
	"ID_UCSPOLUHRADA" NUMBER, 
	"DT_ZAUCTUHRADA" DATE, 
	"ID_ZAUCTUHRADA" NUMBER, 
	"ID_TYPPRECENENI" NUMBER, 
	"S_UCET" VARCHAR2(10 BYTE), 
	"S_UCET2" VARCHAR2(10 BYTE), 
	"C_DPH" CHAR(1 BYTE) DEFAULT '0', 
	"ID_BUDGET" NUMBER(*,0), 
	"ID_TTDEVELOPER" NUMBER(*,0), 
	"ID_CISUHRADA" NUMBER(*,0), 
	"DT_UCETNIZAMITNUTO" DATE, 
	"S_UCETNIZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_KTGUCETNISPOLECNOST2" NUMBER(*,0), 
	"S_UCETB" VARCHAR2(10 BYTE), 
	"S_UCETB2" VARCHAR2(10 BYTE), 
	"CERPAT_REZERVU" VARCHAR2(1 BYTE), 
	"DT_NAVYSENI_SCHVALENO" DATE, 
	"DT_NAVYSENI_ZAMITNUTO" DATE, 
	"S_NAVYSENI_ZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_NAVYSENI_MB" NUMBER, 
	"CISLOFA" VARCHAR2(20 BYTE), 
	"DATPRIJ" DATE, 
	"DATDPH" DATE, 
	"CASTKA" NUMBER(27,2), 
	"FEIS_PRENOS" CHAR(1 BYTE), 
	"DATODES" DATE, 
	"TYP_FKT" NUMBER(*,0), 
	"C_CAPEX_OPEX" VARCHAR2(1 BYTE), 
	"S_FEISTEXT" VARCHAR2(250 BYTE), 
	"DATVYSTAVENI" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;

   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."CISLOFA" IS 'Èíslo faktury ve FEIS';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."DATPRIJ" IS 'Datum pøijetí';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."DATDPH" IS 'Datum zdanitelného plnìní';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."CASTKA" IS 'Celková èástka faktury v mìnì';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."FEIS_PRENOS" IS 'Automaticky prenos';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."DATODES" IS 'Datum odeslání  do FEIS';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."TYP_FKT" IS 'typ faktury';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."C_CAPEX_OPEX" IS 'Novy  typ transakce, Capex, Opex, personalni, skoleni...';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."S_FEISTEXT" IS 'text chyby pri zavedeni faktury do FEIS';
   COMMENT ON COLUMN "DB_JT"."KP_DAT_DOKUMENT"."DATVYSTAVENI" IS 'datum vystaveni faktury, vo FEIS sa uzlozi do DATODES !';
--------------------------------------------------------
--  DDL for Table KP_DAT_BUDGET
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_DAT_BUDGET" 
   (	"ID" NUMBER, 
	"ID_KTGODBOR" NUMBER, 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"ID_KTGPROJEKT" NUMBER(*,0), 
	"DT_SCHVALITDO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;
--------------------------------------------------------
--  DDL for Table KP_DAT_DOKUMENTRADEK_10_2016
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_DAT_DOKUMENTRADEK_10_2016" 
   (	"ID" NUMBER, 
	"ID_DOKUMENT" NUMBER, 
	"ID_ODBOR" NUMBER, 
	"ID_PROJEKT" NUMBER, 
	"ND_CASTKA" NUMBER(15,2), 
	"ID_ODBOROO" NUMBER, 
	"DT_SCHVALENOODBOR" DATE, 
	"ID_PROJEKTMAN" NUMBER, 
	"DT_SCHVALENOPROJEKT" DATE, 
	"ID_UCSPOLOO" NUMBER, 
	"DT_SCHVALENOUCSPOL" DATE, 
	"ID_UCSPOLTOP" NUMBER, 
	"DT_SCHVALENOTOP" DATE, 
	"S_KOMENTAR" VARCHAR2(100 BYTE), 
	"DT_DATUMPREFAKT" DATE, 
	"ID_PREFAKT" NUMBER, 
	"C_KPREFAKT" CHAR(1 BYTE), 
	"DT_DATUMZADANI" DATE, 
	"C_REMOVED" CHAR(1 BYTE), 
	"C_ZOBJEDNAVKY" CHAR(1 BYTE), 
	"ID_ZAMITNUTO" NUMBER, 
	"DT_ZAMITNUTO" DATE, 
	"S_ZAMITNUTO" VARCHAR2(100 BYTE), 
	"ID_DOKUMENTORIG" NUMBER, 
	"ID_ODBOROOREAL" NUMBER, 
	"ID_PROJEKTMANREAL" NUMBER, 
	"ID_UCSPOLOOREAL" NUMBER, 
	"ID_UCSPOLTOPREAL" NUMBER, 
	"ID_TYPTRANSAKCE" NUMBER(*,0), 
	"ND_OBJ_CASTKA_VOLNA" NUMBER(15,2), 
	"ID_OBJ_RADEK" NUMBER, 
	"ID_BANKAR" NUMBER, 
	"S_ISIT_BUDGET" VARCHAR2(20 BYTE), 
	"C_AKTIVACE_HNED" CHAR(1 BYTE), 
	"DT_AKTIVACE" DATE, 
	"S_SMLOUVA_CISLO" VARCHAR2(100 BYTE), 
	"ID_TYP_SW" NUMBER(8,2), 
	"ID_APLIKACE" NUMBER(8,2), 
	"ID_DRUH_NAKLADU" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;
--------------------------------------------------------
--  DDL for Table KP_CIS_DOKLAD
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_CIS_DOKLAD" 
   (	"ID" NUMBER(*,0), 
	"S_POPIS" VARCHAR2(64 BYTE), 
	"JAVA_FORMULAR_ID" NUMBER(*,0), 
	"ID_CISFORMULAR" NUMBER(*,0), 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"C_ZAMCENO" CHAR(1 BYTE), 
	"NL_RADEKPASIVAHV" NUMBER(*,0), 
	"C_UNIFIKOVANEUCTY" CHAR(1 BYTE), 
	"NL_RADEKMENSINOVEPODILY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;

   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."ID" IS 'Primarni klic';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."S_POPIS" IS 'volny text pro identifikaci';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."JAVA_FORMULAR_ID" IS 'asi nepouzito';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."ID_CISFORMULAR" IS 'asi nepouzito';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."DT_PLATNOSTOD" IS 'asi nepouzito';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."DT_PLATNOSTDO" IS 'asi nepouzito';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."C_ZAMCENO" IS 'asi nepouzito';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."NL_RADEKPASIVAHV" IS 'Rika na jakem radku v pasivech je hospodarsky vysledek. Je to radek s kterym pracuje kod a vklada na nej napr. kurzove rozdily apod. V mnoha mistech kodu je to však natvrdo - na zmìny definice v této tabulce reaguje pouze novìjší èást kódu. ';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."C_UNIFIKOVANEUCTY" IS 'Kvuli zpetne kompatibilite. Pro generovani podnikatelske varianty - rozlisuje zda nove ma subjekt prehodit na unifikovany. Pouziva se pri generovani variant dokladu.';
   COMMENT ON COLUMN "DB_JT"."KP_CIS_DOKLAD"."NL_RADEKMENSINOVEPODILY" IS 'Na vysledovce je jeden radek, ktery pri kontrole zda souhlasi zisk na pasivech oproti sume vsech castek na vysledovce musime brat s opacnym znamenkem. Jsou to Menšinové podíly na zisku (ztrátì) po zdanìní.
';
   COMMENT ON TABLE "DB_JT"."KP_CIS_DOKLAD"  IS 'Definuje doklady, ktere KIS umi vygenerovat. <br>Kazdy doklad generujici se v KIS zde ma svuj radek - svoje zahlavi. V nasledujicich tabulkach se definuje struktura dokladu.  <a href=''../../db_schema/dokladdefinice.htm''>viz. diagram definice dokladu</a><p>Definuje napøíklad tyto doklady:<ul><li>Bilanèní doklad</li><li>Zkrácený Kamil doklad</li><li>Podnikatelská bilance</li><li> a další</li></ul>';
--------------------------------------------------------
--  DDL for Table KP_CIS_DOKUMENT
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_CIS_DOKUMENT" 
   (	"ID" NUMBER, 
	"S_POPIS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;
--------------------------------------------------------
--  DDL for Table KP_CIS_DOKUMENTSTATUS
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_CIS_DOKUMENTSTATUS" 
   (	"ID" NUMBER, 
	"S_POPIS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;
--------------------------------------------------------
--  DDL for Table KP_KTG_ODBOR
--------------------------------------------------------

  CREATE TABLE "DB_JT"."KP_KTG_ODBOR" 
   (	"ID" NUMBER, 
	"ID_KTGUCETNISPOLECNOST" NUMBER, 
	"S_NAZEV" VARCHAR2(50 BYTE), 
	"S_KOD" VARCHAR2(6 BYTE), 
	"ID_ODPOVEDNAOSOBA" NUMBER, 
	"DT_PLATNOSTOD" DATE, 
	"DT_PLATNOSTDO" DATE, 
	"ID_USEK" NUMBER, 
	"ID_KAT" NUMBER, 
	"ID_TYPKAT" NUMBER, 
	"ND_DOCUROVEN1" NUMBER(15,2) DEFAULT 0, 
	"C_BUDGETING" CHAR(1 BYTE) DEFAULT '0', 
	"C_ARCHIVNI" CHAR(1 BYTE) DEFAULT '0', 
	"ID_SPONZOR" NUMBER, 
	"ID_IFRSSEGMENT" NUMBER(*,0), 
	"ID_IFRSSUBSEGMENT" NUMBER(*,0), 
	"ID_MNGSEGMENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBAJT" ;
