-- KIS Core Tables - Simplified for Oracle 23c

-- Dokument table (Document Header)
CREATE TABLE KP_DAT_DOKUMENT (
    ID NUMBER PRIMARY KEY,
    ID_CISDOKUMENT NUMBER,
    ID_KTGUCETNISPOLECNOST NUMBER,
    DT_DATUMZADANI DATE DEFAULT SYSDATE,
    ID_ZADAVATEL NUMBER,
    S_POPIS VARCHAR2(500),
    ID_TYPTRANSAKCE NUMBER,
    S_MENA VARCHAR2(3),
    DT_DATUMSPLATNOSTI DATE,
    ID_SPOLECNOST NUMBER,
    S_CISLODOKLADU VARCHAR2(20),
    ID_CISSTATUS NUMBER DEFAULT 0,
    ID_BUDGET NUMBER,
    CASTKA NUMBER(27,2),
    CISLOFA VARCHAR2(20),
    DATPRIJ DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Budget table
CREATE TABLE KP_DAT_BUDGET (
    ID NUMBER PRIMARY KEY,
    ID_KTGODBOR NUMBER NOT NULL,
    DT_PLATNOSTOD DATE NOT NULL,
    DT_PLATNOSTDO DATE NOT NULL,
    ID_KTGPROJEKT NUMBER,
    DT_SCHVALITDO DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Budget line items
CREATE TABLE KP_DAT_BUDGETPOLOZKA (
    ID NUMBER PRIMARY KEY,
    ID_BUDGET NUMBER NOT NULL,
    MESIC NUMBER(2),
    PLAN_AMOUNT NUMBER(15,2),
    ACTUAL_AMOUNT NUMBER(15,2) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budgetpolozka_budget FOREIGN KEY (ID_BUDGET) REFERENCES KP_DAT_BUDGET(ID)
);

-- Document line items  
CREATE TABLE KP_DAT_DOKUMENTRADEK (
    ID NUMBER PRIMARY KEY,
    ID_DOKUMENT NUMBER NOT NULL,
    PORADI NUMBER,
    CASTKA NUMBER(15,2),
    S_POPIS VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dokradek_dokument FOREIGN KEY (ID_DOKUMENT) REFERENCES KP_DAT_DOKUMENT(ID)
);

-- Department catalog
CREATE TABLE KP_KTG_ODBOR (
    ID NUMBER PRIMARY KEY,
    S_KOD VARCHAR2(20) UNIQUE NOT NULL,
    S_NAZEV VARCHAR2(200) NOT NULL,
    ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Document type dictionary
CREATE TABLE KP_CIS_DOKUMENT (
    ID NUMBER PRIMARY KEY,
    S_KOD VARCHAR2(20) UNIQUE NOT NULL,
    S_NAZEV VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Document status dictionary
CREATE TABLE KP_CIS_DOKUMENTSTATUS (
    ID NUMBER PRIMARY KEY,
    S_KOD VARCHAR2(20) UNIQUE NOT NULL,
    S_NAZEV VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Company catalog
CREATE TABLE KP_KTG_SPOLECNOST (
    ID NUMBER PRIMARY KEY,
    S_NAZEV VARCHAR2(200) NOT NULL,
    S_ICO VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User table
CREATE TABLE KP_KTG_APPUSER (
    ID NUMBER PRIMARY KEY,
    S_LOGIN VARCHAR2(50) UNIQUE NOT NULL,
    S_JMENO VARCHAR2(100) NOT NULL,
    S_EMAIL VARCHAR2(100),
    S_POZICE VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sequences
CREATE SEQUENCE seq_dokument START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_budget START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE seq_budgetpolozka START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_dokumentradek START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_odbor START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE seq_dokument_typ START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE seq_dokument_status START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE seq_spolecnost START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_appuser START WITH 100 INCREMENT BY 1;

