-- Seed data for KIS Banking Application

-- Users
INSERT INTO KP_KTG_APPUSER (ID, S_LOGIN, S_JMENO, S_EMAIL, S_POZICE) VALUES (1, 'ecerna', 'Eva Černá', 'eva.cerna@jtbank.cz', 'CFO');
INSERT INTO KP_KTG_APPUSER (ID, S_LOGIN, S_JMENO, S_EMAIL, S_POZICE) VALUES (2, 'mnovak', 'Martin Novák', 'martin.novak@jtbank.cz', 'Manager');
INSERT INTO KP_KTG_APPUSER (ID, S_LOGIN, S_JMENO, S_EMAIL, S_POZICE) VALUES (3, 'psvobodova', 'Petra Svobodová', 'petra.svobodova@jtbank.cz', 'Accountant');

-- Departments (Odbory)
INSERT INTO KP_KTG_ODBOR (ID, S_KOD, S_NAZEV, ACTIVE) VALUES (1, 'IT', 'IT Oddělení', 'Y');
INSERT INTO KP_KTG_ODBOR (ID, S_KOD, S_NAZEV, ACTIVE) VALUES (2, 'FIN', 'Finance', 'Y');
INSERT INTO KP_KTG_ODBOR (ID, S_KOD, S_NAZEV, ACTIVE) VALUES (3, 'HR', 'Lidské zdroje', 'Y');
INSERT INTO KP_KTG_ODBOR (ID, S_KOD, S_NAZEV, ACTIVE) VALUES (4, 'OPS', 'Operace', 'Y');

-- Companies
INSERT INTO KP_KTG_SPOLECNOST (ID, S_NAZEV, S_ICO) VALUES (1, 'JT Bank a.s.', '12345678');
INSERT INTO KP_KTG_SPOLECNOST (ID, S_NAZEV, S_ICO) VALUES (2, 'ACME Corp', '87654321');
INSERT INTO KP_KTG_SPOLECNOST (ID, S_NAZEV, S_ICO) VALUES (3, 'Tech Solutions s.r.o.', '11223344');

-- Document types
INSERT INTO KP_CIS_DOKUMENT (ID, S_KOD, S_NAZEV) VALUES (1, 'INVOICE', 'Faktura');
INSERT INTO KP_CIS_DOKUMENT (ID, S_KOD, S_NAZEV) VALUES (2, 'PURCHASE_ORDER', 'Objednávka');
INSERT INTO KP_CIS_DOKUMENT (ID, S_KOD, S_NAZEV) VALUES (3, 'CONTRACT', 'Smlouva');
INSERT INTO KP_CIS_DOKUMENT (ID, S_KOD, S_NAZEV) VALUES (4, 'CREDIT_NOTE', 'Dobropis');

-- Document statuses
INSERT INTO KP_CIS_DOKUMENTSTATUS (ID, S_KOD, S_NAZEV) VALUES (1, 'PENDING_APPROVAL', 'Čeká na schválení');
INSERT INTO KP_CIS_DOKUMENTSTATUS (ID, S_KOD, S_NAZEV) VALUES (2, 'APPROVED', 'Schváleno');
INSERT INTO KP_CIS_DOKUMENTSTATUS (ID, S_KOD, S_NAZEV) VALUES (3, 'REJECTED', 'Zamítnuto');
INSERT INTO KP_CIS_DOKUMENTSTATUS (ID, S_KOD, S_NAZEV) VALUES (4, 'DRAFT', 'Koncept');
INSERT INTO KP_CIS_DOKUMENTSTATUS (ID, S_KOD, S_NAZEV) VALUES (5, 'OVERDUE', 'Po splatnosti');

-- Budgets
INSERT INTO KP_DAT_BUDGET (ID, ID_KTGODBOR, DT_PLATNOSTOD, DT_PLATNOSTDO) 
VALUES (1, 1, DATE '2025-01-01', DATE '2025-12-31');

INSERT INTO KP_DAT_BUDGET (ID, ID_KTGODBOR, DT_PLATNOSTOD, DT_PLATNOSTDO) 
VALUES (2, 2, DATE '2025-01-01', DATE '2025-12-31');

-- Budget line items (monthly)
BEGIN
  FOR i IN 1..12 LOOP
    INSERT INTO KP_DAT_BUDGETPOLOZKA (ID, ID_BUDGET, MESIC, PLAN_AMOUNT, ACTUAL_AMOUNT)
    VALUES (i, 1, i, 200000 + (i * 10000), 195000 + (i * 5000));
  END LOOP;
  
  FOR i IN 1..12 LOOP
    INSERT INTO KP_DAT_BUDGETPOLOZKA (ID, ID_BUDGET, MESIC, PLAN_AMOUNT, ACTUAL_AMOUNT)
    VALUES (12 + i, 2, i, 150000 + (i * 5000), 148000 + (i * 3000));
  END LOOP;
END;
/

-- Documents
INSERT INTO KP_DAT_DOKUMENT (ID, ID_CISDOKUMENT, S_CISLODOKLADU, ID_SPOLECNOST, ID_BUDGET, ID_ZADAVATEL, ID_CISSTATUS, CASTKA, S_MENA, DT_DATUMZADANI, DT_DATUMSPLATNOSTI, S_POPIS)
VALUES (1, 1, 'DOC-2025-0001', 1, 1, 2, 1, 150000, 'CZK', SYSDATE - 10, SYSDATE + 5, 'IT infrastructure upgrade');

INSERT INTO KP_DAT_DOKUMENT (ID, ID_CISDOKUMENT, S_CISLODOKLADU, ID_SPOLECNOST, ID_BUDGET, ID_ZADAVATEL, ID_CISSTATUS, CASTKA, S_MENA, DT_DATUMZADANI, DT_DATUMSPLATNOSTI, S_POPIS)
VALUES (2, 2, 'DOC-2025-0002', 2, 1, 3, 2, 85000, 'CZK', SYSDATE - 15, SYSDATE + 10, 'Office supplies');

INSERT INTO KP_DAT_DOKUMENT (ID, ID_CISDOKUMENT, S_CISLODOKLADU, ID_SPOLECNOST, ID_BUDGET, ID_ZADAVATEL, ID_CISSTATUS, CASTKA, S_MENA, DT_DATUMZADANI, DT_DATUMSPLATNOSTI, S_POPIS)
VALUES (3, 1, 'DOC-2025-0003', 3, 2, 1, 5, 220000, 'CZK', SYSDATE - 30, SYSDATE - 10, 'Consulting services - OVERDUE');

COMMIT;
