package cz.jtbank.konsolidace.mustky;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpUcet2definiceImpl extends EntityImpl 
{
  protected static final int IDDEFLISTBUNKAUCET = 0;
  protected static final int SUCET = 1;
  protected static final int IDCISSUBJECT = 2;
  protected static final int BUNKA = 3;



  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpUcet2definiceImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.mustky.VwKpUcet2definice");
    }
    return mDefinitionObject;
  }




  /**
   * 
   * Gets the attribute value for IdDeflistbunkaucet, using the alias name IdDeflistbunkaucet
   */
  public Number getIdDeflistbunkaucet()
  {
    return (Number)getAttributeInternal(IDDEFLISTBUNKAUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDeflistbunkaucet
   */
  public void setIdDeflistbunkaucet(Number value)
  {
    setAttributeInternal(IDDEFLISTBUNKAUCET, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for IdCissubject, using the alias name IdCissubject
   */
  public Number getIdCissubject()
  {
    return (Number)getAttributeInternal(IDCISSUBJECT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCissubject
   */
  public void setIdCissubject(Number value)
  {
    setAttributeInternal(IDCISSUBJECT, value);
  }

  /**
   * 
   * Gets the attribute value for Bunka, using the alias name Bunka
   */
  public String getBunka()
  {
    return (String)getAttributeInternal(BUNKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Bunka
   */
  public void setBunka(String value)
  {
    setAttributeInternal(BUNKA, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDEFLISTBUNKAUCET:
        return getIdDeflistbunkaucet();
      case SUCET:
        return getSUcet();
      case IDCISSUBJECT:
        return getIdCissubject();
      case BUNKA:
        return getBunka();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDEFLISTBUNKAUCET:
        setIdDeflistbunkaucet((Number)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case IDCISSUBJECT:
        setIdCissubject((Number)value);
        return;
      case BUNKA:
        setBunka((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idDeflistbunkaucet)
  {
    return new Key(new Object[] {idDeflistbunkaucet});
  }




}