package cz.jtbank.konsolidace.fininv;
import cz.jtbank.konsolidace.common.KisException;
import java.sql.*;
import oracle.jbo.*;
import oracle.jbo.server.ApplicationModuleImpl;
import cz.jtbank.konsolidace.protistrany.VwProtistranaViewImpl;
import oracle.jbo.server.DBTransaction;
import cz.jtbank.konsolidace.excel.*;
import cz.jtbank.konsolidace.common.Constants;
import java.io.*;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class FininvModuleImpl extends ApplicationModuleImpl implements cz.jtbank.konsolidace.fininv.common.FininvModule 
{
  /*
   * 
   * This is the default constructor (do not remove)
   */
  public FininvModuleImpl()
  {
  }

  /*
   * 
   * Container's getter for VwFinancniinvesticeView1
   */
  public VwFinancniinvesticeViewImpl getVwFinancniinvesticeView1()
  {
    return (VwFinancniinvesticeViewImpl)findViewObject("VwFinancniinvesticeView1");
  }

  /*
   * 
   * Container's getter for VwFinancniinvemiseView1
   */
  public VwFinancniinvemiseViewImpl getVwFinancniinvemiseView1()
  {
    return (VwFinancniinvemiseViewImpl)findViewObject("VwFinancniinvemiseView1");
  }

  /*
   * 
   * Container's getter for VwFinancniinvemisehistorView1
   */
  public VwFinancniinvemisehistorViewImpl getVwFinancniinvemisehistorView1()
  {
    return (VwFinancniinvemisehistorViewImpl)findViewObject("VwFinancniinvemisehistorView1");
  }

  /*
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("cz.jtbank.konsolidace.fininv", "FininvModuleLocal");
  }


  /*
   * 
   * Container's getter for KpCisMenaView1
   */
  public KpCisMenaViewImpl getKpCisMenaView1()
  {
    return (KpCisMenaViewImpl)findViewObject("KpCisMenaView1");
  }

  /*
   * 
   * Container's getter for VwProtistranyLimitedView1
   */
  public VwProtistranyLimitedViewImpl getVwProtistranyLimitedView1()
  {
    return (VwProtistranyLimitedViewImpl)findViewObject("VwProtistranyLimitedView1");
  }
  
  private String getUser() 
  {
    String user = cz.jtbank.konsolidace.common.Utils.getUserName(this, false);
    return user;
  }

  /**
   * Vloží novou "investici" - tzn. skupinu jednotlivých emisí.
   * @param idSpol id společnosti/protistrany
   * @param mena mena emisí
   * @param isin IČ/ISIN emise
   * @return id vzniklé investice
   * @throws KisException v případě, že se nezdaří vložení
   */
  public int insertFinInv(int idSpol,
                           String mena,
                           String isin) throws KisException
  {
    Statement st = null;
    int id = 0;
    try 
    {
      st = getDBTransaction().createStatement(1);
      String sql1 = "select db_jt.sq_KP_ktg_FinancniInvestice.nextVal from dual";
      ResultSet rs = st.executeQuery(sql1);
      if(rs.next()) id = rs.getInt(1);
      else return -1;
      
      rs.close();
      
      String sqlString = "insert into db_jt.KP_KTG_FINANCNIINVESTICE (id,id_ktgspolecnost, s_mena, s_uzivatel, s_isin)"+
                         " values ("+id+","+idSpol+",'"+mena+"','"+getUser()+"','"+isin+"')";
      st.execute(sqlString);
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo vkladani do db_jt.KP_KTG_FINANCNIINVESTICE",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { /* ignore */}
    }
    
    return id;
  }
  
  public void deleteFinInv(int id) throws KisException
  {
    Statement st = null;
    try 
    {
      st = getDBTransaction().createStatement(1);
      String sqlString = "delete from db_jt.KP_KTG_FINANCNIINVESTICE where id = "+id;
      st.execute(sqlString);
      getDBTransaction().commit();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo mazani z db_jt.KP_KTG_FINANCNIINVESTICE",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { /* ignore */}
    }
  }

  public void updateFinInv(int idInv,
                           String mena,
                           String isin) throws KisException
  {
    ViewObject vo = (ViewObject) getVwFinancniinvesticeView1();
    vo.clearCache();
    vo.setWhereClause("ID = "+idInv);
    if(vo.hasNext()) 
    {
      Row row = vo.next();
      if("".equals(mena)) mena=null;
      if("".equals(isin)) isin=null;
      if(mena != null && !mena.equals(row.getAttribute("SMena"))) {
        row.setAttribute("SMena",mena);
      }
      if(isin != null && !isin.equals(row.getAttribute("SIsin"))) {
        row.setAttribute("SIsin",isin);
      }
    }
    vo.closeRowSet();
    getDBTransaction().commit();
  }

  public void investiceEmise(String akce,
                             int id,
                             int idInv,
                             java.sql.Date platnostOd,
                             java.sql.Date platnostDo,
                             double pocetKusu,
                             double nominal,
                             double zakladniJmeni,
                             String invfn,
                             String nenulovy) throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    CallableStatement st = null;

    try {
      st = dbTran.createCallableStatement("begin db_jt.kap_gui.p_KpInvesticeEmise (?,?,?,?,?,?,?,?,?,?,?); end;",0);
      st.setString(1, akce);
      st.setInt(2, id);
      st.setInt(3, idInv);
      st.setDate(4, platnostOd);
      st.setDate(5, platnostDo);
      st.setDouble(6, pocetKusu);
      st.setDouble(7, nominal);
      st.setDouble(8, zakladniJmeni);
      st.setString(9, invfn);
      st.setString(10, nenulovy);
      st.setString(11, getUser());
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury db_jt.kap_gui.p_KpInvesticeEmise",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { /* ignore */}
    }

    dbTran.commit();
  }

  public void investiceEmisePlatnost(int id,
                                     java.sql.Date platnostDo) throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    CallableStatement st = null;
    try {
      st = dbTran.createCallableStatement("begin db_jt.kap_gui.p_KpInvesticeEmisePlatnost (?,?,?); end;",0);
      st.setInt(1, id);
      st.setDate(2, platnostDo);
      st.setString(3, getUser());
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury db_jt.kap_gui.p_KpInvesticeEmisePlatnost",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { /* ignore */}
    }
  }

  /**
   * 
   * Container's getter for VwFininvemiseExportView1
   */
  public VwFininvemiseExportViewImpl getVwFininvemiseExportView1()
  {
    return (VwFininvemiseExportViewImpl)findViewObject("VwFininvemiseExportView1");
  }

  public void exportExcelEmise(java.sql.Date datum) throws KisException 
  {
    ESExportFininvEmise ep = new ESExportFininvEmise(this, datum);
    try {
      ep.excelOutput();
    }
    catch (IOException ex) {
      ex.printStackTrace(); //pro zacatek
    }
  }

  private FileFilter ff = new FileFilter() {
      public boolean accept(File pathname) 
      {
        return true;
      }
    };

  private java.text.DateFormat df = java.text.DateFormat.getDateTimeInstance(java.text.DateFormat.MEDIUM, java.text.DateFormat.MEDIUM);

  public String getExcelsEmise() 
  {
    StringBuffer buf = new StringBuffer();
    String dirName = Constants.XLS_FILES_PATH + Constants.DIR_EMISE;
    File dir = new File(dirName);
    File[] arr = dir.listFiles(ff);
    if(arr != null) {
      for( int i=0; i<arr.length; i++ ) 
      {
        String name = arr[i].getName();
        buf.append("<a target=\"_blank\" href=\"excelservlet/"+name+"?file="+Constants.DIR_EMISE+"|5C"+ name + "\">" + name+ "</a>");
        buf.append("&nbsp;" + df.format( new java.util.Date(arr[i].lastModified())) + "<br>"); 
      }
    }
    return buf.toString();
  }
}