package cz.jtbank.konsolidace.report;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwRepUcspolmaxtransakciImpl extends EntityImpl 
{
  protected static final int SPOLECNOST = 0;
  protected static final int POCETTRANSAKCI = 1;
  protected static final int DATUM = 2;
  protected static final int POCETTRANSAKCIPROJEKT = 3;
  protected static final int POCETTRANSAKCIODBOR = 4;
  protected static final int PCTTRANSAKCIPROJEKT = 5;
  protected static final int PCTTRANSAKCIODBOR = 6;
  protected static final int CONLINE = 7;
  protected static final int POCETTRANSAKCIPROJEKTPLUS = 8;
  protected static final int PCTTRANSAKCIPROJEKTPLUS = 9;



  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwRepUcspolmaxtransakciImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.report.VwRepUcspolmaxtransakci");
    }
    return mDefinitionObject;
  }




  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Pocettransakci, using the alias name Pocettransakci
   */
  public Number getPocettransakci()
  {
    return (Number)getAttributeInternal(POCETTRANSAKCI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocettransakci
   */
  public void setPocettransakci(Number value)
  {
    setAttributeInternal(POCETTRANSAKCI, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPOLECNOST:
        return getSpolecnost();
      case POCETTRANSAKCI:
        return getPocettransakci();
      case DATUM:
        return getDatum();
      case POCETTRANSAKCIPROJEKT:
        return getPocettransakciprojekt();
      case POCETTRANSAKCIODBOR:
        return getPocettransakciodbor();
      case PCTTRANSAKCIPROJEKT:
        return getPcttransakciprojekt();
      case PCTTRANSAKCIODBOR:
        return getPcttransakciodbor();
      case CONLINE:
        return getCOnline();
      case POCETTRANSAKCIPROJEKTPLUS:
        return getPocettransakciprojektplus();
      case PCTTRANSAKCIPROJEKTPLUS:
        return getPcttransakciprojektplus();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case POCETTRANSAKCI:
        setPocettransakci((Number)value);
        return;
      case DATUM:
        setDatum((Date)value);
        return;
      case POCETTRANSAKCIPROJEKT:
        setPocettransakciprojekt((Number)value);
        return;
      case POCETTRANSAKCIODBOR:
        setPocettransakciodbor((Number)value);
        return;
      case PCTTRANSAKCIPROJEKT:
        setPcttransakciprojekt((Number)value);
        return;
      case PCTTRANSAKCIODBOR:
        setPcttransakciodbor((Number)value);
        return;
      case CONLINE:
        setCOnline((String)value);
        return;
      case POCETTRANSAKCIPROJEKTPLUS:
        setPocettransakciprojektplus((Number)value);
        return;
      case PCTTRANSAKCIPROJEKTPLUS:
        setPcttransakciprojektplus((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for Datum, using the alias name Datum
   */
  public Date getDatum()
  {
    return (Date)getAttributeInternal(DATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Datum
   */
  public void setDatum(Date value)
  {
    setAttributeInternal(DATUM, value);
  }



  /**
   * 
   * Gets the attribute value for Pocettransakciprojekt, using the alias name Pocettransakciprojekt
   */
  public Number getPocettransakciprojekt()
  {
    return (Number)getAttributeInternal(POCETTRANSAKCIPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocettransakciprojekt
   */
  public void setPocettransakciprojekt(Number value)
  {
    setAttributeInternal(POCETTRANSAKCIPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for Pocettransakciodbor, using the alias name Pocettransakciodbor
   */
  public Number getPocettransakciodbor()
  {
    return (Number)getAttributeInternal(POCETTRANSAKCIODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocettransakciodbor
   */
  public void setPocettransakciodbor(Number value)
  {
    setAttributeInternal(POCETTRANSAKCIODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for Pcttransakciprojekt, using the alias name Pcttransakciprojekt
   */
  public Number getPcttransakciprojekt()
  {
    return (Number)getAttributeInternal(PCTTRANSAKCIPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pcttransakciprojekt
   */
  public void setPcttransakciprojekt(Number value)
  {
    setAttributeInternal(PCTTRANSAKCIPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for Pcttransakciodbor, using the alias name Pcttransakciodbor
   */
  public Number getPcttransakciodbor()
  {
    return (Number)getAttributeInternal(PCTTRANSAKCIODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pcttransakciodbor
   */
  public void setPcttransakciodbor(Number value)
  {
    setAttributeInternal(PCTTRANSAKCIODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for COnline, using the alias name COnline
   */
  public String getCOnline()
  {
    return (String)getAttributeInternal(CONLINE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for COnline
   */
  public void setCOnline(String value)
  {
    setAttributeInternal(CONLINE, value);
  }



  /**
   * 
   * Gets the attribute value for Pocettransakciprojektplus, using the alias name Pocettransakciprojektplus
   */
  public Number getPocettransakciprojektplus()
  {
    return (Number)getAttributeInternal(POCETTRANSAKCIPROJEKTPLUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocettransakciprojektplus
   */
  public void setPocettransakciprojektplus(Number value)
  {
    setAttributeInternal(POCETTRANSAKCIPROJEKTPLUS, value);
  }

  /**
   * 
   * Gets the attribute value for Pcttransakciprojektplus, using the alias name Pcttransakciprojektplus
   */
  public Number getPcttransakciprojektplus()
  {
    return (Number)getAttributeInternal(PCTTRANSAKCIPROJEKTPLUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pcttransakciprojektplus
   */
  public void setPcttransakciprojektplus(Number value)
  {
    setAttributeInternal(PCTTRANSAKCIPROJEKTPLUS, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String spolecnost)
  {
    return new Key(new Object[] {spolecnost});
  }
}