package cz.jtbank.konsolidace.evi;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatEvizplnomocneniImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int DTPLATNOSTOD = 1;
  protected static final int DTPLATNOSTDO = 2;
  protected static final int SPOZNAMKA = 3;
  protected static final int IDADMINSPOLECNOST = 4;
  protected static final int CNAVRH = 5;
  protected static final int KPKTGEVIADMINSPOLECNOST = 6;



  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatEvizplnomocneniImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.evi.KpDatEvizplnomocneni");
    }
    return mDefinitionObject;
  }




  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }

  /**
   * 
   * Gets the attribute value for SPoznamka, using the alias name SPoznamka
   */
  public String getSPoznamka()
  {
    return (String)getAttributeInternal(SPOZNAMKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPoznamka
   */
  public void setSPoznamka(String value)
  {
    setAttributeInternal(SPOZNAMKA, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      case SPOZNAMKA:
        return getSPoznamka();
      case IDADMINSPOLECNOST:
        return getIdAdminspolecnost();
      case CNAVRH:
        return getCNavrh();
      case KPKTGEVIADMINSPOLECNOST:
        return getKpKtgEviadminspolecnost();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      case SPOZNAMKA:
        setSPoznamka((String)value);
        return;
      case IDADMINSPOLECNOST:
        setIdAdminspolecnost((Number)value);
        return;
      case CNAVRH:
        setCNavrh((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   * Gets the attribute value for IdAdminspolecnost, using the alias name IdAdminspolecnost
   */
  public Number getIdAdminspolecnost()
  {
    return (Number)getAttributeInternal(IDADMINSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdminspolecnost
   */
  public void setIdAdminspolecnost(Number value)
  {
    setAttributeInternal(IDADMINSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for CNavrh, using the alias name CNavrh
   */
  public String getCNavrh()
  {
    return (String)getAttributeInternal(CNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CNavrh
   */
  public void setCNavrh(String value)
  {
    setAttributeInternal(CNAVRH, value);
  }

  /**
   * 
   * Gets the associated entity KpKtgEviadminspolecnostImpl
   */
  public KpKtgEviadminspolecnostImpl getKpKtgEviadminspolecnost()
  {
    return (KpKtgEviadminspolecnostImpl)getAttributeInternal(KPKTGEVIADMINSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpKtgEviadminspolecnostImpl
   */
  public void setKpKtgEviadminspolecnost(KpKtgEviadminspolecnostImpl value)
  {
    setAttributeInternal(KPKTGEVIADMINSPOLECNOST, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }



}