package cz.jtbank.konsolidace.evi;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatEviobchodnirejstrikViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatEviobchodnirejstrikViewImpl()
  {
  }
}