package cz.jtbank.konsolidace.evi;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKtgEviadminspolecnostImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SNAZEV = 1;
  protected static final int SSTAT = 2;
  protected static final int IDEXTERNIADMIN = 3;
  protected static final int IDADMINISTRATOR = 4;
  protected static final int IDSTATUS = 5;
  protected static final int IDKTGUCETNISPOLECNOST = 6;
  protected static final int SICO = 7;
  protected static final int DTDATUMZALOZENI = 8;
  protected static final int CNAVRH = 9;
  protected static final int SNAZEVNAVRH = 10;
  protected static final int SICONAVRH = 11;
  protected static final int IDADMINISTRATORNAVRH = 12;
  protected static final int IDTYPSPOL = 13;
  protected static final int SICODOKUMENTY = 14;
  protected static final int KPKTGEVIEXTERNIADMIN = 15;
  protected static final int KPCISEVISTATUS = 16;
  protected static final int KPDATEVIBANKY = 17;
  protected static final int KPDATEVIDOIDENTIFIKACE = 18;
  protected static final int KPDATEVIDOKUMENT = 19;
  protected static final int KPDATEVIKOMISIONARSKESMLOUVY = 20;
  protected static final int KPDATEVIKORESPONDENCE = 21;
  protected static final int KPDATEVIZPLNOMOCNENI = 22;
  protected static final int KPKTGEVISIDLO = 23;
  protected static final int KPKTGEVISTATUTARNIZASTUPCE = 24;
  protected static final int KPDATEVIADMINDODAVATEL = 25;
























  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKtgEviadminspolecnostImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.evi.KpKtgEviadminspolecnost");
    }
    return mDefinitionObject;
  }

























  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }

  /**
   * 
   * Gets the attribute value for SStat, using the alias name SStat
   */
  public String getSStat()
  {
    return (String)getAttributeInternal(SSTAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SStat
   */
  public void setSStat(String value)
  {
    setAttributeInternal(SSTAT, value);
  }

  /**
   * 
   * Gets the attribute value for IdExterniadmin, using the alias name IdExterniadmin
   */
  public Number getIdExterniadmin()
  {
    return (Number)getAttributeInternal(IDEXTERNIADMIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdExterniadmin
   */
  public void setIdExterniadmin(Number value)
  {
    setAttributeInternal(IDEXTERNIADMIN, value);
  }

  /**
   * 
   * Gets the attribute value for IdAdministrator, using the alias name IdAdministrator
   */
  public Number getIdAdministrator()
  {
    return (Number)getAttributeInternal(IDADMINISTRATOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdministrator
   */
  public void setIdAdministrator(Number value)
  {
    setAttributeInternal(IDADMINISTRATOR, value);
  }

  /**
   * 
   * Gets the attribute value for IdStatus, using the alias name IdStatus
   */
  public Number getIdStatus()
  {
    return (Number)getAttributeInternal(IDSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdStatus
   */
  public void setIdStatus(Number value)
  {
    setAttributeInternal(IDSTATUS, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SNAZEV:
        return getSNazev();
      case SSTAT:
        return getSStat();
      case IDEXTERNIADMIN:
        return getIdExterniadmin();
      case IDADMINISTRATOR:
        return getIdAdministrator();
      case IDSTATUS:
        return getIdStatus();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case SICO:
        return getSIco();
      case DTDATUMZALOZENI:
        return getDtDatumzalozeni();
      case CNAVRH:
        return getCNavrh();
      case SNAZEVNAVRH:
        return getSNazevnavrh();
      case SICONAVRH:
        return getSIconavrh();
      case IDADMINISTRATORNAVRH:
        return getIdAdministratornavrh();
      case IDTYPSPOL:
        return getIdTypspol();
      case SICODOKUMENTY:
        return getSIcodokumenty();
      case KPDATEVIBANKY:
        return getKpDatEvibanky();
      case KPDATEVIDOIDENTIFIKACE:
        return getKpDatEvidoidentifikace();
      case KPDATEVIDOKUMENT:
        return getKpDatEvidokument();
      case KPDATEVIKOMISIONARSKESMLOUVY:
        return getKpDatEvikomisionarskesmlouvy();
      case KPDATEVIKORESPONDENCE:
        return getKpDatEvikorespondence();
      case KPDATEVIZPLNOMOCNENI:
        return getKpDatEvizplnomocneni();
      case KPKTGEVISIDLO:
        return getKpKtgEvisidlo();
      case KPKTGEVISTATUTARNIZASTUPCE:
        return getKpKtgEvistatutarnizastupce();
      case KPDATEVIADMINDODAVATEL:
        return getKpDatEviadmindodavatel();
      case KPKTGEVIEXTERNIADMIN:
        return getKpKtgEviexterniadmin();
      case KPCISEVISTATUS:
        return getKpCisEvistatus();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      case SSTAT:
        setSStat((String)value);
        return;
      case IDEXTERNIADMIN:
        setIdExterniadmin((Number)value);
        return;
      case IDADMINISTRATOR:
        setIdAdministrator((Number)value);
        return;
      case IDSTATUS:
        setIdStatus((Number)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case SICO:
        setSIco((String)value);
        return;
      case DTDATUMZALOZENI:
        setDtDatumzalozeni((Date)value);
        return;
      case CNAVRH:
        setCNavrh((String)value);
        return;
      case SNAZEVNAVRH:
        setSNazevnavrh((String)value);
        return;
      case SICONAVRH:
        setSIconavrh((String)value);
        return;
      case IDADMINISTRATORNAVRH:
        setIdAdministratornavrh((Number)value);
        return;
      case IDTYPSPOL:
        setIdTypspol((Number)value);
        return;
      case SICODOKUMENTY:
        setSIcodokumenty((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the associated entity KpKtgEviexterniadminImpl
   */
  public KpKtgEviexterniadminImpl getKpKtgEviexterniadmin()
  {
    return (KpKtgEviexterniadminImpl)getAttributeInternal(KPKTGEVIEXTERNIADMIN);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpKtgEviexterniadminImpl
   */
  public void setKpKtgEviexterniadmin(KpKtgEviexterniadminImpl value)
  {
    setAttributeInternal(KPKTGEVIEXTERNIADMIN, value);
  }

  /**
   * 
   * Gets the associated entity KpCisEvistatusImpl
   */
  public KpCisEvistatusImpl getKpCisEvistatus()
  {
    return (KpCisEvistatusImpl)getAttributeInternal(KPCISEVISTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpCisEvistatusImpl
   */
  public void setKpCisEvistatus(KpCisEvistatusImpl value)
  {
    setAttributeInternal(KPCISEVISTATUS, value);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvibanky()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIBANKY);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvidoidentifikace()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIDOIDENTIFIKACE);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvidokument()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIDOKUMENT);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvikomisionarskesmlouvy()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIKOMISIONARSKESMLOUVY);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvikorespondence()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIKORESPONDENCE);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEvizplnomocneni()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIZPLNOMOCNENI);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpKtgEvisidlo()
  {
    return (RowIterator)getAttributeInternal(KPKTGEVISIDLO);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpKtgEvistatutarnizastupce()
  {
    return (RowIterator)getAttributeInternal(KPKTGEVISTATUTARNIZASTUPCE);
  }


  /**
   * 
   * Gets the attribute value for SIco, using the alias name SIco
   */
  public String getSIco()
  {
    return (String)getAttributeInternal(SICO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIco
   */
  public void setSIco(String value)
  {
    setAttributeInternal(SICO, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzalozeni, using the alias name DtDatumzalozeni
   */
  public Date getDtDatumzalozeni()
  {
    return (Date)getAttributeInternal(DTDATUMZALOZENI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzalozeni
   */
  public void setDtDatumzalozeni(Date value)
  {
    setAttributeInternal(DTDATUMZALOZENI, value);
  }


  /**
   * 
   * Gets the attribute value for CNavrh, using the alias name CNavrh
   */
  public String getCNavrh()
  {
    return (String)getAttributeInternal(CNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CNavrh
   */
  public void setCNavrh(String value)
  {
    setAttributeInternal(CNAVRH, value);
  }


  /**
   * 
   * Gets the attribute value for SNazevnavrh, using the alias name SNazevnavrh
   */
  public String getSNazevnavrh()
  {
    return (String)getAttributeInternal(SNAZEVNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazevnavrh
   */
  public void setSNazevnavrh(String value)
  {
    setAttributeInternal(SNAZEVNAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for SIconavrh, using the alias name SIconavrh
   */
  public String getSIconavrh()
  {
    return (String)getAttributeInternal(SICONAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIconavrh
   */
  public void setSIconavrh(String value)
  {
    setAttributeInternal(SICONAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for IdAdministratornavrh, using the alias name IdAdministratornavrh
   */
  public Number getIdAdministratornavrh()
  {
    return (Number)getAttributeInternal(IDADMINISTRATORNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdministratornavrh
   */
  public void setIdAdministratornavrh(Number value)
  {
    setAttributeInternal(IDADMINISTRATORNAVRH, value);
  }


  /**
   * 
   * Gets the attribute value for IdTypspol, using the alias name IdTypspol
   */
  public Number getIdTypspol()
  {
    return (Number)getAttributeInternal(IDTYPSPOL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTypspol
   */
  public void setIdTypspol(Number value)
  {
    setAttributeInternal(IDTYPSPOL, value);
  }


  /**
   * 
   * Gets the attribute value for SIcodokumenty, using the alias name SIcodokumenty
   */
  public String getSIcodokumenty()
  {
    return (String)getAttributeInternal(SICODOKUMENTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIcodokumenty
   */
  public void setSIcodokumenty(String value)
  {
    setAttributeInternal(SICODOKUMENTY, value);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpDatEviadmindodavatel()
  {
    return (RowIterator)getAttributeInternal(KPDATEVIADMINDODAVATEL);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }















}