package cz.jtbank.konsolidace.evi;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpEviobchodnirejstrik3mImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SPOLECNOST = 1;
  protected static final int STAT = 2;
  protected static final int KOMPLETNI = 3;
  protected static final int K3M = 4;
  protected static final int AKCIONAR = 5;
  protected static final int A3M = 6;
  protected static final int K2M = 7;
  protected static final int A2M = 8;
  protected static final int EXTERNIADMIN = 9;


  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpEviobchodnirejstrik3mImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.evi.VwKpEviobchodnirejstrik3m");
    }
    return mDefinitionObject;
  }



  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Stat, using the alias name Stat
   */
  public String getStat()
  {
    return (String)getAttributeInternal(STAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Stat
   */
  public void setStat(String value)
  {
    setAttributeInternal(STAT, value);
  }

  /**
   * 
   * Gets the attribute value for Kompletni, using the alias name Kompletni
   */
  public Date getKompletni()
  {
    return (Date)getAttributeInternal(KOMPLETNI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Kompletni
   */
  public void setKompletni(Date value)
  {
    setAttributeInternal(KOMPLETNI, value);
  }

  /**
   * 
   * Gets the attribute value for K3m, using the alias name K3m
   */
  public String getK3m()
  {
    return (String)getAttributeInternal(K3M);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for K3m
   */
  public void setK3m(String value)
  {
    setAttributeInternal(K3M, value);
  }

  /**
   * 
   * Gets the attribute value for Akcionar, using the alias name Akcionar
   */
  public Date getAkcionar()
  {
    return (Date)getAttributeInternal(AKCIONAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Akcionar
   */
  public void setAkcionar(Date value)
  {
    setAttributeInternal(AKCIONAR, value);
  }

  /**
   * 
   * Gets the attribute value for A3m, using the alias name A3m
   */
  public String getA3m()
  {
    return (String)getAttributeInternal(A3M);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for A3m
   */
  public void setA3m(String value)
  {
    setAttributeInternal(A3M, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SPOLECNOST:
        return getSpolecnost();
      case STAT:
        return getStat();
      case KOMPLETNI:
        return getKompletni();
      case K3M:
        return getK3m();
      case AKCIONAR:
        return getAkcionar();
      case A3M:
        return getA3m();
      case K2M:
        return getK2m();
      case A2M:
        return getA2m();
      case EXTERNIADMIN:
        return getExterniadmin();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case STAT:
        setStat((String)value);
        return;
      case KOMPLETNI:
        setKompletni((Date)value);
        return;
      case K3M:
        setK3m((String)value);
        return;
      case AKCIONAR:
        setAkcionar((Date)value);
        return;
      case A3M:
        setA3m((String)value);
        return;
      case K2M:
        setK2m((String)value);
        return;
      case A2M:
        setA2m((String)value);
        return;
      case EXTERNIADMIN:
        setExterniadmin((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for K2m, using the alias name K2m
   */
  public String getK2m()
  {
    return (String)getAttributeInternal(K2M);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for K2m
   */
  public void setK2m(String value)
  {
    setAttributeInternal(K2M, value);
  }

  /**
   * 
   * Gets the attribute value for A2m, using the alias name A2m
   */
  public String getA2m()
  {
    return (String)getAttributeInternal(A2M);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for A2m
   */
  public void setA2m(String value)
  {
    setAttributeInternal(A2M, value);
  }



  /**
   * 
   * Gets the attribute value for Externiadmin, using the alias name Externiadmin
   */
  public String getExterniadmin()
  {
    return (String)getAttributeInternal(EXTERNIADMIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Externiadmin
   */
  public void setExterniadmin(String value)
  {
    setAttributeInternal(EXTERNIADMIN, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }
}