package cz.jtbank.konsolidace.budget.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatBudgettransakceImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatBudgettransakceImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPopis_LABEL", "Popis"},
    {"IdKtgprojekt_LABEL", "Projekt"},
    {"NdCastkalocal_LABEL", "Èástka v mìnì úè."},
    {"SUcet_LABEL", "Úèet"},
    {"NdCastkamena_LABEL", "Èástka v mìnì"},
    {"SUnifspol_LABEL", "Protistrana"},
    {"Datum_LABEL", "Datum"},
    {"SMena_LABEL", "Mìna"},
    {"UcspolMena_LABEL", "Mìna úè."},
    {"Spolecnost_LABEL", "Spoleènost"}};




}