package cz.jtbank.konsolidace.protistrany.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwProtistranadetailViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwProtistranadetailViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"DtZmena_LABEL", "Datum změny"},
    {"EkonomSektor_LABEL", "Ek. sektor"},
    {"RowID_DISPLAYHINT", "Hide"},
    {"SDblink_LABEL", "DB Link"},
    {"EoId_LABEL", "Id E.O."},
    {"SNazev_LABEL", "Název"},
    {"BankaId_LABEL", "Id banky"},
    {"Id_TOOLTIP", "ID"},
    {"SIco_TOOLTIP", "S_ICO"},
    {"SIco_LABEL", "IČ"},
    {"FirmaId_LABEL", "Id firmy"},
    {"FirmaId_TOOLTIP", "FIRMA_ID"},
    {"DtZmena_TOOLTIP", "DT_ZMENA"},
    {"Detailprotistrana_TOOLTIP", "DETAILPROTISTRANA"},
    {"EoId_TOOLTIP", "EO_ID"},
    {"Dic_LABEL", "DIČ"},
    {"Regrms_LABEL", "Reg. RMS"},
    {"Typosoby_LABEL", "Typ osoby"},
    {"Datumzalozeni_LABEL", "Datum založení"},
    {"Detailprotistrana_LABEL", "Detail protistrany"},
    {"Ulice_LABEL", "Ulice"},
    {"BankaId_TOOLTIP", "BANKA_ID"},
    {"Stat_LABEL", "Stát"},
    {"SNumber0_DISPLAYHINT", "Hide"},
    {"IdSpolecnost_LABEL", "ID Spol."},
    {"Psc_LABEL", "PSČ"},
    {"SDblink_TOOLTIP", "S_DBLINK"},
    {"Id_LABEL", "Id"},
    {"SNazev_TOOLTIP", "S_NAZEV"},
    {"Kid_TOOLTIP", "KID"},
    {"Doid_TOOLTIP", "DOID"},
    {"Ucetscp_LABEL", "Účet SCP"},
    {"Platinst_TOOLTIP", "PLATINST"},
    {"Mesto_LABEL", "Město"},
    {"IdSpolecnost_TOOLTIP", "ID_SPOLECNOST"}};








}