package cz.jtbank.konsolidace.majetek;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKtgDokladmajucastvyjimkaViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKtgDokladmajucastvyjimkaViewImpl()
  {
  }
}