package cz.jtbank.konsolidace.projekt;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatProjektcashflowImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDKTGPROJEKT = 1;
  protected static final int IDTYP = 2;
  protected static final int DTDATUM = 3;
  protected static final int NDCASTKA = 4;
  protected static final int SMENA = 5;
  protected static final int SINOUT = 6;
  protected static final int IDINOUTTYP = 7;
  protected static final int SPOZNAMKA = 8;
  protected static final int KPCISPROJEKTCASHFLOWTYP = 9;
  protected static final int KPCISPROJEKTINOUTTYP = 10;







  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatProjektcashflowImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.projekt.KpDatProjektcashflow");
    }
    return mDefinitionObject;
  }








  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgprojekt, using the alias name IdKtgprojekt
   */
  public Number getIdKtgprojekt()
  {
    return (Number)getAttributeInternal(IDKTGPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgprojekt
   */
  public void setIdKtgprojekt(Number value)
  {
    setAttributeInternal(IDKTGPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for IdTyp, using the alias name IdTyp
   */
  public Number getIdTyp()
  {
    return (Number)getAttributeInternal(IDTYP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTyp
   */
  public void setIdTyp(Number value)
  {
    setAttributeInternal(IDTYP, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatum, using the alias name DtDatum
   */
  public Date getDtDatum()
  {
    return (Date)getAttributeInternal(DTDATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatum
   */
  public void setDtDatum(Date value)
  {
    setAttributeInternal(DTDATUM, value);
  }




























  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDKTGPROJEKT:
        return getIdKtgprojekt();
      case IDTYP:
        return getIdTyp();
      case DTDATUM:
        return getDtDatum();
      case NDCASTKA:
        return getNdCastka();
      case SMENA:
        return getSMena();
      case SINOUT:
        return getSInout();
      case IDINOUTTYP:
        return getIdInouttyp();
      case SPOZNAMKA:
        return getSPoznamka();
      case KPCISPROJEKTCASHFLOWTYP:
        return getKpCisProjektcashflowtyp();
      case KPCISPROJEKTINOUTTYP:
        return getKpCisProjektinouttyp();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDKTGPROJEKT:
        setIdKtgprojekt((Number)value);
        return;
      case IDTYP:
        setIdTyp((Number)value);
        return;
      case DTDATUM:
        setDtDatum((Date)value);
        return;
      case NDCASTKA:
        setNdCastka((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case SINOUT:
        setSInout((String)value);
        return;
      case IDINOUTTYP:
        setIdInouttyp((Number)value);
        return;
      case SPOZNAMKA:
        setSPoznamka((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   * Gets the associated entity KpCisProjektcashflowtypImpl
   */
  public KpCisProjektcashflowtypImpl getKpCisProjektcashflowtyp()
  {
    return (KpCisProjektcashflowtypImpl)getAttributeInternal(KPCISPROJEKTCASHFLOWTYP);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpCisProjektcashflowtypImpl
   */
  public void setKpCisProjektcashflowtyp(KpCisProjektcashflowtypImpl value)
  {
    setAttributeInternal(KPCISPROJEKTCASHFLOWTYP, value);
  }


  /**
   * 
   * Gets the attribute value for NdCastka, using the alias name NdCastka
   */
  public Number getNdCastka()
  {
    return (Number)getAttributeInternal(NDCASTKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastka
   */
  public void setNdCastka(Number value)
  {
    setAttributeInternal(NDCASTKA, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SInout, using the alias name SInout
   */
  public String getSInout()
  {
    return (String)getAttributeInternal(SINOUT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SInout
   */
  public void setSInout(String value)
  {
    setAttributeInternal(SINOUT, value);
  }

  /**
   * 
   * Gets the attribute value for IdInouttyp, using the alias name IdInouttyp
   */
  public Number getIdInouttyp()
  {
    return (Number)getAttributeInternal(IDINOUTTYP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdInouttyp
   */
  public void setIdInouttyp(Number value)
  {
    setAttributeInternal(IDINOUTTYP, value);
  }

  /**
   * 
   * Gets the attribute value for SPoznamka, using the alias name SPoznamka
   */
  public String getSPoznamka()
  {
    return (String)getAttributeInternal(SPOZNAMKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPoznamka
   */
  public void setSPoznamka(String value)
  {
    setAttributeInternal(SPOZNAMKA, value);
  }


  /**
   * 
   * Gets the associated entity KpCisProjektinouttypImpl
   */
  public KpCisProjektinouttypImpl getKpCisProjektinouttyp()
  {
    return (KpCisProjektinouttypImpl)getAttributeInternal(KPCISPROJEKTINOUTTYP);
  }

  /**
   * 
   * Sets <code>value</code> as the associated entity KpCisProjektinouttypImpl
   */
  public void setKpCisProjektinouttyp(KpCisProjektinouttypImpl value)
  {
    setAttributeInternal(KPCISPROJEKTINOUTTYP, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }







}