package cz.jtbank.konsolidace.protistrany;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpSpolecnostspravcekoImpl extends EntityImpl 
{
  protected static final int IDDATABAZE = 0;
  protected static final int IDSPOLECNOST = 1;
  protected static final int SNUMBER0 = 2;
  protected static final int STAT = 3;
  protected static final int SICO = 4;
  protected static final int SNAZEV = 5;
  protected static final int SSPRAVCE = 6;
  protected static final int SKO = 7;
  protected static final int MNGSEGMENT = 8;
  protected static final int SEGMENTBOSS = 9;
  protected static final int PRODUKT = 10;






  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpSpolecnostspravcekoImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.protistrany.VwKpSpolecnostspravceko");
    }
    return mDefinitionObject;
  }







  /**
   * 
   * Gets the attribute value for IdDatabaze, using the alias name IdDatabaze
   */
  public Number getIdDatabaze()
  {
    return (Number)getAttributeInternal(IDDATABAZE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDatabaze
   */
  public void setIdDatabaze(Number value)
  {
    setAttributeInternal(IDDATABAZE, value);
  }

  /**
   * 
   * Gets the attribute value for IdSpolecnost, using the alias name IdSpolecnost
   */
  public Number getIdSpolecnost()
  {
    return (Number)getAttributeInternal(IDSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdSpolecnost
   */
  public void setIdSpolecnost(Number value)
  {
    setAttributeInternal(IDSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SNumber0, using the alias name SNumber0
   */
  public String getSNumber0()
  {
    return (String)getAttributeInternal(SNUMBER0);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNumber0
   */
  public void setSNumber0(String value)
  {
    setAttributeInternal(SNUMBER0, value);
  }

  /**
   * 
   * Gets the attribute value for Stat, using the alias name Stat
   */
  public String getStat()
  {
    return (String)getAttributeInternal(STAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Stat
   */
  public void setStat(String value)
  {
    setAttributeInternal(STAT, value);
  }

  /**
   * 
   * Gets the attribute value for SIco, using the alias name SIco
   */
  public String getSIco()
  {
    return (String)getAttributeInternal(SICO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIco
   */
  public void setSIco(String value)
  {
    setAttributeInternal(SICO, value);
  }

  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }

  /**
   * 
   * Gets the attribute value for SSpravce, using the alias name SSpravce
   */
  public String getSSpravce()
  {
    return (String)getAttributeInternal(SSPRAVCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SSpravce
   */
  public void setSSpravce(String value)
  {
    setAttributeInternal(SSPRAVCE, value);
  }

  /**
   * 
   * Gets the attribute value for SKo, using the alias name SKo
   */
  public String getSKo()
  {
    return (String)getAttributeInternal(SKO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SKo
   */
  public void setSKo(String value)
  {
    setAttributeInternal(SKO, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDATABAZE:
        return getIdDatabaze();
      case IDSPOLECNOST:
        return getIdSpolecnost();
      case SNUMBER0:
        return getSNumber0();
      case STAT:
        return getStat();
      case SICO:
        return getSIco();
      case SNAZEV:
        return getSNazev();
      case SSPRAVCE:
        return getSSpravce();
      case SKO:
        return getSKo();
      case MNGSEGMENT:
        return getMngsegment();
      case SEGMENTBOSS:
        return getSegmentboss();
      case PRODUKT:
        return getProdukt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDATABAZE:
        setIdDatabaze((Number)value);
        return;
      case IDSPOLECNOST:
        setIdSpolecnost((Number)value);
        return;
      case SNUMBER0:
        setSNumber0((String)value);
        return;
      case STAT:
        setStat((String)value);
        return;
      case SICO:
        setSIco((String)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      case SSPRAVCE:
        setSSpravce((String)value);
        return;
      case SKO:
        setSKo((String)value);
        return;
      case MNGSEGMENT:
        setMngsegment((String)value);
        return;
      case SEGMENTBOSS:
        setSegmentboss((String)value);
        return;
      case PRODUKT:
        setProdukt((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for Mngsegment, using the alias name Mngsegment
   */
  public String getMngsegment()
  {
    return (String)getAttributeInternal(MNGSEGMENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Mngsegment
   */
  public void setMngsegment(String value)
  {
    setAttributeInternal(MNGSEGMENT, value);
  }


  /**
   * 
   * Gets the attribute value for Segmentboss, using the alias name Segmentboss
   */
  public String getSegmentboss()
  {
    return (String)getAttributeInternal(SEGMENTBOSS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Segmentboss
   */
  public void setSegmentboss(String value)
  {
    setAttributeInternal(SEGMENTBOSS, value);
  }


  /**
   * 
   * Gets the attribute value for Produkt, using the alias name Produkt
   */
  public String getProdukt()
  {
    return (String)getAttributeInternal(PRODUKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Produkt
   */
  public void setProdukt(String value)
  {
    setAttributeInternal(PRODUKT, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idDatabaze, Number idSpolecnost, String sNumber0, String sSpravce)
  {
    return new Key(new Object[] {idDatabaze, idSpolecnost, sNumber0, sSpravce});
  }






}