package cz.jtbank.konsolidace.protistrany.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwProtistranaViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwProtistranaViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPsc_LABEL", "PSÈ"},
    {"SDic_LABEL", "DIÈ"},
    {"DtDatumzalozeni_TOOLTIP", "DT_DATUMZALOZENI"},
    {"SNazev_LABEL", "Název"},
    {"Listgroup_TOOLTIP", "LISTGROUP"},
    {"CIndicatorPc_TOOLTIP", "C_INDICATOR_PC"},
    {"Id_TOOLTIP", "ID"},
    {"DtDatumzalozeni_LABEL", "Datum založení"},
    {"SUcetscp_LABEL", "Úèet SCP"},
    {"SCountry_LABEL", "Zemì"},
    {"SIco_TOOLTIP", "S_ICO"},
    {"Kategoriekoef_LABEL", "Rizikovost"},
    {"SIco_LABEL", "IÈ"},
    {"SMesto_TOOLTIP", "S_MESTO"},
    {"SCountry_TOOLTIP", "S_COUNTRY"},
    {"Listgroup_LABEL", "Skupina"},
    {"SRegrms_LABEL", "Reg. RMS"},
    {"Kategoriekoef_TOOLTIP", "KATEGORIEKOEF"},
    {"SEkonomSektor_TOOLTIP", "S_EKONOM_SEKTOR"},
    {"SUcetscp_TOOLTIP", "S_UCETSCP"},
    {"SPsc_TOOLTIP", "S_PSC"},
    {"IdKtgspolecnost_TOOLTIP", "ID_KTGSPOLECNOST"},
    {"SEkonomSektor_LABEL", "Sektor"},
    {"SUlice_TOOLTIP", "S_ULICE"},
    {"SNazev_TOOLTIP", "S_NAZEV"},
    {"Id_LABEL", "Id"},
    {"SDic_TOOLTIP", "S_DIC"},
    {"CIndicatorPc_LABEL", "Pers./Corp."},
    {"IdKtgspolecnost_LABEL", "Úè. spol."},
    {"SUlice_LABEL", "Ulice"},
    {"SRegrms_TOOLTIP", "S_REGRMS"},
    {"SMesto_LABEL", "Mìsto"}};









}