package cz.jtbank.konsolidace.ifrs.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwJtSpolecnostpravifrsdetailImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwJtSpolecnostpravifrsdetailImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPopis_LABEL", "Popis"},
    {"NdCastka_LABEL", "Částka"},
    {"SUcetmd_LABEL", "Účet má dáti"},
    {"SPodminka_LABEL", "Podmínka"},
    {"SZkratka_LABEL", "Typ pravidla"},
    {"NdCastkalocal_LABEL", "Částka lokální"},
    {"SPoznamka_LABEL", "Poznámka"},
    {"SUcetzbytek_LABEL", "Účet zbytek"},
    {"IdPoradi_LABEL", "Id pořadí"},
    {"SUcetd_LABEL", "Účet dal"},
    {"SMena_LABEL", "Měna"}};



}