package cz.jtbank.konsolidace.evi;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpLogEviadminspolecnostImpl extends EntityImpl 
{
  protected static final int SAKCE = 0;
  protected static final int ID = 1;
  protected static final int SNAZEV = 2;
  protected static final int SSTAT = 3;
  protected static final int IDEXTERNIADMIN = 4;
  protected static final int IDADMINISTRATOR = 5;
  protected static final int IDSTATUS = 6;
  protected static final int IDKTGUCETNISPOLECNOST = 7;
  protected static final int SICO = 8;
  protected static final int DTDATUMZALOZENI = 9;
  protected static final int CNAVRH = 10;
  protected static final int SNAZEVNAVRH = 11;
  protected static final int SICONAVRH = 12;
  protected static final int IDADMINISTRATORNAVRH = 13;
  protected static final int IDTYPSPOL = 14;
  protected static final int DTDATUMZMENY = 15;
  protected static final int SUZIVATEL = 16;
  protected static final int SICODOKUMENTY = 17;

  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpLogEviadminspolecnostImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.evi.KpLogEviadminspolecnost");
    }
    return mDefinitionObject;
  }


  /**
   * 
   * Gets the attribute value for SAkce, using the alias name SAkce
   */
  public String getSAkce()
  {
    return (String)getAttributeInternal(SAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SAkce
   */
  public void setSAkce(String value)
  {
    setAttributeInternal(SAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }

  /**
   * 
   * Gets the attribute value for SStat, using the alias name SStat
   */
  public String getSStat()
  {
    return (String)getAttributeInternal(SSTAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SStat
   */
  public void setSStat(String value)
  {
    setAttributeInternal(SSTAT, value);
  }

  /**
   * 
   * Gets the attribute value for IdExterniadmin, using the alias name IdExterniadmin
   */
  public Number getIdExterniadmin()
  {
    return (Number)getAttributeInternal(IDEXTERNIADMIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdExterniadmin
   */
  public void setIdExterniadmin(Number value)
  {
    setAttributeInternal(IDEXTERNIADMIN, value);
  }

  /**
   * 
   * Gets the attribute value for IdAdministrator, using the alias name IdAdministrator
   */
  public Number getIdAdministrator()
  {
    return (Number)getAttributeInternal(IDADMINISTRATOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdministrator
   */
  public void setIdAdministrator(Number value)
  {
    setAttributeInternal(IDADMINISTRATOR, value);
  }

  /**
   * 
   * Gets the attribute value for IdStatus, using the alias name IdStatus
   */
  public Number getIdStatus()
  {
    return (Number)getAttributeInternal(IDSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdStatus
   */
  public void setIdStatus(Number value)
  {
    setAttributeInternal(IDSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SIco, using the alias name SIco
   */
  public String getSIco()
  {
    return (String)getAttributeInternal(SICO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIco
   */
  public void setSIco(String value)
  {
    setAttributeInternal(SICO, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzalozeni, using the alias name DtDatumzalozeni
   */
  public Date getDtDatumzalozeni()
  {
    return (Date)getAttributeInternal(DTDATUMZALOZENI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzalozeni
   */
  public void setDtDatumzalozeni(Date value)
  {
    setAttributeInternal(DTDATUMZALOZENI, value);
  }

  /**
   * 
   * Gets the attribute value for CNavrh, using the alias name CNavrh
   */
  public String getCNavrh()
  {
    return (String)getAttributeInternal(CNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CNavrh
   */
  public void setCNavrh(String value)
  {
    setAttributeInternal(CNAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for SNazevnavrh, using the alias name SNazevnavrh
   */
  public String getSNazevnavrh()
  {
    return (String)getAttributeInternal(SNAZEVNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazevnavrh
   */
  public void setSNazevnavrh(String value)
  {
    setAttributeInternal(SNAZEVNAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for SIconavrh, using the alias name SIconavrh
   */
  public String getSIconavrh()
  {
    return (String)getAttributeInternal(SICONAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIconavrh
   */
  public void setSIconavrh(String value)
  {
    setAttributeInternal(SICONAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for IdAdministratornavrh, using the alias name IdAdministratornavrh
   */
  public Number getIdAdministratornavrh()
  {
    return (Number)getAttributeInternal(IDADMINISTRATORNAVRH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdministratornavrh
   */
  public void setIdAdministratornavrh(Number value)
  {
    setAttributeInternal(IDADMINISTRATORNAVRH, value);
  }

  /**
   * 
   * Gets the attribute value for IdTypspol, using the alias name IdTypspol
   */
  public Number getIdTypspol()
  {
    return (Number)getAttributeInternal(IDTYPSPOL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTypspol
   */
  public void setIdTypspol(Number value)
  {
    setAttributeInternal(IDTYPSPOL, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzmeny, using the alias name DtDatumzmeny
   */
  public Date getDtDatumzmeny()
  {
    return (Date)getAttributeInternal(DTDATUMZMENY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzmeny
   */
  public void setDtDatumzmeny(Date value)
  {
    setAttributeInternal(DTDATUMZMENY, value);
  }

  /**
   * 
   * Gets the attribute value for SUzivatel, using the alias name SUzivatel
   */
  public String getSUzivatel()
  {
    return (String)getAttributeInternal(SUZIVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUzivatel
   */
  public void setSUzivatel(String value)
  {
    setAttributeInternal(SUZIVATEL, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SAKCE:
        return getSAkce();
      case ID:
        return getId();
      case SNAZEV:
        return getSNazev();
      case SSTAT:
        return getSStat();
      case IDEXTERNIADMIN:
        return getIdExterniadmin();
      case IDADMINISTRATOR:
        return getIdAdministrator();
      case IDSTATUS:
        return getIdStatus();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case SICO:
        return getSIco();
      case DTDATUMZALOZENI:
        return getDtDatumzalozeni();
      case CNAVRH:
        return getCNavrh();
      case SNAZEVNAVRH:
        return getSNazevnavrh();
      case SICONAVRH:
        return getSIconavrh();
      case IDADMINISTRATORNAVRH:
        return getIdAdministratornavrh();
      case IDTYPSPOL:
        return getIdTypspol();
      case DTDATUMZMENY:
        return getDtDatumzmeny();
      case SUZIVATEL:
        return getSUzivatel();
      case SICODOKUMENTY:
        return getSIcodokumenty();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SAKCE:
        setSAkce((String)value);
        return;
      case ID:
        setId((Number)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      case SSTAT:
        setSStat((String)value);
        return;
      case IDEXTERNIADMIN:
        setIdExterniadmin((Number)value);
        return;
      case IDADMINISTRATOR:
        setIdAdministrator((Number)value);
        return;
      case IDSTATUS:
        setIdStatus((Number)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case SICO:
        setSIco((String)value);
        return;
      case DTDATUMZALOZENI:
        setDtDatumzalozeni((Date)value);
        return;
      case CNAVRH:
        setCNavrh((String)value);
        return;
      case SNAZEVNAVRH:
        setSNazevnavrh((String)value);
        return;
      case SICONAVRH:
        setSIconavrh((String)value);
        return;
      case IDADMINISTRATORNAVRH:
        setIdAdministratornavrh((Number)value);
        return;
      case IDTYPSPOL:
        setIdTypspol((Number)value);
        return;
      case DTDATUMZMENY:
        setDtDatumzmeny((Date)value);
        return;
      case SUZIVATEL:
        setSUzivatel((String)value);
        return;
      case SICODOKUMENTY:
        setSIcodokumenty((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for SIcodokumenty, using the alias name SIcodokumenty
   */
  public String getSIcodokumenty()
  {
    return (String)getAttributeInternal(SICODOKUMENTY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIcodokumenty
   */
  public void setSIcodokumenty(String value)
  {
    setAttributeInternal(SICODOKUMENTY, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String sAkce, Number id, Date dtDatumzmeny, String sUzivatel)
  {
    return new Key(new Object[] {sAkce, id, dtDatumzmeny, sUzivatel});
  }
}