package cz.jtbank.konsolidace.evi.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpLogEviadminspolecnostViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpLogEviadminspolecnostViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Id4_DISPLAYHINT", "Hide"},
    {"IdKtgucetnispolecnost_LABEL", "Id U.S."},
    {"SNazev_LABEL", "Název"},
    {"AdministratorNavrh_LABEL", "Administrátor - návrh"},
    {"DtDatumzalozeni_LABEL", "Dt. založení"},
    {"SIconavrh_LABEL", "IČ - návrh"},
    {"Status_LABEL", "Status"},
    {"Id2_DISPLAYHINT", "Hide"},
    {"ExtAdmin_LABEL", "Ext. administrátor"},
    {"SIco_LABEL", "IČ"},
    {"SNazevnavrh_LABEL", "Název - návrh"},
    {"SStat_LABEL", "Stát"},
    {"Administrator_LABEL", "Administrátor"},
    {"DtDatumzmeny_LABEL", "Datum změny"},
    {"IdExterniadmin_DISPLAYHINT", "Hide"},
    {"SAkce_LABEL", "Akce"},
    {"IdTypspol_DISPLAYHINT", "Hide"},
    {"CNavrh_LABEL", "Návrh"},
    {"Id1_DISPLAYHINT", "Hide"},
    {"SIcodokumenty_LABEL", "Formát IČ pro dokumenty"},
    {"IdStatus_DISPLAYHINT", "Hide"},
    {"IdAdministratornavrh_DISPLAYHINT", "Hide"},
    {"Id_LABEL", "Id"},
    {"SUzivatel_LABEL", "Uživatel"},
    {"IdAdministrator_DISPLAYHINT", "Hide"},
    {"Id3_DISPLAYHINT", "Hide"}};



}