package cz.jtbank.konsolidace.fininv;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwFinancniinvesticeImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDKTGSPOLECNOST = 1;
  protected static final int SMENA = 2;
  protected static final int DTZMENA = 3;
  protected static final int SUZIVATEL = 4;
  protected static final int SICO = 5;
  protected static final int SNAZEV = 6;
  protected static final int ROWID = 7;
  protected static final int SISIN = 8;



  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwFinancniinvesticeImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.fininv.VwFinancniinvestice");
    }
    return mDefinitionObject;
  }




  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgspolecnost, using the alias name IdKtgspolecnost
   */
  public Number getIdKtgspolecnost()
  {
    return (Number)getAttributeInternal(IDKTGSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgspolecnost
   */
  public void setIdKtgspolecnost(Number value)
  {
    setAttributeInternal(IDKTGSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for DtZmena, using the alias name DtZmena
   */
  public Date getDtZmena()
  {
    return (Date)getAttributeInternal(DTZMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtZmena
   */
  public void setDtZmena(Date value)
  {
    setAttributeInternal(DTZMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SUzivatel, using the alias name SUzivatel
   */
  public String getSUzivatel()
  {
    return (String)getAttributeInternal(SUZIVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUzivatel
   */
  public void setSUzivatel(String value)
  {
    setAttributeInternal(SUZIVATEL, value);
  }

  /**
   * 
   * Gets the attribute value for SIco, using the alias name SIco
   */
  public String getSIco()
  {
    return (String)getAttributeInternal(SICO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIco
   */
  public void setSIco(String value)
  {
    setAttributeInternal(SICO, value);
  }

  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }

  /**
   * 
   * Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDKTGSPOLECNOST:
        return getIdKtgspolecnost();
      case SMENA:
        return getSMena();
      case DTZMENA:
        return getDtZmena();
      case SUZIVATEL:
        return getSUzivatel();
      case SICO:
        return getSIco();
      case SNAZEV:
        return getSNazev();
      case ROWID:
        return getRowID();
      case SISIN:
        return getSIsin();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDKTGSPOLECNOST:
        setIdKtgspolecnost((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case DTZMENA:
        setDtZmena((Date)value);
        return;
      case SUZIVATEL:
        setSUzivatel((String)value);
        return;
      case SICO:
        setSIco((String)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      case SISIN:
        setSIsin((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for SIsin, using the alias name SIsin
   */
  public String getSIsin()
  {
    return (String)getAttributeInternal(SISIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SIsin
   */
  public void setSIsin(String value)
  {
    setAttributeInternal(SISIN, value);
  }
}