package cz.jtbank.konsolidace.fininv;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwFinancniinvemiseViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwFinancniinvemiseViewImpl()
  {
  }
}