package cz.jtbank.konsolidace.users;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KtgAppuserNadrizenaViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KtgAppuserNadrizenaViewImpl()
  {
  }
}