package cz.jtbank.konsolidace.ucskup;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKtgUcspolpredavaniImpl extends EntityImpl 
{
  protected static final int IDKTGUCETNISPOLECNOST = 0;
  protected static final int IDCISPRENOSPRIORITA = 1;
  protected static final int PRENOSPRIORITA = 2;
  protected static final int SACCSTATUS = 3;
  protected static final int SUZAVRENEUCETNICTVI = 4;
  protected static final int DTDATUM = 5;
  protected static final int DTODSOUHLASENOJARKA = 6;
  protected static final int IDODSOUHLASENOJARKA = 7;
  protected static final int DTODSOUHLASENOJANKA = 8;
  protected static final int IDODSOUHLASENOJANKA = 9;
  protected static final int DTODSOUHLASENOTOP = 10;
  protected static final int IDODSOUHLASENOTOP = 11;
  protected static final int ODSOUHLASENOJARKA = 12;
  protected static final int ODSOUHLASENOJANKA = 13;
  protected static final int ODSOUHLASENOTOP = 14;
  protected static final int SPOLECNOST = 15;
  protected static final int IDCISPRENOSKATEGORIE = 16;
  protected static final int PRENOSKATEGORIE = 17;




  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKtgUcspolpredavaniImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.ucskup.VwKtgUcspolpredavani");
    }
    return mDefinitionObject;
  }





  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisprenospriorita, using the alias name IdCisprenospriorita
   */
  public Number getIdCisprenospriorita()
  {
    return (Number)getAttributeInternal(IDCISPRENOSPRIORITA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisprenospriorita
   */
  public void setIdCisprenospriorita(Number value)
  {
    setAttributeInternal(IDCISPRENOSPRIORITA, value);
  }

  /**
   * 
   * Gets the attribute value for Prenospriorita, using the alias name Prenospriorita
   */
  public String getPrenospriorita()
  {
    return (String)getAttributeInternal(PRENOSPRIORITA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Prenospriorita
   */
  public void setPrenospriorita(String value)
  {
    setAttributeInternal(PRENOSPRIORITA, value);
  }

  /**
   * 
   * Gets the attribute value for SAccstatus, using the alias name SAccstatus
   */
  public String getSAccstatus()
  {
    return (String)getAttributeInternal(SACCSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SAccstatus
   */
  public void setSAccstatus(String value)
  {
    setAttributeInternal(SACCSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for SUzavreneucetnictvi, using the alias name SUzavreneucetnictvi
   */
  public String getSUzavreneucetnictvi()
  {
    return (String)getAttributeInternal(SUZAVRENEUCETNICTVI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUzavreneucetnictvi
   */
  public void setSUzavreneucetnictvi(String value)
  {
    setAttributeInternal(SUZAVRENEUCETNICTVI, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatum, using the alias name DtDatum
   */
  public Date getDtDatum()
  {
    return (Date)getAttributeInternal(DTDATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatum
   */
  public void setDtDatum(Date value)
  {
    setAttributeInternal(DTDATUM, value);
  }

  /**
   * 
   * Gets the attribute value for DtOdsouhlasenojarka, using the alias name DtOdsouhlasenojarka
   */
  public Date getDtOdsouhlasenojarka()
  {
    return (Date)getAttributeInternal(DTODSOUHLASENOJARKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtOdsouhlasenojarka
   */
  public void setDtOdsouhlasenojarka(Date value)
  {
    setAttributeInternal(DTODSOUHLASENOJARKA, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdsouhlasenojarka, using the alias name IdOdsouhlasenojarka
   */
  public Number getIdOdsouhlasenojarka()
  {
    return (Number)getAttributeInternal(IDODSOUHLASENOJARKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdsouhlasenojarka
   */
  public void setIdOdsouhlasenojarka(Number value)
  {
    setAttributeInternal(IDODSOUHLASENOJARKA, value);
  }

  /**
   * 
   * Gets the attribute value for DtOdsouhlasenojanka, using the alias name DtOdsouhlasenojanka
   */
  public Date getDtOdsouhlasenojanka()
  {
    return (Date)getAttributeInternal(DTODSOUHLASENOJANKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtOdsouhlasenojanka
   */
  public void setDtOdsouhlasenojanka(Date value)
  {
    setAttributeInternal(DTODSOUHLASENOJANKA, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdsouhlasenojanka, using the alias name IdOdsouhlasenojanka
   */
  public Number getIdOdsouhlasenojanka()
  {
    return (Number)getAttributeInternal(IDODSOUHLASENOJANKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdsouhlasenojanka
   */
  public void setIdOdsouhlasenojanka(Number value)
  {
    setAttributeInternal(IDODSOUHLASENOJANKA, value);
  }

  /**
   * 
   * Gets the attribute value for DtOdsouhlasenotop, using the alias name DtOdsouhlasenotop
   */
  public Date getDtOdsouhlasenotop()
  {
    return (Date)getAttributeInternal(DTODSOUHLASENOTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtOdsouhlasenotop
   */
  public void setDtOdsouhlasenotop(Date value)
  {
    setAttributeInternal(DTODSOUHLASENOTOP, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdsouhlasenotop, using the alias name IdOdsouhlasenotop
   */
  public Number getIdOdsouhlasenotop()
  {
    return (Number)getAttributeInternal(IDODSOUHLASENOTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdsouhlasenotop
   */
  public void setIdOdsouhlasenotop(Number value)
  {
    setAttributeInternal(IDODSOUHLASENOTOP, value);
  }

  /**
   * 
   * Gets the attribute value for Odsouhlasenojarka, using the alias name Odsouhlasenojarka
   */
  public String getOdsouhlasenojarka()
  {
    return (String)getAttributeInternal(ODSOUHLASENOJARKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odsouhlasenojarka
   */
  public void setOdsouhlasenojarka(String value)
  {
    setAttributeInternal(ODSOUHLASENOJARKA, value);
  }

  /**
   * 
   * Gets the attribute value for Odsouhlasenojanka, using the alias name Odsouhlasenojanka
   */
  public String getOdsouhlasenojanka()
  {
    return (String)getAttributeInternal(ODSOUHLASENOJANKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odsouhlasenojanka
   */
  public void setOdsouhlasenojanka(String value)
  {
    setAttributeInternal(ODSOUHLASENOJANKA, value);
  }

  /**
   * 
   * Gets the attribute value for Odsouhlasenotop, using the alias name Odsouhlasenotop
   */
  public String getOdsouhlasenotop()
  {
    return (String)getAttributeInternal(ODSOUHLASENOTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odsouhlasenotop
   */
  public void setOdsouhlasenotop(String value)
  {
    setAttributeInternal(ODSOUHLASENOTOP, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case IDCISPRENOSPRIORITA:
        return getIdCisprenospriorita();
      case PRENOSPRIORITA:
        return getPrenospriorita();
      case SACCSTATUS:
        return getSAccstatus();
      case SUZAVRENEUCETNICTVI:
        return getSUzavreneucetnictvi();
      case DTDATUM:
        return getDtDatum();
      case DTODSOUHLASENOJARKA:
        return getDtOdsouhlasenojarka();
      case IDODSOUHLASENOJARKA:
        return getIdOdsouhlasenojarka();
      case DTODSOUHLASENOJANKA:
        return getDtOdsouhlasenojanka();
      case IDODSOUHLASENOJANKA:
        return getIdOdsouhlasenojanka();
      case DTODSOUHLASENOTOP:
        return getDtOdsouhlasenotop();
      case IDODSOUHLASENOTOP:
        return getIdOdsouhlasenotop();
      case ODSOUHLASENOJARKA:
        return getOdsouhlasenojarka();
      case ODSOUHLASENOJANKA:
        return getOdsouhlasenojanka();
      case ODSOUHLASENOTOP:
        return getOdsouhlasenotop();
      case SPOLECNOST:
        return getSpolecnost();
      case IDCISPRENOSKATEGORIE:
        return getIdCisprenoskategorie();
      case PRENOSKATEGORIE:
        return getPrenoskategorie();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case IDCISPRENOSPRIORITA:
        setIdCisprenospriorita((Number)value);
        return;
      case PRENOSPRIORITA:
        setPrenospriorita((String)value);
        return;
      case SACCSTATUS:
        setSAccstatus((String)value);
        return;
      case SUZAVRENEUCETNICTVI:
        setSUzavreneucetnictvi((String)value);
        return;
      case DTDATUM:
        setDtDatum((Date)value);
        return;
      case DTODSOUHLASENOJARKA:
        setDtOdsouhlasenojarka((Date)value);
        return;
      case IDODSOUHLASENOJARKA:
        setIdOdsouhlasenojarka((Number)value);
        return;
      case DTODSOUHLASENOJANKA:
        setDtOdsouhlasenojanka((Date)value);
        return;
      case IDODSOUHLASENOJANKA:
        setIdOdsouhlasenojanka((Number)value);
        return;
      case DTODSOUHLASENOTOP:
        setDtOdsouhlasenotop((Date)value);
        return;
      case IDODSOUHLASENOTOP:
        setIdOdsouhlasenotop((Number)value);
        return;
      case ODSOUHLASENOJARKA:
        setOdsouhlasenojarka((String)value);
        return;
      case ODSOUHLASENOJANKA:
        setOdsouhlasenojanka((String)value);
        return;
      case ODSOUHLASENOTOP:
        setOdsouhlasenotop((String)value);
        return;
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case IDCISPRENOSKATEGORIE:
        setIdCisprenoskategorie((Number)value);
        return;
      case PRENOSKATEGORIE:
        setPrenoskategorie((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }


  /**
   * 
   * Gets the attribute value for IdCisprenoskategorie, using the alias name IdCisprenoskategorie
   */
  public Number getIdCisprenoskategorie()
  {
    return (Number)getAttributeInternal(IDCISPRENOSKATEGORIE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisprenoskategorie
   */
  public void setIdCisprenoskategorie(Number value)
  {
    setAttributeInternal(IDCISPRENOSKATEGORIE, value);
  }

  /**
   * 
   * Gets the attribute value for Prenoskategorie, using the alias name Prenoskategorie
   */
  public String getPrenoskategorie()
  {
    return (String)getAttributeInternal(PRENOSKATEGORIE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Prenoskategorie
   */
  public void setPrenoskategorie(String value)
  {
    setAttributeInternal(PRENOSKATEGORIE, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idKtgucetnispolecnost)
  {
    return new Key(new Object[] {idKtgucetnispolecnost});
  }



}