package cz.jtbank.konsolidace.admin.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpParametryViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpParametryViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"DtZmena_LABEL", "Zmìna"},
    {"IdKtgucetniskupina3_LABEL", "Úèetní skupina 3"},
    {"RowID_DISPLAYHINT", "Hide"},
    {"IdKtgucetniskupina_LABEL", "Úèetní skupina"},
    {"IdKtgucetniskupina_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"SNgHodiny_LABEL", "Hodina generování"},
    {"IdKtgucetniskupina4_FMT_FORMAT", "####"},
    {"IdKtgucetniskupina4_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"IdKtgucetniskupina3_FMT_FORMAT", "####"},
    {"IdKtgucetniskupina2_LABEL", "Úèetní skupina 2"},
    {"IdKtgucetniskupina6_FMT_FORMAT", "####"},
    {"IdKtgucetniskupina8_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"IdKtgucetniskupina3_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"IdKtgucetniskupina6_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"IdKtgucetniskupina_FMT_FORMAT", "####"},
    {"IdKtgucetniskupina4_LABEL", "Úèetní skupina 4"},
    {"DtNgDatumMustek_LABEL", "Datum mùstku"},
    {"IdKtgucetniskupina7_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"CRestartrunning_LABEL", "Bude restart!"},
    {"NdKapital_LABEL", "Kapitál"},
    {"IdKtgucetniskupina2_FMT_FORMAT", "####"},
    {"IdKtgucetniskupina7_FMT_FORMAT", "####"},
    {"SUzivatel_LABEL", "Uživatel"},
    {"IdKtgucetniskupina2_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"DtNgDatumDo_LABEL", "Datum ke kterému se doklady generují"},
    {"IdKtgucetniskupina8_FMT_FORMAT", "####"},
    {"CNgPovoleno_LABEL", "Povolit generování"}};






























}