package cz.jtbank.konsolidace.subkons;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKtgTypsubpravidloViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKtgTypsubpravidloViewImpl()
  {
  }
}