package cz.jtbank.konsolidace.report;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwRepDocprehledImpl extends EntityImpl 
{
  protected static final int MESIC = 0;
  protected static final int POCET = 1;
  protected static final int RADEK = 2;

  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwRepDocprehledImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.report.VwRepDocprehled");
    }
    return mDefinitionObject;
  }


  /**
   * 
   * Gets the attribute value for Mesic, using the alias name Mesic
   */
  public String getMesic()
  {
    return (String)getAttributeInternal(MESIC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Mesic
   */
  public void setMesic(String value)
  {
    setAttributeInternal(MESIC, value);
  }

  /**
   * 
   * Gets the attribute value for Pocet, using the alias name Pocet
   */
  public Number getPocet()
  {
    return (Number)getAttributeInternal(POCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocet
   */
  public void setPocet(Number value)
  {
    setAttributeInternal(POCET, value);
  }

  /**
   * 
   * Gets the attribute value for Radek, using the alias name Radek
   */
  public Number getRadek()
  {
    return (Number)getAttributeInternal(RADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Radek
   */
  public void setRadek(Number value)
  {
    setAttributeInternal(RADEK, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case MESIC:
        return getMesic();
      case POCET:
        return getPocet();
      case RADEK:
        return getRadek();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case MESIC:
        setMesic((String)value);
        return;
      case POCET:
        setPocet((Number)value);
        return;
      case RADEK:
        setRadek((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String mesic, Number radek)
  {
    return new Key(new Object[] {mesic, radek});
  }


}