package cz.jtbank.konsolidace.report;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwRepUcspolucetnidetailzukImpl extends EntityImpl 
{
  protected static final int ZODPOVEDNAUCETNI = 0;
  protected static final int SPOLECNOST = 1;
  protected static final int HLASKA = 2;
  protected static final int IDDOKLAD = 3;
  protected static final int DATUM = 4;
  protected static final int IDKTGUCETNISPOLECNOST = 5;


  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwRepUcspolucetnidetailzukImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.report.VwRepUcspolucetnidetailzuk");
    }
    return mDefinitionObject;
  }



  /**
   * 
   * Gets the attribute value for Zodpovednaucetni, using the alias name Zodpovednaucetni
   */
  public String getZodpovednaucetni()
  {
    return (String)getAttributeInternal(ZODPOVEDNAUCETNI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zodpovednaucetni
   */
  public void setZodpovednaucetni(String value)
  {
    setAttributeInternal(ZODPOVEDNAUCETNI, value);
  }

  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Hlaska, using the alias name Hlaska
   */
  public String getHlaska()
  {
    return (String)getAttributeInternal(HLASKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Hlaska
   */
  public void setHlaska(String value)
  {
    setAttributeInternal(HLASKA, value);
  }

  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ZODPOVEDNAUCETNI:
        return getZodpovednaucetni();
      case SPOLECNOST:
        return getSpolecnost();
      case HLASKA:
        return getHlaska();
      case IDDOKLAD:
        return getIdDoklad();
      case DATUM:
        return getDatum();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ZODPOVEDNAUCETNI:
        setZodpovednaucetni((String)value);
        return;
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case HLASKA:
        setHlaska((String)value);
        return;
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case DATUM:
        setDatum((Date)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for Datum, using the alias name Datum
   */
  public Date getDatum()
  {
    return (Date)getAttributeInternal(DATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Datum
   */
  public void setDatum(Date value)
  {
    setAttributeInternal(DATUM, value);
  }



  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String zodpovednaucetni, String spolecnost, String hlaska, Number idDoklad)
  {
    return new Key(new Object[] {zodpovednaucetni, spolecnost, hlaska, idDoklad});
  }
}