package cz.jtbank.konsolidace.projekt;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatSlprojektdeveloperViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatSlprojektdeveloperViewImpl()
  {
  }
}