package cz.jtbank.konsolidace.projekt;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKtgUversplatkyImpl extends EntityImpl 
{
  protected static final int DTDATUM = 0;
  protected static final int NDCASTKALNS = 1;
  protected static final int NDCASTKARED = 2;
  protected static final int NDCASTKAINT = 3;
  protected static final int SPOZNAMKA = 4;
  protected static final int IDEXTSYSTEM = 5;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKtgUversplatkyImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.projekt.VwKtgUversplatky");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for DtDatum, using the alias name DtDatum
   */
  public Date getDtDatum()
  {
    return (Date)getAttributeInternal(DTDATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatum
   */
  public void setDtDatum(Date value)
  {
    setAttributeInternal(DTDATUM, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkaLns, using the alias name NdCastkaLns
   */
  public Number getNdCastkaLns()
  {
    return (Number)getAttributeInternal(NDCASTKALNS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkaLns
   */
  public void setNdCastkaLns(Number value)
  {
    setAttributeInternal(NDCASTKALNS, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkaRed, using the alias name NdCastkaRed
   */
  public Number getNdCastkaRed()
  {
    return (Number)getAttributeInternal(NDCASTKARED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkaRed
   */
  public void setNdCastkaRed(Number value)
  {
    setAttributeInternal(NDCASTKARED, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkaInt, using the alias name NdCastkaInt
   */
  public Number getNdCastkaInt()
  {
    return (Number)getAttributeInternal(NDCASTKAINT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkaInt
   */
  public void setNdCastkaInt(Number value)
  {
    setAttributeInternal(NDCASTKAINT, value);
  }

  /**
   * 
   * Gets the attribute value for SPoznamka, using the alias name SPoznamka
   */
  public String getSPoznamka()
  {
    return (String)getAttributeInternal(SPOZNAMKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPoznamka
   */
  public void setSPoznamka(String value)
  {
    setAttributeInternal(SPOZNAMKA, value);
  }

  /**
   * 
   * Gets the attribute value for IdExtsystem, using the alias name IdExtsystem
   */
  public String getIdExtsystem()
  {
    return (String)getAttributeInternal(IDEXTSYSTEM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdExtsystem
   */
  public void setIdExtsystem(String value)
  {
    setAttributeInternal(IDEXTSYSTEM, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DTDATUM:
        return getDtDatum();
      case NDCASTKALNS:
        return getNdCastkaLns();
      case NDCASTKARED:
        return getNdCastkaRed();
      case NDCASTKAINT:
        return getNdCastkaInt();
      case SPOZNAMKA:
        return getSPoznamka();
      case IDEXTSYSTEM:
        return getIdExtsystem();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DTDATUM:
        setDtDatum((Date)value);
        return;
      case NDCASTKALNS:
        setNdCastkaLns((Number)value);
        return;
      case NDCASTKARED:
        setNdCastkaRed((Number)value);
        return;
      case NDCASTKAINT:
        setNdCastkaInt((Number)value);
        return;
      case SPOZNAMKA:
        setSPoznamka((String)value);
        return;
      case IDEXTSYSTEM:
        setIdExtsystem((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Date dtDatum, String idExtsystem)
  {
    return new Key(new Object[] {dtDatum, idExtsystem});
  }
}