package cz.jtbank.konsolidace.projekt.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKtgProjektnavrhImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKtgProjektnavrhImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SPopis_LABEL", "Popis"},
    {"IdPmanager_LABEL", "Projekt manager"},
    {"IdSponzor_LABEL", "Sponzor"},
    {"SNazev_LABEL", "Název"},
    {"Pmanager_LABEL", "Projekt manager"},
    {"DtKonec_LABEL", "Konec real."},
    {"SMenavynos_LABEL", "Měna"},
    {"Id_LABEL", "ID"},
    {"DtZacatek_LABEL", "Začátek real."},
    {"IdNavrhuje_LABEL", "Navrhuje"},
    {"Sponzor_LABEL", "Sponzor"},
    {"NdNaklad_LABEL", "Předpokládaný náklad"},
    {"NdVynos_LABEL", "Předpokládaný výnos"},
    {"SMenanaklad_LABEL", "Měna"},
    {"Navrhuje_LABEL", "Navrhuje"}};


}