package cz.jtbank.konsolidace.ucskup;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwRelSubkonsolidaceclenImpl extends EntityImpl 
{
  protected static final int IDKTGUCETNISKUPINA = 0;
  protected static final int IDKTGUCETNISPOLECNOST = 1;
  protected static final int DTPLATNOSTOD = 2;
  protected static final int DTPLATNOSTDO = 3;




  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwRelSubkonsolidaceclenImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.ucskup.VwRelSubkonsolidaceclen");
    }
    return mDefinitionObject;
  }





  /**
   * 
   * Gets the attribute value for IdKtgucetniskupina, using the alias name IdKtgucetniskupina
   */
  public Number getIdKtgucetniskupina()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISKUPINA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetniskupina
   */
  public void setIdKtgucetniskupina(Number value)
  {
    setAttributeInternal(IDKTGUCETNISKUPINA, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }



  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGUCETNISKUPINA:
        return getIdKtgucetniskupina();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDKTGUCETNISKUPINA:
        setIdKtgucetniskupina((Number)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idKtgucetniskupina, Number idKtgucetnispolecnost, Date dtPlatnostod, Date dtPlatnostdo)
  {
    return new Key(new Object[] {idKtgucetniskupina, idKtgucetnispolecnost, dtPlatnostod, dtPlatnostdo});
  }





}