package cz.jtbank.konsolidace.dokument;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKtgUcetnispolecnostLinkViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKtgUcetnispolecnostLinkViewImpl()
  {
  }
}