package cz.jtbank.konsolidace.dokument;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatSchvalovakAllImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDCISDOKUMENT = 1;
  protected static final int IDKTGUCETNISPOLECNOST = 2;
  protected static final int DTDATUMZADANI = 3;
  protected static final int IDZADAVATEL = 4;
  protected static final int SPOPIS = 5;
  protected static final int IDTYPTRANSAKCE = 6;
  protected static final int CTYPIZOVANATRAN = 7;
  protected static final int DTTYPIZOVANAOD = 8;
  protected static final int DTTYPIZOVANADO = 9;
  protected static final int SMENA = 10;
  protected static final int SPISEMNE = 11;
  protected static final int DTDATUMZAUCTOVANI = 12;
  protected static final int IDSPOLECNOST = 13;
  protected static final int SCISLODOKLADU = 14;
  protected static final int DTDATUMSPLATNOSTI = 15;
  protected static final int IDAPPUSER = 16;
  protected static final int IDZAUCT = 17;
  protected static final int IDCISSTATUS = 18;
  protected static final int CPOKLADNITRANSAKCE = 19;
  protected static final int IDGESTOR = 20;
  protected static final int DTGESTORSCHVALENO = 21;
  protected static final int DTPOZADDATUMUHRADY = 22;
  protected static final int DTREALDATUMUHRADY = 23;
  protected static final int DTGESTORZAMITNUTO = 24;
  protected static final int SGESTORZAMITNUTO = 25;
  protected static final int DTZADAVATELZAMITNUTO = 26;
  protected static final int SZADAVATELZAMITNUTO = 27;
  protected static final int IDTYPIZLINK = 28;
  protected static final int SDUVODZRUSENI = 29;
  protected static final int IDUCSPOLUHRADA = 30;
  protected static final int DTZAUCTUHRADA = 31;
  protected static final int IDZAUCTUHRADA = 32;
  protected static final int SPOLECNOST = 33;
  protected static final int ZADAVATEL = 34;
  protected static final int TYPTRAN = 35;
  protected static final int IDZODPOVEDNAUCETNI = 36;
  protected static final int IDADMINISTRATOR = 37;
  protected static final int PROTISTRANA = 38;
  protected static final int ZAUCTOVATEL = 39;
  protected static final int POCETRADKU = 40;
  protected static final int SUMARADKU = 41;
  protected static final int NDOBJCASTKAVOLNA = 42;
  protected static final int DOCSTATUS = 43;
  protected static final int GESTOR = 44;
  protected static final int EXISTUJENRADEK = 45;
  protected static final int POSPLATNOSTI = 46;
  protected static final int UCSPOLUHRADA = 47;
  protected static final int IDUHRADAUCETNI = 48;
  protected static final int IDUHRADAADMIN = 49;
  protected static final int ZAUCTUHRADA = 50;
  protected static final int IDTYPPRECENENI = 51;
  protected static final int TYPPRECENENI = 52;
  protected static final int SUCET = 53;
  protected static final int SUCET2 = 54;
  protected static final int APPUSER = 55;
  protected static final int CDPH = 56;
  protected static final int IDBUDGET = 57;
  protected static final int IDTTDEVELOPER = 58;
  protected static final int IDCISUHRADA = 59;
  protected static final int UHRADA = 60;
  protected static final int DTUCETNIZAMITNUTO = 61;
  protected static final int SUCETNIZAMITNUTO = 62;
  protected static final int ZODPOVEDNAUCETNI = 63;
  protected static final int CSPECIAL = 64;
  protected static final int IDKTGUCETNISPOLECNOST2 = 65;
  protected static final int SPOLECNOST2 = 66;
  protected static final int SUCETB = 67;
  protected static final int SUCETB2 = 68;
  protected static final int CTISKMAJETEK = 69;
  protected static final int IDKATEGORIE = 70;
  protected static final int CERPATREZERVU = 71;
  protected static final int DTNAVYSENISCHVALENO = 72;
  protected static final int DTNAVYSENIZAMITNUTO = 73;
  protected static final int SNAVYSENIZAMITNUTO = 74;
  protected static final int IDNAVYSENIMB = 75;
  protected static final int MASTERBUDGETER = 76;
  protected static final int DRIDRADKU = 77;
  protected static final int DRIDODBOR = 78;
  protected static final int DRODBOR = 79;
  protected static final int DRIDPROJEKT = 80;
  protected static final int DRPROJEKT = 81;
  protected static final int DRNDCASTKA = 82;
  protected static final int DRIDODBOROO = 83;
  protected static final int DRODBOROO = 84;
  protected static final int DRIDPROJEKTMAN = 85;
  protected static final int DRPROJEKTMAN = 86;
  protected static final int DRIDUCSPOLOO = 87;
  protected static final int DRUCSPOLOO = 88;
  protected static final int DRIDUCSPOLTOP = 89;
  protected static final int DRUCSPOLTOP = 90;
  protected static final int DRDTDATUMZADANI = 91;
  protected static final int DRCZOBJEDNAVKY = 92;
  protected static final int DRIDZAMITNUTO = 93;
  protected static final int DRDTZAMITNUTO = 94;
  protected static final int DRSZAMITNUTO = 95;
  protected static final int DRIDODBOROOREAL = 96;
  protected static final int DRIDPROJEKTMANREAL = 97;
  protected static final int DRIDUCSPOLOOREAL = 98;
  protected static final int DRIDUCSPOLTOPREAL = 99;
  protected static final int DRIDTYPTRANSAKCE = 100;
  protected static final int DRIDPREFAKT = 101;
  protected static final int DRCKPREFAKT = 102;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatSchvalovakAllImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.dokument.VwDatSchvalovakAll");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisdokument, using the alias name IdCisdokument
   */
  public Number getIdCisdokument()
  {
    return (Number)getAttributeInternal(IDCISDOKUMENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisdokument
   */
  public void setIdCisdokument(Number value)
  {
    setAttributeInternal(IDCISDOKUMENT, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzadani, using the alias name DtDatumzadani
   */
  public Date getDtDatumzadani()
  {
    return (Date)getAttributeInternal(DTDATUMZADANI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzadani
   */
  public void setDtDatumzadani(Date value)
  {
    setAttributeInternal(DTDATUMZADANI, value);
  }

  /**
   * 
   * Gets the attribute value for IdZadavatel, using the alias name IdZadavatel
   */
  public Number getIdZadavatel()
  {
    return (Number)getAttributeInternal(IDZADAVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZadavatel
   */
  public void setIdZadavatel(Number value)
  {
    setAttributeInternal(IDZADAVATEL, value);
  }

  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }

  /**
   * 
   * Gets the attribute value for IdTyptransakce, using the alias name IdTyptransakce
   */
  public Number getIdTyptransakce()
  {
    return (Number)getAttributeInternal(IDTYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTyptransakce
   */
  public void setIdTyptransakce(Number value)
  {
    setAttributeInternal(IDTYPTRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for CTypizovanatran, using the alias name CTypizovanatran
   */
  public String getCTypizovanatran()
  {
    return (String)getAttributeInternal(CTYPIZOVANATRAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CTypizovanatran
   */
  public void setCTypizovanatran(String value)
  {
    setAttributeInternal(CTYPIZOVANATRAN, value);
  }

  /**
   * 
   * Gets the attribute value for DtTypizovanaod, using the alias name DtTypizovanaod
   */
  public Date getDtTypizovanaod()
  {
    return (Date)getAttributeInternal(DTTYPIZOVANAOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtTypizovanaod
   */
  public void setDtTypizovanaod(Date value)
  {
    setAttributeInternal(DTTYPIZOVANAOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtTypizovanado, using the alias name DtTypizovanado
   */
  public Date getDtTypizovanado()
  {
    return (Date)getAttributeInternal(DTTYPIZOVANADO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtTypizovanado
   */
  public void setDtTypizovanado(Date value)
  {
    setAttributeInternal(DTTYPIZOVANADO, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SPisemne, using the alias name SPisemne
   */
  public String getSPisemne()
  {
    return (String)getAttributeInternal(SPISEMNE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPisemne
   */
  public void setSPisemne(String value)
  {
    setAttributeInternal(SPISEMNE, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzauctovani, using the alias name DtDatumzauctovani
   */
  public Date getDtDatumzauctovani()
  {
    return (Date)getAttributeInternal(DTDATUMZAUCTOVANI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzauctovani
   */
  public void setDtDatumzauctovani(Date value)
  {
    setAttributeInternal(DTDATUMZAUCTOVANI, value);
  }

  /**
   * 
   * Gets the attribute value for IdSpolecnost, using the alias name IdSpolecnost
   */
  public Number getIdSpolecnost()
  {
    return (Number)getAttributeInternal(IDSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdSpolecnost
   */
  public void setIdSpolecnost(Number value)
  {
    setAttributeInternal(IDSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SCislodokladu, using the alias name SCislodokladu
   */
  public String getSCislodokladu()
  {
    return (String)getAttributeInternal(SCISLODOKLADU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SCislodokladu
   */
  public void setSCislodokladu(String value)
  {
    setAttributeInternal(SCISLODOKLADU, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumsplatnosti, using the alias name DtDatumsplatnosti
   */
  public Date getDtDatumsplatnosti()
  {
    return (Date)getAttributeInternal(DTDATUMSPLATNOSTI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumsplatnosti
   */
  public void setDtDatumsplatnosti(Date value)
  {
    setAttributeInternal(DTDATUMSPLATNOSTI, value);
  }

  /**
   * 
   * Gets the attribute value for IdAppuser, using the alias name IdAppuser
   */
  public Number getIdAppuser()
  {
    return (Number)getAttributeInternal(IDAPPUSER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAppuser
   */
  public void setIdAppuser(Number value)
  {
    setAttributeInternal(IDAPPUSER, value);
  }

  /**
   * 
   * Gets the attribute value for IdZauct, using the alias name IdZauct
   */
  public Number getIdZauct()
  {
    return (Number)getAttributeInternal(IDZAUCT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZauct
   */
  public void setIdZauct(Number value)
  {
    setAttributeInternal(IDZAUCT, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisstatus, using the alias name IdCisstatus
   */
  public Number getIdCisstatus()
  {
    return (Number)getAttributeInternal(IDCISSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisstatus
   */
  public void setIdCisstatus(Number value)
  {
    setAttributeInternal(IDCISSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for CPokladnitransakce, using the alias name CPokladnitransakce
   */
  public String getCPokladnitransakce()
  {
    return (String)getAttributeInternal(CPOKLADNITRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CPokladnitransakce
   */
  public void setCPokladnitransakce(String value)
  {
    setAttributeInternal(CPOKLADNITRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for IdGestor, using the alias name IdGestor
   */
  public Number getIdGestor()
  {
    return (Number)getAttributeInternal(IDGESTOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdGestor
   */
  public void setIdGestor(Number value)
  {
    setAttributeInternal(IDGESTOR, value);
  }

  /**
   * 
   * Gets the attribute value for DtGestorschvaleno, using the alias name DtGestorschvaleno
   */
  public Date getDtGestorschvaleno()
  {
    return (Date)getAttributeInternal(DTGESTORSCHVALENO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtGestorschvaleno
   */
  public void setDtGestorschvaleno(Date value)
  {
    setAttributeInternal(DTGESTORSCHVALENO, value);
  }

  /**
   * 
   * Gets the attribute value for DtPozaddatumuhrady, using the alias name DtPozaddatumuhrady
   */
  public Date getDtPozaddatumuhrady()
  {
    return (Date)getAttributeInternal(DTPOZADDATUMUHRADY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPozaddatumuhrady
   */
  public void setDtPozaddatumuhrady(Date value)
  {
    setAttributeInternal(DTPOZADDATUMUHRADY, value);
  }

  /**
   * 
   * Gets the attribute value for DtRealdatumuhrady, using the alias name DtRealdatumuhrady
   */
  public Date getDtRealdatumuhrady()
  {
    return (Date)getAttributeInternal(DTREALDATUMUHRADY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtRealdatumuhrady
   */
  public void setDtRealdatumuhrady(Date value)
  {
    setAttributeInternal(DTREALDATUMUHRADY, value);
  }

  /**
   * 
   * Gets the attribute value for DtGestorzamitnuto, using the alias name DtGestorzamitnuto
   */
  public Date getDtGestorzamitnuto()
  {
    return (Date)getAttributeInternal(DTGESTORZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtGestorzamitnuto
   */
  public void setDtGestorzamitnuto(Date value)
  {
    setAttributeInternal(DTGESTORZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for SGestorzamitnuto, using the alias name SGestorzamitnuto
   */
  public String getSGestorzamitnuto()
  {
    return (String)getAttributeInternal(SGESTORZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SGestorzamitnuto
   */
  public void setSGestorzamitnuto(String value)
  {
    setAttributeInternal(SGESTORZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for DtZadavatelzamitnuto, using the alias name DtZadavatelzamitnuto
   */
  public Date getDtZadavatelzamitnuto()
  {
    return (Date)getAttributeInternal(DTZADAVATELZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtZadavatelzamitnuto
   */
  public void setDtZadavatelzamitnuto(Date value)
  {
    setAttributeInternal(DTZADAVATELZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for SZadavatelzamitnuto, using the alias name SZadavatelzamitnuto
   */
  public String getSZadavatelzamitnuto()
  {
    return (String)getAttributeInternal(SZADAVATELZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SZadavatelzamitnuto
   */
  public void setSZadavatelzamitnuto(String value)
  {
    setAttributeInternal(SZADAVATELZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for IdTypizlink, using the alias name IdTypizlink
   */
  public Number getIdTypizlink()
  {
    return (Number)getAttributeInternal(IDTYPIZLINK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTypizlink
   */
  public void setIdTypizlink(Number value)
  {
    setAttributeInternal(IDTYPIZLINK, value);
  }

  /**
   * 
   * Gets the attribute value for SDuvodzruseni, using the alias name SDuvodzruseni
   */
  public String getSDuvodzruseni()
  {
    return (String)getAttributeInternal(SDUVODZRUSENI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SDuvodzruseni
   */
  public void setSDuvodzruseni(String value)
  {
    setAttributeInternal(SDUVODZRUSENI, value);
  }

  /**
   * 
   * Gets the attribute value for IdUcspoluhrada, using the alias name IdUcspoluhrada
   */
  public Number getIdUcspoluhrada()
  {
    return (Number)getAttributeInternal(IDUCSPOLUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUcspoluhrada
   */
  public void setIdUcspoluhrada(Number value)
  {
    setAttributeInternal(IDUCSPOLUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for DtZauctuhrada, using the alias name DtZauctuhrada
   */
  public Date getDtZauctuhrada()
  {
    return (Date)getAttributeInternal(DTZAUCTUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtZauctuhrada
   */
  public void setDtZauctuhrada(Date value)
  {
    setAttributeInternal(DTZAUCTUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for IdZauctuhrada, using the alias name IdZauctuhrada
   */
  public Number getIdZauctuhrada()
  {
    return (Number)getAttributeInternal(IDZAUCTUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZauctuhrada
   */
  public void setIdZauctuhrada(Number value)
  {
    setAttributeInternal(IDZAUCTUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Zadavatel, using the alias name Zadavatel
   */
  public String getZadavatel()
  {
    return (String)getAttributeInternal(ZADAVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zadavatel
   */
  public void setZadavatel(String value)
  {
    setAttributeInternal(ZADAVATEL, value);
  }

  /**
   * 
   * Gets the attribute value for Typtran, using the alias name Typtran
   */
  public String getTyptran()
  {
    return (String)getAttributeInternal(TYPTRAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Typtran
   */
  public void setTyptran(String value)
  {
    setAttributeInternal(TYPTRAN, value);
  }

  /**
   * 
   * Gets the attribute value for IdZodpovednaucetni, using the alias name IdZodpovednaucetni
   */
  public Number getIdZodpovednaucetni()
  {
    return (Number)getAttributeInternal(IDZODPOVEDNAUCETNI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZodpovednaucetni
   */
  public void setIdZodpovednaucetni(Number value)
  {
    setAttributeInternal(IDZODPOVEDNAUCETNI, value);
  }

  /**
   * 
   * Gets the attribute value for IdAdministrator, using the alias name IdAdministrator
   */
  public Number getIdAdministrator()
  {
    return (Number)getAttributeInternal(IDADMINISTRATOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdAdministrator
   */
  public void setIdAdministrator(Number value)
  {
    setAttributeInternal(IDADMINISTRATOR, value);
  }

  /**
   * 
   * Gets the attribute value for Protistrana, using the alias name Protistrana
   */
  public String getProtistrana()
  {
    return (String)getAttributeInternal(PROTISTRANA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Protistrana
   */
  public void setProtistrana(String value)
  {
    setAttributeInternal(PROTISTRANA, value);
  }

  /**
   * 
   * Gets the attribute value for Zauctovatel, using the alias name Zauctovatel
   */
  public String getZauctovatel()
  {
    return (String)getAttributeInternal(ZAUCTOVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zauctovatel
   */
  public void setZauctovatel(String value)
  {
    setAttributeInternal(ZAUCTOVATEL, value);
  }

  /**
   * 
   * Gets the attribute value for Pocetradku, using the alias name Pocetradku
   */
  public Number getPocetradku()
  {
    return (Number)getAttributeInternal(POCETRADKU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Pocetradku
   */
  public void setPocetradku(Number value)
  {
    setAttributeInternal(POCETRADKU, value);
  }

  /**
   * 
   * Gets the attribute value for Sumaradku, using the alias name Sumaradku
   */
  public Number getSumaradku()
  {
    return (Number)getAttributeInternal(SUMARADKU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Sumaradku
   */
  public void setSumaradku(Number value)
  {
    setAttributeInternal(SUMARADKU, value);
  }

  /**
   * 
   * Gets the attribute value for NdObjCastkaVolna, using the alias name NdObjCastkaVolna
   */
  public Number getNdObjCastkaVolna()
  {
    return (Number)getAttributeInternal(NDOBJCASTKAVOLNA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdObjCastkaVolna
   */
  public void setNdObjCastkaVolna(Number value)
  {
    setAttributeInternal(NDOBJCASTKAVOLNA, value);
  }

  /**
   * 
   * Gets the attribute value for Docstatus, using the alias name Docstatus
   */
  public String getDocstatus()
  {
    return (String)getAttributeInternal(DOCSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Docstatus
   */
  public void setDocstatus(String value)
  {
    setAttributeInternal(DOCSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for Gestor, using the alias name Gestor
   */
  public String getGestor()
  {
    return (String)getAttributeInternal(GESTOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Gestor
   */
  public void setGestor(String value)
  {
    setAttributeInternal(GESTOR, value);
  }

  /**
   * 
   * Gets the attribute value for ExistujeNradek, using the alias name ExistujeNradek
   */
  public String getExistujeNradek()
  {
    return (String)getAttributeInternal(EXISTUJENRADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for ExistujeNradek
   */
  public void setExistujeNradek(String value)
  {
    setAttributeInternal(EXISTUJENRADEK, value);
  }

  /**
   * 
   * Gets the attribute value for Posplatnosti, using the alias name Posplatnosti
   */
  public String getPosplatnosti()
  {
    return (String)getAttributeInternal(POSPLATNOSTI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Posplatnosti
   */
  public void setPosplatnosti(String value)
  {
    setAttributeInternal(POSPLATNOSTI, value);
  }

  /**
   * 
   * Gets the attribute value for Ucspoluhrada, using the alias name Ucspoluhrada
   */
  public String getUcspoluhrada()
  {
    return (String)getAttributeInternal(UCSPOLUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Ucspoluhrada
   */
  public void setUcspoluhrada(String value)
  {
    setAttributeInternal(UCSPOLUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for IdUhradaucetni, using the alias name IdUhradaucetni
   */
  public Number getIdUhradaucetni()
  {
    return (Number)getAttributeInternal(IDUHRADAUCETNI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUhradaucetni
   */
  public void setIdUhradaucetni(Number value)
  {
    setAttributeInternal(IDUHRADAUCETNI, value);
  }

  /**
   * 
   * Gets the attribute value for IdUhradaadmin, using the alias name IdUhradaadmin
   */
  public Number getIdUhradaadmin()
  {
    return (Number)getAttributeInternal(IDUHRADAADMIN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUhradaadmin
   */
  public void setIdUhradaadmin(Number value)
  {
    setAttributeInternal(IDUHRADAADMIN, value);
  }

  /**
   * 
   * Gets the attribute value for Zauctuhrada, using the alias name Zauctuhrada
   */
  public String getZauctuhrada()
  {
    return (String)getAttributeInternal(ZAUCTUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zauctuhrada
   */
  public void setZauctuhrada(String value)
  {
    setAttributeInternal(ZAUCTUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for IdTyppreceneni, using the alias name IdTyppreceneni
   */
  public Number getIdTyppreceneni()
  {
    return (Number)getAttributeInternal(IDTYPPRECENENI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTyppreceneni
   */
  public void setIdTyppreceneni(Number value)
  {
    setAttributeInternal(IDTYPPRECENENI, value);
  }

  /**
   * 
   * Gets the attribute value for Typpreceneni, using the alias name Typpreceneni
   */
  public String getTyppreceneni()
  {
    return (String)getAttributeInternal(TYPPRECENENI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Typpreceneni
   */
  public void setTyppreceneni(String value)
  {
    setAttributeInternal(TYPPRECENENI, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet2, using the alias name SUcet2
   */
  public String getSUcet2()
  {
    return (String)getAttributeInternal(SUCET2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet2
   */
  public void setSUcet2(String value)
  {
    setAttributeInternal(SUCET2, value);
  }

  /**
   * 
   * Gets the attribute value for Appuser, using the alias name Appuser
   */
  public String getAppuser()
  {
    return (String)getAttributeInternal(APPUSER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Appuser
   */
  public void setAppuser(String value)
  {
    setAttributeInternal(APPUSER, value);
  }

  /**
   * 
   * Gets the attribute value for CDph, using the alias name CDph
   */
  public String getCDph()
  {
    return (String)getAttributeInternal(CDPH);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CDph
   */
  public void setCDph(String value)
  {
    setAttributeInternal(CDPH, value);
  }

  /**
   * 
   * Gets the attribute value for IdBudget, using the alias name IdBudget
   */
  public Number getIdBudget()
  {
    return (Number)getAttributeInternal(IDBUDGET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdBudget
   */
  public void setIdBudget(Number value)
  {
    setAttributeInternal(IDBUDGET, value);
  }

  /**
   * 
   * Gets the attribute value for IdTtdeveloper, using the alias name IdTtdeveloper
   */
  public Number getIdTtdeveloper()
  {
    return (Number)getAttributeInternal(IDTTDEVELOPER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTtdeveloper
   */
  public void setIdTtdeveloper(Number value)
  {
    setAttributeInternal(IDTTDEVELOPER, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisuhrada, using the alias name IdCisuhrada
   */
  public Number getIdCisuhrada()
  {
    return (Number)getAttributeInternal(IDCISUHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisuhrada
   */
  public void setIdCisuhrada(Number value)
  {
    setAttributeInternal(IDCISUHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for Uhrada, using the alias name Uhrada
   */
  public String getUhrada()
  {
    return (String)getAttributeInternal(UHRADA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Uhrada
   */
  public void setUhrada(String value)
  {
    setAttributeInternal(UHRADA, value);
  }

  /**
   * 
   * Gets the attribute value for DtUcetnizamitnuto, using the alias name DtUcetnizamitnuto
   */
  public Date getDtUcetnizamitnuto()
  {
    return (Date)getAttributeInternal(DTUCETNIZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtUcetnizamitnuto
   */
  public void setDtUcetnizamitnuto(Date value)
  {
    setAttributeInternal(DTUCETNIZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for SUcetnizamitnuto, using the alias name SUcetnizamitnuto
   */
  public String getSUcetnizamitnuto()
  {
    return (String)getAttributeInternal(SUCETNIZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetnizamitnuto
   */
  public void setSUcetnizamitnuto(String value)
  {
    setAttributeInternal(SUCETNIZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for Zodpovednaucetni, using the alias name Zodpovednaucetni
   */
  public String getZodpovednaucetni()
  {
    return (String)getAttributeInternal(ZODPOVEDNAUCETNI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zodpovednaucetni
   */
  public void setZodpovednaucetni(String value)
  {
    setAttributeInternal(ZODPOVEDNAUCETNI, value);
  }

  /**
   * 
   * Gets the attribute value for CSpecial, using the alias name CSpecial
   */
  public String getCSpecial()
  {
    return (String)getAttributeInternal(CSPECIAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CSpecial
   */
  public void setCSpecial(String value)
  {
    setAttributeInternal(CSPECIAL, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost2, using the alias name IdKtgucetnispolecnost2
   */
  public Number getIdKtgucetnispolecnost2()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost2
   */
  public void setIdKtgucetnispolecnost2(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST2, value);
  }

  /**
   * 
   * Gets the attribute value for Spolecnost2, using the alias name Spolecnost2
   */
  public String getSpolecnost2()
  {
    return (String)getAttributeInternal(SPOLECNOST2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost2
   */
  public void setSpolecnost2(String value)
  {
    setAttributeInternal(SPOLECNOST2, value);
  }

  /**
   * 
   * Gets the attribute value for SUcetb, using the alias name SUcetb
   */
  public String getSUcetb()
  {
    return (String)getAttributeInternal(SUCETB);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetb
   */
  public void setSUcetb(String value)
  {
    setAttributeInternal(SUCETB, value);
  }

  /**
   * 
   * Gets the attribute value for SUcetb2, using the alias name SUcetb2
   */
  public String getSUcetb2()
  {
    return (String)getAttributeInternal(SUCETB2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetb2
   */
  public void setSUcetb2(String value)
  {
    setAttributeInternal(SUCETB2, value);
  }

  /**
   * 
   * Gets the attribute value for CTiskmajetek, using the alias name CTiskmajetek
   */
  public String getCTiskmajetek()
  {
    return (String)getAttributeInternal(CTISKMAJETEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CTiskmajetek
   */
  public void setCTiskmajetek(String value)
  {
    setAttributeInternal(CTISKMAJETEK, value);
  }

  /**
   * 
   * Gets the attribute value for IdKategorie, using the alias name IdKategorie
   */
  public Number getIdKategorie()
  {
    return (Number)getAttributeInternal(IDKATEGORIE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKategorie
   */
  public void setIdKategorie(Number value)
  {
    setAttributeInternal(IDKATEGORIE, value);
  }

  /**
   * 
   * Gets the attribute value for CerpatRezervu, using the alias name CerpatRezervu
   */
  public String getCerpatRezervu()
  {
    return (String)getAttributeInternal(CERPATREZERVU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CerpatRezervu
   */
  public void setCerpatRezervu(String value)
  {
    setAttributeInternal(CERPATREZERVU, value);
  }

  /**
   * 
   * Gets the attribute value for DtNavyseniSchvaleno, using the alias name DtNavyseniSchvaleno
   */
  public Date getDtNavyseniSchvaleno()
  {
    return (Date)getAttributeInternal(DTNAVYSENISCHVALENO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtNavyseniSchvaleno
   */
  public void setDtNavyseniSchvaleno(Date value)
  {
    setAttributeInternal(DTNAVYSENISCHVALENO, value);
  }

  /**
   * 
   * Gets the attribute value for DtNavyseniZamitnuto, using the alias name DtNavyseniZamitnuto
   */
  public Date getDtNavyseniZamitnuto()
  {
    return (Date)getAttributeInternal(DTNAVYSENIZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtNavyseniZamitnuto
   */
  public void setDtNavyseniZamitnuto(Date value)
  {
    setAttributeInternal(DTNAVYSENIZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for SNavyseniZamitnuto, using the alias name SNavyseniZamitnuto
   */
  public String getSNavyseniZamitnuto()
  {
    return (String)getAttributeInternal(SNAVYSENIZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNavyseniZamitnuto
   */
  public void setSNavyseniZamitnuto(String value)
  {
    setAttributeInternal(SNAVYSENIZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for IdNavyseniMb, using the alias name IdNavyseniMb
   */
  public Number getIdNavyseniMb()
  {
    return (Number)getAttributeInternal(IDNAVYSENIMB);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdNavyseniMb
   */
  public void setIdNavyseniMb(Number value)
  {
    setAttributeInternal(IDNAVYSENIMB, value);
  }

  /**
   * 
   * Gets the attribute value for MasterBudgeter, using the alias name MasterBudgeter
   */
  public String getMasterBudgeter()
  {
    return (String)getAttributeInternal(MASTERBUDGETER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for MasterBudgeter
   */
  public void setMasterBudgeter(String value)
  {
    setAttributeInternal(MASTERBUDGETER, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdRadku, using the alias name DrIdRadku
   */
  public Number getDrIdRadku()
  {
    return (Number)getAttributeInternal(DRIDRADKU);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdRadku
   */
  public void setDrIdRadku(Number value)
  {
    setAttributeInternal(DRIDRADKU, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdOdbor, using the alias name DrIdOdbor
   */
  public Number getDrIdOdbor()
  {
    return (Number)getAttributeInternal(DRIDODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdOdbor
   */
  public void setDrIdOdbor(Number value)
  {
    setAttributeInternal(DRIDODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for DrOdbor, using the alias name DrOdbor
   */
  public String getDrOdbor()
  {
    return (String)getAttributeInternal(DRODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrOdbor
   */
  public void setDrOdbor(String value)
  {
    setAttributeInternal(DRODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdProjekt, using the alias name DrIdProjekt
   */
  public Number getDrIdProjekt()
  {
    return (Number)getAttributeInternal(DRIDPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdProjekt
   */
  public void setDrIdProjekt(Number value)
  {
    setAttributeInternal(DRIDPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for DrProjekt, using the alias name DrProjekt
   */
  public String getDrProjekt()
  {
    return (String)getAttributeInternal(DRPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrProjekt
   */
  public void setDrProjekt(String value)
  {
    setAttributeInternal(DRPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for DrNdCastka, using the alias name DrNdCastka
   */
  public Number getDrNdCastka()
  {
    return (Number)getAttributeInternal(DRNDCASTKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrNdCastka
   */
  public void setDrNdCastka(Number value)
  {
    setAttributeInternal(DRNDCASTKA, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdOdboroo, using the alias name DrIdOdboroo
   */
  public Number getDrIdOdboroo()
  {
    return (Number)getAttributeInternal(DRIDODBOROO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdOdboroo
   */
  public void setDrIdOdboroo(Number value)
  {
    setAttributeInternal(DRIDODBOROO, value);
  }

  /**
   * 
   * Gets the attribute value for DrOdboroo, using the alias name DrOdboroo
   */
  public String getDrOdboroo()
  {
    return (String)getAttributeInternal(DRODBOROO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrOdboroo
   */
  public void setDrOdboroo(String value)
  {
    setAttributeInternal(DRODBOROO, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdProjektman, using the alias name DrIdProjektman
   */
  public Number getDrIdProjektman()
  {
    return (Number)getAttributeInternal(DRIDPROJEKTMAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdProjektman
   */
  public void setDrIdProjektman(Number value)
  {
    setAttributeInternal(DRIDPROJEKTMAN, value);
  }

  /**
   * 
   * Gets the attribute value for DrProjektman, using the alias name DrProjektman
   */
  public String getDrProjektman()
  {
    return (String)getAttributeInternal(DRPROJEKTMAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrProjektman
   */
  public void setDrProjektman(String value)
  {
    setAttributeInternal(DRPROJEKTMAN, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdUcspoloo, using the alias name DrIdUcspoloo
   */
  public Number getDrIdUcspoloo()
  {
    return (Number)getAttributeInternal(DRIDUCSPOLOO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdUcspoloo
   */
  public void setDrIdUcspoloo(Number value)
  {
    setAttributeInternal(DRIDUCSPOLOO, value);
  }

  /**
   * 
   * Gets the attribute value for DrUcspoloo, using the alias name DrUcspoloo
   */
  public String getDrUcspoloo()
  {
    return (String)getAttributeInternal(DRUCSPOLOO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrUcspoloo
   */
  public void setDrUcspoloo(String value)
  {
    setAttributeInternal(DRUCSPOLOO, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdUcspoltop, using the alias name DrIdUcspoltop
   */
  public Number getDrIdUcspoltop()
  {
    return (Number)getAttributeInternal(DRIDUCSPOLTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdUcspoltop
   */
  public void setDrIdUcspoltop(Number value)
  {
    setAttributeInternal(DRIDUCSPOLTOP, value);
  }

  /**
   * 
   * Gets the attribute value for DrUcspoltop, using the alias name DrUcspoltop
   */
  public String getDrUcspoltop()
  {
    return (String)getAttributeInternal(DRUCSPOLTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrUcspoltop
   */
  public void setDrUcspoltop(String value)
  {
    setAttributeInternal(DRUCSPOLTOP, value);
  }

  /**
   * 
   * Gets the attribute value for DrDtDatumzadani, using the alias name DrDtDatumzadani
   */
  public Date getDrDtDatumzadani()
  {
    return (Date)getAttributeInternal(DRDTDATUMZADANI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrDtDatumzadani
   */
  public void setDrDtDatumzadani(Date value)
  {
    setAttributeInternal(DRDTDATUMZADANI, value);
  }

  /**
   * 
   * Gets the attribute value for DrCZobjednavky, using the alias name DrCZobjednavky
   */
  public String getDrCZobjednavky()
  {
    return (String)getAttributeInternal(DRCZOBJEDNAVKY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrCZobjednavky
   */
  public void setDrCZobjednavky(String value)
  {
    setAttributeInternal(DRCZOBJEDNAVKY, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdZamitnuto, using the alias name DrIdZamitnuto
   */
  public Number getDrIdZamitnuto()
  {
    return (Number)getAttributeInternal(DRIDZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdZamitnuto
   */
  public void setDrIdZamitnuto(Number value)
  {
    setAttributeInternal(DRIDZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for DrDtZamitnuto, using the alias name DrDtZamitnuto
   */
  public Date getDrDtZamitnuto()
  {
    return (Date)getAttributeInternal(DRDTZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrDtZamitnuto
   */
  public void setDrDtZamitnuto(Date value)
  {
    setAttributeInternal(DRDTZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for DrSZamitnuto, using the alias name DrSZamitnuto
   */
  public String getDrSZamitnuto()
  {
    return (String)getAttributeInternal(DRSZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrSZamitnuto
   */
  public void setDrSZamitnuto(String value)
  {
    setAttributeInternal(DRSZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdOdborooreal, using the alias name DrIdOdborooreal
   */
  public Number getDrIdOdborooreal()
  {
    return (Number)getAttributeInternal(DRIDODBOROOREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdOdborooreal
   */
  public void setDrIdOdborooreal(Number value)
  {
    setAttributeInternal(DRIDODBOROOREAL, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdProjektmanreal, using the alias name DrIdProjektmanreal
   */
  public Number getDrIdProjektmanreal()
  {
    return (Number)getAttributeInternal(DRIDPROJEKTMANREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdProjektmanreal
   */
  public void setDrIdProjektmanreal(Number value)
  {
    setAttributeInternal(DRIDPROJEKTMANREAL, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdUcspolooreal, using the alias name DrIdUcspolooreal
   */
  public Number getDrIdUcspolooreal()
  {
    return (Number)getAttributeInternal(DRIDUCSPOLOOREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdUcspolooreal
   */
  public void setDrIdUcspolooreal(Number value)
  {
    setAttributeInternal(DRIDUCSPOLOOREAL, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdUcspoltopreal, using the alias name DrIdUcspoltopreal
   */
  public Number getDrIdUcspoltopreal()
  {
    return (Number)getAttributeInternal(DRIDUCSPOLTOPREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdUcspoltopreal
   */
  public void setDrIdUcspoltopreal(Number value)
  {
    setAttributeInternal(DRIDUCSPOLTOPREAL, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdTyptransakce, using the alias name DrIdTyptransakce
   */
  public Number getDrIdTyptransakce()
  {
    return (Number)getAttributeInternal(DRIDTYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdTyptransakce
   */
  public void setDrIdTyptransakce(Number value)
  {
    setAttributeInternal(DRIDTYPTRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for DrIdPrefakt, using the alias name DrIdPrefakt
   */
  public Number getDrIdPrefakt()
  {
    return (Number)getAttributeInternal(DRIDPREFAKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrIdPrefakt
   */
  public void setDrIdPrefakt(Number value)
  {
    setAttributeInternal(DRIDPREFAKT, value);
  }

  /**
   * 
   * Gets the attribute value for DrCKprefakt, using the alias name DrCKprefakt
   */
  public String getDrCKprefakt()
  {
    return (String)getAttributeInternal(DRCKPREFAKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DrCKprefakt
   */
  public void setDrCKprefakt(String value)
  {
    setAttributeInternal(DRCKPREFAKT, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDCISDOKUMENT:
        return getIdCisdokument();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case DTDATUMZADANI:
        return getDtDatumzadani();
      case IDZADAVATEL:
        return getIdZadavatel();
      case SPOPIS:
        return getSPopis();
      case IDTYPTRANSAKCE:
        return getIdTyptransakce();
      case CTYPIZOVANATRAN:
        return getCTypizovanatran();
      case DTTYPIZOVANAOD:
        return getDtTypizovanaod();
      case DTTYPIZOVANADO:
        return getDtTypizovanado();
      case SMENA:
        return getSMena();
      case SPISEMNE:
        return getSPisemne();
      case DTDATUMZAUCTOVANI:
        return getDtDatumzauctovani();
      case IDSPOLECNOST:
        return getIdSpolecnost();
      case SCISLODOKLADU:
        return getSCislodokladu();
      case DTDATUMSPLATNOSTI:
        return getDtDatumsplatnosti();
      case IDAPPUSER:
        return getIdAppuser();
      case IDZAUCT:
        return getIdZauct();
      case IDCISSTATUS:
        return getIdCisstatus();
      case CPOKLADNITRANSAKCE:
        return getCPokladnitransakce();
      case IDGESTOR:
        return getIdGestor();
      case DTGESTORSCHVALENO:
        return getDtGestorschvaleno();
      case DTPOZADDATUMUHRADY:
        return getDtPozaddatumuhrady();
      case DTREALDATUMUHRADY:
        return getDtRealdatumuhrady();
      case DTGESTORZAMITNUTO:
        return getDtGestorzamitnuto();
      case SGESTORZAMITNUTO:
        return getSGestorzamitnuto();
      case DTZADAVATELZAMITNUTO:
        return getDtZadavatelzamitnuto();
      case SZADAVATELZAMITNUTO:
        return getSZadavatelzamitnuto();
      case IDTYPIZLINK:
        return getIdTypizlink();
      case SDUVODZRUSENI:
        return getSDuvodzruseni();
      case IDUCSPOLUHRADA:
        return getIdUcspoluhrada();
      case DTZAUCTUHRADA:
        return getDtZauctuhrada();
      case IDZAUCTUHRADA:
        return getIdZauctuhrada();
      case SPOLECNOST:
        return getSpolecnost();
      case ZADAVATEL:
        return getZadavatel();
      case TYPTRAN:
        return getTyptran();
      case IDZODPOVEDNAUCETNI:
        return getIdZodpovednaucetni();
      case IDADMINISTRATOR:
        return getIdAdministrator();
      case PROTISTRANA:
        return getProtistrana();
      case ZAUCTOVATEL:
        return getZauctovatel();
      case POCETRADKU:
        return getPocetradku();
      case SUMARADKU:
        return getSumaradku();
      case NDOBJCASTKAVOLNA:
        return getNdObjCastkaVolna();
      case DOCSTATUS:
        return getDocstatus();
      case GESTOR:
        return getGestor();
      case EXISTUJENRADEK:
        return getExistujeNradek();
      case POSPLATNOSTI:
        return getPosplatnosti();
      case UCSPOLUHRADA:
        return getUcspoluhrada();
      case IDUHRADAUCETNI:
        return getIdUhradaucetni();
      case IDUHRADAADMIN:
        return getIdUhradaadmin();
      case ZAUCTUHRADA:
        return getZauctuhrada();
      case IDTYPPRECENENI:
        return getIdTyppreceneni();
      case TYPPRECENENI:
        return getTyppreceneni();
      case SUCET:
        return getSUcet();
      case SUCET2:
        return getSUcet2();
      case APPUSER:
        return getAppuser();
      case CDPH:
        return getCDph();
      case IDBUDGET:
        return getIdBudget();
      case IDTTDEVELOPER:
        return getIdTtdeveloper();
      case IDCISUHRADA:
        return getIdCisuhrada();
      case UHRADA:
        return getUhrada();
      case DTUCETNIZAMITNUTO:
        return getDtUcetnizamitnuto();
      case SUCETNIZAMITNUTO:
        return getSUcetnizamitnuto();
      case ZODPOVEDNAUCETNI:
        return getZodpovednaucetni();
      case CSPECIAL:
        return getCSpecial();
      case IDKTGUCETNISPOLECNOST2:
        return getIdKtgucetnispolecnost2();
      case SPOLECNOST2:
        return getSpolecnost2();
      case SUCETB:
        return getSUcetb();
      case SUCETB2:
        return getSUcetb2();
      case CTISKMAJETEK:
        return getCTiskmajetek();
      case IDKATEGORIE:
        return getIdKategorie();
      case CERPATREZERVU:
        return getCerpatRezervu();
      case DTNAVYSENISCHVALENO:
        return getDtNavyseniSchvaleno();
      case DTNAVYSENIZAMITNUTO:
        return getDtNavyseniZamitnuto();
      case SNAVYSENIZAMITNUTO:
        return getSNavyseniZamitnuto();
      case IDNAVYSENIMB:
        return getIdNavyseniMb();
      case MASTERBUDGETER:
        return getMasterBudgeter();
      case DRIDRADKU:
        return getDrIdRadku();
      case DRIDODBOR:
        return getDrIdOdbor();
      case DRODBOR:
        return getDrOdbor();
      case DRIDPROJEKT:
        return getDrIdProjekt();
      case DRPROJEKT:
        return getDrProjekt();
      case DRNDCASTKA:
        return getDrNdCastka();
      case DRIDODBOROO:
        return getDrIdOdboroo();
      case DRODBOROO:
        return getDrOdboroo();
      case DRIDPROJEKTMAN:
        return getDrIdProjektman();
      case DRPROJEKTMAN:
        return getDrProjektman();
      case DRIDUCSPOLOO:
        return getDrIdUcspoloo();
      case DRUCSPOLOO:
        return getDrUcspoloo();
      case DRIDUCSPOLTOP:
        return getDrIdUcspoltop();
      case DRUCSPOLTOP:
        return getDrUcspoltop();
      case DRDTDATUMZADANI:
        return getDrDtDatumzadani();
      case DRCZOBJEDNAVKY:
        return getDrCZobjednavky();
      case DRIDZAMITNUTO:
        return getDrIdZamitnuto();
      case DRDTZAMITNUTO:
        return getDrDtZamitnuto();
      case DRSZAMITNUTO:
        return getDrSZamitnuto();
      case DRIDODBOROOREAL:
        return getDrIdOdborooreal();
      case DRIDPROJEKTMANREAL:
        return getDrIdProjektmanreal();
      case DRIDUCSPOLOOREAL:
        return getDrIdUcspolooreal();
      case DRIDUCSPOLTOPREAL:
        return getDrIdUcspoltopreal();
      case DRIDTYPTRANSAKCE:
        return getDrIdTyptransakce();
      case DRIDPREFAKT:
        return getDrIdPrefakt();
      case DRCKPREFAKT:
        return getDrCKprefakt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDCISDOKUMENT:
        setIdCisdokument((Number)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case DTDATUMZADANI:
        setDtDatumzadani((Date)value);
        return;
      case IDZADAVATEL:
        setIdZadavatel((Number)value);
        return;
      case SPOPIS:
        setSPopis((String)value);
        return;
      case IDTYPTRANSAKCE:
        setIdTyptransakce((Number)value);
        return;
      case CTYPIZOVANATRAN:
        setCTypizovanatran((String)value);
        return;
      case DTTYPIZOVANAOD:
        setDtTypizovanaod((Date)value);
        return;
      case DTTYPIZOVANADO:
        setDtTypizovanado((Date)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case SPISEMNE:
        setSPisemne((String)value);
        return;
      case DTDATUMZAUCTOVANI:
        setDtDatumzauctovani((Date)value);
        return;
      case IDSPOLECNOST:
        setIdSpolecnost((Number)value);
        return;
      case SCISLODOKLADU:
        setSCislodokladu((String)value);
        return;
      case DTDATUMSPLATNOSTI:
        setDtDatumsplatnosti((Date)value);
        return;
      case IDAPPUSER:
        setIdAppuser((Number)value);
        return;
      case IDZAUCT:
        setIdZauct((Number)value);
        return;
      case IDCISSTATUS:
        setIdCisstatus((Number)value);
        return;
      case CPOKLADNITRANSAKCE:
        setCPokladnitransakce((String)value);
        return;
      case IDGESTOR:
        setIdGestor((Number)value);
        return;
      case DTGESTORSCHVALENO:
        setDtGestorschvaleno((Date)value);
        return;
      case DTPOZADDATUMUHRADY:
        setDtPozaddatumuhrady((Date)value);
        return;
      case DTREALDATUMUHRADY:
        setDtRealdatumuhrady((Date)value);
        return;
      case DTGESTORZAMITNUTO:
        setDtGestorzamitnuto((Date)value);
        return;
      case SGESTORZAMITNUTO:
        setSGestorzamitnuto((String)value);
        return;
      case DTZADAVATELZAMITNUTO:
        setDtZadavatelzamitnuto((Date)value);
        return;
      case SZADAVATELZAMITNUTO:
        setSZadavatelzamitnuto((String)value);
        return;
      case IDTYPIZLINK:
        setIdTypizlink((Number)value);
        return;
      case SDUVODZRUSENI:
        setSDuvodzruseni((String)value);
        return;
      case IDUCSPOLUHRADA:
        setIdUcspoluhrada((Number)value);
        return;
      case DTZAUCTUHRADA:
        setDtZauctuhrada((Date)value);
        return;
      case IDZAUCTUHRADA:
        setIdZauctuhrada((Number)value);
        return;
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case ZADAVATEL:
        setZadavatel((String)value);
        return;
      case TYPTRAN:
        setTyptran((String)value);
        return;
      case IDZODPOVEDNAUCETNI:
        setIdZodpovednaucetni((Number)value);
        return;
      case IDADMINISTRATOR:
        setIdAdministrator((Number)value);
        return;
      case PROTISTRANA:
        setProtistrana((String)value);
        return;
      case ZAUCTOVATEL:
        setZauctovatel((String)value);
        return;
      case POCETRADKU:
        setPocetradku((Number)value);
        return;
      case SUMARADKU:
        setSumaradku((Number)value);
        return;
      case NDOBJCASTKAVOLNA:
        setNdObjCastkaVolna((Number)value);
        return;
      case DOCSTATUS:
        setDocstatus((String)value);
        return;
      case GESTOR:
        setGestor((String)value);
        return;
      case EXISTUJENRADEK:
        setExistujeNradek((String)value);
        return;
      case POSPLATNOSTI:
        setPosplatnosti((String)value);
        return;
      case UCSPOLUHRADA:
        setUcspoluhrada((String)value);
        return;
      case IDUHRADAUCETNI:
        setIdUhradaucetni((Number)value);
        return;
      case IDUHRADAADMIN:
        setIdUhradaadmin((Number)value);
        return;
      case ZAUCTUHRADA:
        setZauctuhrada((String)value);
        return;
      case IDTYPPRECENENI:
        setIdTyppreceneni((Number)value);
        return;
      case TYPPRECENENI:
        setTyppreceneni((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case SUCET2:
        setSUcet2((String)value);
        return;
      case APPUSER:
        setAppuser((String)value);
        return;
      case CDPH:
        setCDph((String)value);
        return;
      case IDBUDGET:
        setIdBudget((Number)value);
        return;
      case IDTTDEVELOPER:
        setIdTtdeveloper((Number)value);
        return;
      case IDCISUHRADA:
        setIdCisuhrada((Number)value);
        return;
      case UHRADA:
        setUhrada((String)value);
        return;
      case DTUCETNIZAMITNUTO:
        setDtUcetnizamitnuto((Date)value);
        return;
      case SUCETNIZAMITNUTO:
        setSUcetnizamitnuto((String)value);
        return;
      case ZODPOVEDNAUCETNI:
        setZodpovednaucetni((String)value);
        return;
      case CSPECIAL:
        setCSpecial((String)value);
        return;
      case IDKTGUCETNISPOLECNOST2:
        setIdKtgucetnispolecnost2((Number)value);
        return;
      case SPOLECNOST2:
        setSpolecnost2((String)value);
        return;
      case SUCETB:
        setSUcetb((String)value);
        return;
      case SUCETB2:
        setSUcetb2((String)value);
        return;
      case CTISKMAJETEK:
        setCTiskmajetek((String)value);
        return;
      case IDKATEGORIE:
        setIdKategorie((Number)value);
        return;
      case CERPATREZERVU:
        setCerpatRezervu((String)value);
        return;
      case DTNAVYSENISCHVALENO:
        setDtNavyseniSchvaleno((Date)value);
        return;
      case DTNAVYSENIZAMITNUTO:
        setDtNavyseniZamitnuto((Date)value);
        return;
      case SNAVYSENIZAMITNUTO:
        setSNavyseniZamitnuto((String)value);
        return;
      case IDNAVYSENIMB:
        setIdNavyseniMb((Number)value);
        return;
      case MASTERBUDGETER:
        setMasterBudgeter((String)value);
        return;
      case DRIDRADKU:
        setDrIdRadku((Number)value);
        return;
      case DRIDODBOR:
        setDrIdOdbor((Number)value);
        return;
      case DRODBOR:
        setDrOdbor((String)value);
        return;
      case DRIDPROJEKT:
        setDrIdProjekt((Number)value);
        return;
      case DRPROJEKT:
        setDrProjekt((String)value);
        return;
      case DRNDCASTKA:
        setDrNdCastka((Number)value);
        return;
      case DRIDODBOROO:
        setDrIdOdboroo((Number)value);
        return;
      case DRODBOROO:
        setDrOdboroo((String)value);
        return;
      case DRIDPROJEKTMAN:
        setDrIdProjektman((Number)value);
        return;
      case DRPROJEKTMAN:
        setDrProjektman((String)value);
        return;
      case DRIDUCSPOLOO:
        setDrIdUcspoloo((Number)value);
        return;
      case DRUCSPOLOO:
        setDrUcspoloo((String)value);
        return;
      case DRIDUCSPOLTOP:
        setDrIdUcspoltop((Number)value);
        return;
      case DRUCSPOLTOP:
        setDrUcspoltop((String)value);
        return;
      case DRDTDATUMZADANI:
        setDrDtDatumzadani((Date)value);
        return;
      case DRCZOBJEDNAVKY:
        setDrCZobjednavky((String)value);
        return;
      case DRIDZAMITNUTO:
        setDrIdZamitnuto((Number)value);
        return;
      case DRDTZAMITNUTO:
        setDrDtZamitnuto((Date)value);
        return;
      case DRSZAMITNUTO:
        setDrSZamitnuto((String)value);
        return;
      case DRIDODBOROOREAL:
        setDrIdOdborooreal((Number)value);
        return;
      case DRIDPROJEKTMANREAL:
        setDrIdProjektmanreal((Number)value);
        return;
      case DRIDUCSPOLOOREAL:
        setDrIdUcspolooreal((Number)value);
        return;
      case DRIDUCSPOLTOPREAL:
        setDrIdUcspoltopreal((Number)value);
        return;
      case DRIDTYPTRANSAKCE:
        setDrIdTyptransakce((Number)value);
        return;
      case DRIDPREFAKT:
        setDrIdPrefakt((Number)value);
        return;
      case DRCKPREFAKT:
        setDrCKprefakt((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id, Number drIdRadku)
  {
    return new Key(new Object[] {id, drIdRadku});
  }
}