package cz.jtbank.konsolidace.admin;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKalendarakciImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SDEN = 1;
  protected static final int CPOSILATEMAILY = 2;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKalendarakciImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.admin.KpKalendarakci");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for SDen, using the alias name SDen
   */
  public String getSDen()
  {
    return (String)getAttributeInternal(SDEN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SDen
   */
  public void setSDen(String value)
  {
    setAttributeInternal(SDEN, value);
  }

  /**
   * 
   * Gets the attribute value for CPosilatemaily, using the alias name CPosilatemaily
   */
  public String getCPosilatemaily()
  {
    return (String)getAttributeInternal(CPOSILATEMAILY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CPosilatemaily
   */
  public void setCPosilatemaily(String value)
  {
    setAttributeInternal(CPOSILATEMAILY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SDEN:
        return getSDen();
      case CPOSILATEMAILY:
        return getCPosilatemaily();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case SDEN:
        setSDen((String)value);
        return;
      case CPOSILATEMAILY:
        setCPosilatemaily((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }
}