package cz.jtbank.konsolidace.pb;
import cz.jtbank.konsolidace.common.*;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransaction;
import java.sql.*;
import cz.jtbank.konsolidace.common.KisException;
import cz.jtbank.konsolidace.evi.KpCisEvidoidentifikaceViewImpl;
import cz.jtbank.konsolidace.evi.KpCisEvidovaneinformaceViewImpl;
import cz.jtbank.konsolidace.evi.KpCisEvistatusViewImpl;
import cz.jtbank.konsolidace.evi.KpCisEvitypstatzastupceViewImpl;
import cz.jtbank.konsolidace.evi.KpDatEvibankyViewImpl;
import cz.jtbank.konsolidace.evi.KpDatEvidokumentViewImpl;
import cz.jtbank.konsolidace.evi.KpDatEvikomisionarskesmlouvyViewImpl;
import cz.jtbank.konsolidace.evi.KpDatEvikorespondenceViewImpl;
import cz.jtbank.konsolidace.evi.KpDatEvizplnomocneniViewImpl;
import cz.jtbank.konsolidace.evi.KpKtgEviadminspolecnostViewImpl;
import cz.jtbank.konsolidace.evi.KpKtgEvisidloViewImpl;
import cz.jtbank.konsolidace.evi.KpKtgEvistatutarnizastupceViewImpl;
import cz.jtbank.konsolidace.evi.KpRelTypspolevidinfoViewImpl;
import cz.jtbank.konsolidace.evi.VwKtgEviadminspolecnostViewImpl;
import cz.jtbank.konsolidace.evi.KpRelDblinkappuserViewImpl;
import cz.jtbank.konsolidace.evi.KpCisDatabazeViewImpl;
import cz.jtbank.konsolidace.protistrany.KpKtgSpolecnostViewImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.client.Configuration;
import oracle.jbo.ViewObject;
import oracle.jbo.Row;
import cz.jtbank.konsolidace.ucskup.KpCisStatViewImpl;
import cz.jtbank.konsolidace.users.KtgAppuserViewImpl;
import java.io.*;
import cz.jtbank.konsolidace.excel.*;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PbModuleImpl extends ApplicationModuleImpl implements cz.jtbank.konsolidace.pb.common.PbModule 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PbModuleImpl()
  {
  }

  /**
   * 
   * Container's getter for KpCisPbkategorieklientaView1
   */
  public KpCisPbkategorieklientaViewImpl getKpCisPbkategorieklientaView1()
  {
    return (KpCisPbkategorieklientaViewImpl)findViewObject("KpCisPbkategorieklientaView1");
  }

  /**
   * 
   * Container's getter for KpCisPbstatusklientaView1
   */
  public KpCisPbstatusklientaViewImpl getKpCisPbstatusklientaView1()
  {
    return (KpCisPbstatusklientaViewImpl)findViewObject("KpCisPbstatusklientaView1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
  public static void main(String[] args)
  {
    launchTester("cz.jtbank.konsolidace.pb", "PbModuleLocal");
  }
   */

  /**
   * 
   * Container's getter for KpKtgPbskupinaView1
   */
  public KpKtgPbskupinaViewImpl getKpKtgPbskupinaView1()
  {
    return (KpKtgPbskupinaViewImpl)findViewObject("KpKtgPbskupinaView1");
  }
  
  public void skupina(String akce,
                      int id,
                      String popis) throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;

    //INSERT
    if("I".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("INSERT INTO DB_JT.KP_KTG_PBSKUPINA "+
                                            "(ID, S_POPIS) "+
                                            "SELECT NVL(MAX(ID),0)+1,? FROM DB_JT.KP_KTG_PBSKUPINA",0);
        st.setString(1, popis);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury skupina akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    //UPDATE
    else if("U".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("UPDATE DB_JT.KP_KTG_PBSKUPINA "+
                                            "SET S_POPIS=? "+
                                            "WHERE ID=?",0);
        st.setString(1, popis);
        st.setInt(2, id);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury skupina akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    //DELETE
    else if("D".equals(akce)) {
      try {
        st = dbTran.createPreparedStatement("DELETE FROM DB_JT.KP_KTG_PBSKUPINA "+
                                            "WHERE ID=?",0);
        st.setInt(1, id);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury skupina akce="+akce,s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }
    
    dbTran.commit();
  }

  /**
   * 
   * Container's getter for KpDatPbvyjimkyView1
   */
  public KpDatPbvyjimkyViewImpl getKpDatPbvyjimkyView1()
  {
    return (KpDatPbvyjimkyViewImpl)findViewObject("KpDatPbvyjimkyView1");
  }

  /**
   * 
   * Container's getter for KpCisEvidoidentifikaceView1
   */
  public KpCisEvidoidentifikaceViewImpl getKpCisEvidoidentifikaceView1()
  {
    return (KpCisEvidoidentifikaceViewImpl)findViewObject("KpCisEvidoidentifikaceView1");
  }

  /**
   * 
   * Container's getter for KpCisEvidovaneinformaceView1
   */
  public KpCisEvidovaneinformaceViewImpl getKpCisEvidovaneinformaceView1()
  {
    return (KpCisEvidovaneinformaceViewImpl)findViewObject("KpCisEvidovaneinformaceView1");
  }

  /**
   * 
   * Container's getter for KpCisEvistatusView1
   */
  public KpCisEvistatusViewImpl getKpCisEvistatusView1()
  {
    return (KpCisEvistatusViewImpl)findViewObject("KpCisEvistatusView1");
  }

  /**
   * 
   * Container's getter for KpCisEvitypstatzastupceView1
   */
  public KpCisEvitypstatzastupceViewImpl getKpCisEvitypstatzastupceView1()
  {
    return (KpCisEvitypstatzastupceViewImpl)findViewObject("KpCisEvitypstatzastupceView1");
  }

  /**
   * 
   * Container's getter for KpDatEvibankyView1
   */
  public KpDatEvibankyViewImpl getKpDatEvibankyView1()
  {
    return (KpDatEvibankyViewImpl)findViewObject("KpDatEvibankyView1");
  }

  /**
   * 
   * Container's getter for KpDatEvidokumentView1
   */
  public KpDatEvidokumentViewImpl getKpDatEvidokumentView1()
  {
    return (KpDatEvidokumentViewImpl)findViewObject("KpDatEvidokumentView1");
  }

  /**
   * 
   * Container's getter for KpDatEvikomisionarskesmlouvyView1
   */
  public KpDatEvikomisionarskesmlouvyViewImpl getKpDatEvikomisionarskesmlouvyView1()
  {
    return (KpDatEvikomisionarskesmlouvyViewImpl)findViewObject("KpDatEvikomisionarskesmlouvyView1");
  }

  /**
   * 
   * Container's getter for KpDatEvikorespondenceView1
   */
  public KpDatEvikorespondenceViewImpl getKpDatEvikorespondenceView1()
  {
    return (KpDatEvikorespondenceViewImpl)findViewObject("KpDatEvikorespondenceView1");
  }

  /**
   * 
   * Container's getter for KpDatEvizplnomocneniView1
   */
  public KpDatEvizplnomocneniViewImpl getKpDatEvizplnomocneniView1()
  {
    return (KpDatEvizplnomocneniViewImpl)findViewObject("KpDatEvizplnomocneniView1");
  }

  /**
   * 
   * Container's getter for KpKtgEviadminspolecnostView1
   */
  public KpKtgEviadminspolecnostViewImpl getKpKtgEviadminspolecnostView1()
  {
    return (KpKtgEviadminspolecnostViewImpl)findViewObject("KpKtgEviadminspolecnostView1");
  }

  /**
   * 
   * Container's getter for KpKtgEvisidloView1
   */
  public KpKtgEvisidloViewImpl getKpKtgEvisidloView1()
  {
    return (KpKtgEvisidloViewImpl)findViewObject("KpKtgEvisidloView1");
  }

  /**
   * 
   * Container's getter for KpKtgEvistatutarnizastupceView1
   */
  public KpKtgEvistatutarnizastupceViewImpl getKpKtgEvistatutarnizastupceView1()
  {
    return (KpKtgEvistatutarnizastupceViewImpl)findViewObject("KpKtgEvistatutarnizastupceView1");
  }

  /**
   * 
   * Container's getter for KpRelTypspolevidinfoView1
   */
  public KpRelTypspolevidinfoViewImpl getKpRelTypspolevidinfoView1()
  {
    return (KpRelTypspolevidinfoViewImpl)findViewObject("KpRelTypspolevidinfoView1");
  }

  /**
   * 
   * Container's getter for VwKtgEviadminspolecnostView1
   */
  public VwKtgEviadminspolecnostViewImpl getVwKtgEviadminspolecnostView1()
  {
    return (VwKtgEviadminspolecnostViewImpl)findViewObject("VwKtgEviadminspolecnostView1");
  }

  /**
   * 
   * Container's getter for KpRelDblinkappuserView1
   */
  public KpRelDblinkappuserViewImpl getKpRelDblinkappuserView1()
  {
    return (KpRelDblinkappuserViewImpl)findViewObject("KpRelDblinkappuserView1");
  }

  /**
   * 
   * Container's getter for KpCisDatabazeView1
   */
  public KpCisDatabazeViewImpl getKpCisDatabazeView1()
  {
    return (KpCisDatabazeViewImpl)findViewObject("KpCisDatabazeView1");
  }

  /**
   * 
   * Container's getter for KpKtgPbbeznyucetView1
   */
  public KpKtgPbbeznyucetViewImpl getKpKtgPbbeznyucetView1()
  {
    return (KpKtgPbbeznyucetViewImpl)findViewObject("KpKtgPbbeznyucetView1");
  }

  /**
   * 
   * Container's getter for KpKtgPbevidencnilistView1
   */
  public KpKtgPbevidencnilistViewImpl getKpKtgPbevidencnilistView1()
  {
    return (KpKtgPbevidencnilistViewImpl)findViewObject("KpKtgPbevidencnilistView1");
  }

  /**
   * 
   * Container's getter for KpKtgPblistrizikovostiView1
   */
  public KpKtgPblistrizikovostiViewImpl getKpKtgPblistrizikovostiView1()
  {
    return (KpKtgPblistrizikovostiViewImpl)findViewObject("KpKtgPblistrizikovostiView1");
  }

  /**
   * 
   * Container's getter for KpCisPbrizikoView1
   */
  public KpCisPbrizikoViewImpl getKpCisPbrizikoView1()
  {
    return (KpCisPbrizikoViewImpl)findViewObject("KpCisPbrizikoView1");
  }

  /**
   * 
   * Container's getter for KpRelPbrizikovostView1
   */
  public KpRelPbrizikovostViewImpl getKpRelPbrizikovostView1()
  {
    return (KpRelPbrizikovostViewImpl)findViewObject("KpRelPbrizikovostView1");
  }

  private Number getIdSpolecnostFromIco(String ico) 
  {
    Number ret = null;
    
    ViewObject vo = getKpKtgSpolecnostView1();
    vo.clearCache();
    vo.setWhereClause("S_ICO = '"+ico+"'");
    if(vo.hasNext()) 
    {
      Row row = vo.next();
      ret = (Number) row.getAttribute("Id");
    }
    vo.closeRowSet();
    
    return ret;
  }

  private Object getDataFromSpolecnost(Number id, String sloupec) 
  {
    Object ret = null;
    
    ViewObject vo = getKpKtgSpolecnostView1();
    vo.clearCache();
    vo.setWhereClause("ID = "+id);
    if(vo.hasNext()) 
    {
      Row row = vo.next();
      ret = row.getAttribute(sloupec);
    }
    vo.closeRowSet();
    
    return ret;
  }

  public int zalozitSpolecnost(String ico) throws KisException
  {
    if(ico==null || ico.length()==0) return 0;
    ico = ico.trim();
    while(ico.length() < 10 ) ico = "0" + ico;
  
    DBTransaction dbTran = this.getDBTransaction();
    Statement sst = null;
    PreparedStatement st = null;
    int id = 0;

    try {
      sst = dbTran.createStatement(0);
      ResultSet rs = sst.executeQuery("select db_jt.sq_ktg_eviAdminSpolecnost.nextVal from dual");
      if(rs.next()) 
      {
        id = rs.getInt(1);
      }
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury zalozitSpolecnost - 1.",s);
    }
    finally {
      try {
        if (sst != null) sst.close();
      } 
      catch (SQLException s) { /* ignore */}
    }
    
    Number idSpol = getIdSpolecnostFromIco(ico);
    String nazev = idSpol!=null ? (String)getDataFromSpolecnost(idSpol,"SNazev") : "-";

    //INSERT
    try {
      st = dbTran.createPreparedStatement("INSERT INTO DB_JT.KP_KTG_EVIADMINSPOLECNOST "+
                                          "(ID, S_NAZEV, S_ICO, ID_STATUS, ID_TYPSPOL) "+
                                          "VALUES (?,?,?,1,2)",0);
      st.setInt(1, id);
      st.setString(2, nazev);
      st.setString(3, ico);
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury zalozitSpolecnost - 2.",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { /* ignore */}
    }

    dbTran.commit();

    if(idSpol!=null) {
      String ulice = (String)getDataFromSpolecnost(idSpol,"SUlice");
      String mesto = (String)getDataFromSpolecnost(idSpol,"SMesto");
      String psc = (String)getDataFromSpolecnost(idSpol,"SPsc");
      String stat = (String)getDataFromSpolecnost(idSpol,"SCountry");
      try {
        st = dbTran.createPreparedStatement("INSERT INTO DB_JT.KP_KTG_EVISIDLO "+
                                            "(ID,ID_ADMINSPOLECNOST,S_ULICE,S_MESTO,S_PSC,S_STAT,C_NAVRH) "+
                                            "SELECT NVL(MAX(ID),0)+1,?,?,?,?,?,'0' FROM DB_JT.KP_KTG_EVISIDLO",0);
        st.setInt(1, id);
        st.setString(2, ulice);
        st.setString(3, mesto);
        st.setString(4, psc);
        st.setString(5, stat);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury zalozitSpolecnost - 3.",s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { /* ignore */}
      }
    }

    dbTran.commit();
    
    return id;
  }

  public void ulozitSpolecnost(int idSpol,
                              String nazev,
                              String ico,
                              int idCell,
                              String ulice,
                              String mesto,
                              String psc,
                              String stat) throws KisException
  {
/*  
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;

    if(idSpol!=null) {
      String ulice = (String)getDataFromSpolecnost(idSpol,"SUlice");
      String mesto = (String)getDataFromSpolecnost(idSpol,"SMesto");
      String psc = (String)getDataFromSpolecnost(idSpol,"SPsc");
      String stat = (String)getDataFromSpolecnost(idSpol,"SCountry");
      try {
        st = dbTran.createPreparedStatement("INSERT INTO DB_JT.KP_KTG_EVISIDLO "+
                                            "(ID,ID_ADMINSPOLECNOST,S_ULICE,S_MESTO,S_PSC,S_STAT,C_NAVRH) "+
                                            "SELECT NVL(MAX(ID),0)+1,?,?,?,?,?,'0' FROM DB_JT.KP_KTG_EVISIDLO",0);
        st.setInt(1, id);
        st.setString(2, ulice);
        st.setString(3, mesto);
        st.setString(4, psc);
        st.setString(5, stat);
        st.execute();
      }
      catch (SQLException s) {
        s.printStackTrace(); //pro zacatek
        throw new KisException("Selhalo volání procedury zalozitSpolecnost - 3.",s);
      }
      finally {
        try {
          if (st != null) st.close();
        } 
        catch (SQLException s) { }
      }
    }

    dbTran.commit();
*/
  }

  /**
   * 
   * Container's getter for KpKtgSpolecnostView1
   */
  public KpKtgSpolecnostViewImpl getKpKtgSpolecnostView1()
  {
    return (KpKtgSpolecnostViewImpl)findViewObject("KpKtgSpolecnostView1");
  }
  
  public static void main(String[] argv) 
  {
    PbModuleImpl dm = (PbModuleImpl) Configuration.createRootApplicationModule("cz.jtbank.konsolidace.pb.PbModule","PbModuleLocal");
    try {
      dm.zalozitSpolecnost("0035812338");
    }
    catch(Exception e) 
    {
      e.printStackTrace();
    }
  }

  /**
   * 
   * Container's getter for KpCisStatView1
   */
  public KpCisStatViewImpl getKpCisStatView1()
  {
    return (KpCisStatViewImpl)findViewObject("KpCisStatView1");
  }

  /**
   * 
   * Container's getter for KtgAppuserView1
   */
  public KtgAppuserViewImpl getKtgAppuserView1()
  {
    return (KtgAppuserViewImpl)findViewObject("KtgAppuserView1");
  }

  public void deleteAllEPerspektiva() throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;
    try 
    {
      st = dbTran.createPreparedStatement("delete db_dsa.kp_tmp_eperspektivaOsobyPb",0);
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury deleteAllEPerspektiva",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { }
    }

    dbTran.commit();
  }
  
  public void insertEPerspektiva(int idOsoba,
                                 String banker,
                                 String ico,
                                 String nazev,
                                 String scp,
                                 String ulice,
                                 String mesto,
                                 String psc,
                                 String ico2) throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;
    try 
    {
      st = dbTran.createPreparedStatement("insert into db_dsa.kp_tmp_eperspektivaOsobyPb (osoba_id,privatni_banker,ico,nazev,scp_klient_id,ulice,mesto,psc,ico_cizinec) "+
                                          "values (?,?,?,?,?,?,?,?,?)",0);
      st.setInt(1, idOsoba);
      st.setString(2, banker);
      st.setString(3, ico);
      st.setString(4, nazev);
      st.setString(5, scp);
      st.setString(6, ulice);
      st.setString(7, mesto);
      st.setString(8, psc);
      st.setString(9, ico2);
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury insertEPerspektiva",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { }
    }

    dbTran.commit();
  }

  public void reloadKlienti() throws KisException
  {
    DBTransaction dbTran = this.getDBTransaction();
    PreparedStatement st = null;
    try 
    {
      st = dbTran.createPreparedStatement("begin db_dsa.kap_privateBanking.p_loadKlienti(?); end;",0);
      st.setString(1, Utils.getUserName(this, true));
      st.execute();
    }
    catch (SQLException s) {
      s.printStackTrace(); //pro zacatek
      throw new KisException("Selhalo volání procedury db_dsa.kap_privateBanking.p_loadKlienti",s);
    }
    finally {
      try {
        if (st != null) st.close();
      } 
      catch (SQLException s) { }
    }

    dbTran.commit();
  }

  /**
   * 
   * Container's getter for VwAcKlientipbView1
   */
  public VwAcKlientipbViewImpl getVwAcKlientipbView1()
  {
    return (VwAcKlientipbViewImpl)findViewObject("VwAcKlientipbView1");
  }

  public void exportExcelKlientiA(java.sql.Date datum) throws KisException
  {
    ESExportPbKlientiA ep = new ESExportPbKlientiA(this, datum);
    try {
      ep.excelOutput();
    }
    catch (IOException ex) {
      ex.printStackTrace(); //pro zacatek
    }
  }

  protected FileFilter getFileFilter(final String name) 
  {
    return new FileFilter() {
      public boolean accept(File pathname) 
      {
        return true;
      }
    };
  }

  private java.text.DateFormat df = java.text.DateFormat.getDateTimeInstance(java.text.DateFormat.MEDIUM, java.text.DateFormat.MEDIUM);

  public String getExcelsKlientiA() 
  {
    StringBuffer buf = new StringBuffer();
    String dirName = Constants.XLS_FILES_PATH + Constants.DIR_PB_KLIENTI + "\\";
    File dir = new File(dirName);
    FileFilter ff = getFileFilter("");
    File[] arr = dir.listFiles(ff);
    if(arr != null) {
      for( int i=0; i<arr.length; i++ ) 
      {
        String name = arr[i].getName();
        buf.append("<a target=\"_blank\" href=\"excelservlet/"+name+"?file="+Constants.DIR_PB_KLIENTI+"|5C" + name + "\">" + name+ "</a>");
        buf.append("&nbsp;" + df.format( new java.util.Date(arr[i].lastModified())) + "<br>"); 
      }
    }
    return buf.toString();
  }

}