package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDatDokladsubkonvazbydenikKurzViewImpl extends ViewObjectImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDatDokladsubkonvazbydenikKurzViewImpl()
  {
  }
}