package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDefQuestorvazbaproductImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDKTGUCETNISPOLECNOST = 1;
  protected static final int SPRODUCT1 = 2;
  protected static final int SPRODUCT2 = 3;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDefQuestorvazbaproductImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.KpDefQuestorvazbaproduct");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SProduct1, using the alias name SProduct1
   */
  public String getSProduct1()
  {
    return (String)getAttributeInternal(SPRODUCT1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SProduct1
   */
  public void setSProduct1(String value)
  {
    setAttributeInternal(SPRODUCT1, value);
  }

  /**
   * 
   * Gets the attribute value for SProduct2, using the alias name SProduct2
   */
  public String getSProduct2()
  {
    return (String)getAttributeInternal(SPRODUCT2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SProduct2
   */
  public void setSProduct2(String value)
  {
    setAttributeInternal(SPRODUCT2, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case SPRODUCT1:
        return getSProduct1();
      case SPRODUCT2:
        return getSProduct2();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case SPRODUCT1:
        setSProduct1((String)value);
        return;
      case SPRODUCT2:
        setSProduct2((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idKtgucetnispolecnost, String sProduct1, String sProduct2)
  {
    return new Key(new Object[] {idKtgucetnispolecnost, sProduct1, sProduct2});
  }
}