package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwJtSpolecnostImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SNAZEV = 1;
  protected static final int SSOUBORPREDPONA = 2;
  protected static final int SMENA = 3;
  protected static final int LASTCLOSEDATE = 4;
  protected static final int CAUTOMATICKEGENEROVANI = 5;
  protected static final int CRKC = 6;
  protected static final int SPINID = 7;
  protected static final int TOPASID = 8;
  protected static final int QUESTID = 9;
  protected static final int SDBLINK = 10;
  protected static final int SZKRATKA = 11;
  protected static final int IDKATEGORIE = 12;
  protected static final int ROWID = 13;
  protected static final int IDCISSUBJECT = 14;





  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwJtSpolecnostImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.VwJtSpolecnost");
    }
    return mDefinitionObject;
  }






  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }


  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }


  /**
   * 
   * Gets the attribute value for SSouborpredpona, using the alias name SSouborpredpona
   */
  public String getSSouborpredpona()
  {
    return (String)getAttributeInternal(SSOUBORPREDPONA);
  }




  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }


  /**
   * 
   * Gets the attribute value for Lastclosedate, using the alias name Lastclosedate
   */
  public Date getLastclosedate()
  {
    return (Date)getAttributeInternal(LASTCLOSEDATE);
  }


  /**
   * 
   * Gets the attribute value for CAutomatickegenerovani, using the alias name CAutomatickegenerovani
   */
  public String getCAutomatickegenerovani()
  {
    return (String)getAttributeInternal(CAUTOMATICKEGENEROVANI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CAutomatickegenerovani
   */
  public void setCAutomatickegenerovani(String value)
  {
    setAttributeInternal(CAUTOMATICKEGENEROVANI, value);
  }

  /**
   * 
   * Gets the attribute value for CRkc, using the alias name CRkc
   */
  public String getCRkc()
  {
    return (String)getAttributeInternal(CRKC);
  }


  /**
   * 
   * Gets the attribute value for SpinId, using the alias name SpinId
   */
  public Number getSpinId()
  {
    return (Number)getAttributeInternal(SPINID);
  }


  /**
   * 
   * Gets the attribute value for TopasId, using the alias name TopasId
   */
  public String getTopasId()
  {
    return (String)getAttributeInternal(TOPASID);
  }


  /**
   * 
   * Gets the attribute value for QuestId, using the alias name QuestId
   */
  public String getQuestId()
  {
    return (String)getAttributeInternal(QUESTID);
  }


  /**
   * 
   * Gets the attribute value for SDblink, using the alias name SDblink
   */
  public String getSDblink()
  {
    return (String)getAttributeInternal(SDBLINK);
  }


  /**
   * 
   * Gets the attribute value for SZkratka, using the alias name SZkratka
   */
  public String getSZkratka()
  {
    return (String)getAttributeInternal(SZKRATKA);
  }


  /**
   * 
   * Gets the attribute value for IdKategorie, using the alias name IdKategorie
   */
  public Number getIdKategorie()
  {
    return (Number)getAttributeInternal(IDKATEGORIE);
  }


  /**
   * 
   * Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SNAZEV:
        return getSNazev();
      case SSOUBORPREDPONA:
        return getSSouborpredpona();
      case SMENA:
        return getSMena();
      case LASTCLOSEDATE:
        return getLastclosedate();
      case CAUTOMATICKEGENEROVANI:
        return getCAutomatickegenerovani();
      case CRKC:
        return getCRkc();
      case SPINID:
        return getSpinId();
      case TOPASID:
        return getTopasId();
      case QUESTID:
        return getQuestId();
      case SDBLINK:
        return getSDblink();
      case SZKRATKA:
        return getSZkratka();
      case IDKATEGORIE:
        return getIdKategorie();
      case ROWID:
        return getRowID();
      case IDCISSUBJECT:
        return getIdCissubject();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CAUTOMATICKEGENEROVANI:
        setCAutomatickegenerovani((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for IdCissubject, using the alias name IdCissubject
   */
  public Number getIdCissubject()
  {
    return (Number)getAttributeInternal(IDCISSUBJECT);
  }


}