package cz.jtbank.konsolidace.doklady;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwSubkonDokladpolozkaImpl extends EntityImpl 
{
  protected static final int IDDOKLAD = 0;
  protected static final int NDCASTKALOCAL = 1;
  protected static final int NDCASTKACZK = 2;
  protected static final int NLRADEK = 3;
  protected static final int NLSLOUPEC = 4;
  protected static final int NLPORADILIST = 5;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwSubkonDokladpolozkaImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.doklady.VwSubkonDokladpolozka");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for IdDoklad, using the alias name IdDoklad
   */
  public Number getIdDoklad()
  {
    return (Number)getAttributeInternal(IDDOKLAD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDoklad
   */
  public void setIdDoklad(Number value)
  {
    setAttributeInternal(IDDOKLAD, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkaczk, using the alias name NdCastkaczk
   */
  public Number getNdCastkaczk()
  {
    return (Number)getAttributeInternal(NDCASTKACZK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkaczk
   */
  public void setNdCastkaczk(Number value)
  {
    setAttributeInternal(NDCASTKACZK, value);
  }

  /**
   * 
   * Gets the attribute value for NlRadek, using the alias name NlRadek
   */
  public Number getNlRadek()
  {
    return (Number)getAttributeInternal(NLRADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlRadek
   */
  public void setNlRadek(Number value)
  {
    setAttributeInternal(NLRADEK, value);
  }

  /**
   * 
   * Gets the attribute value for NlSloupec, using the alias name NlSloupec
   */
  public Number getNlSloupec()
  {
    return (Number)getAttributeInternal(NLSLOUPEC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlSloupec
   */
  public void setNlSloupec(Number value)
  {
    setAttributeInternal(NLSLOUPEC, value);
  }

  /**
   * 
   * Gets the attribute value for NlPoradilist, using the alias name NlPoradilist
   */
  public Number getNlPoradilist()
  {
    return (Number)getAttributeInternal(NLPORADILIST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NlPoradilist
   */
  public void setNlPoradilist(Number value)
  {
    setAttributeInternal(NLPORADILIST, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOKLAD:
        return getIdDoklad();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case NDCASTKACZK:
        return getNdCastkaczk();
      case NLRADEK:
        return getNlRadek();
      case NLSLOUPEC:
        return getNlSloupec();
      case NLPORADILIST:
        return getNlPoradilist();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case IDDOKLAD:
        setIdDoklad((Number)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case NDCASTKACZK:
        setNdCastkaczk((Number)value);
        return;
      case NLRADEK:
        setNlRadek((Number)value);
        return;
      case NLSLOUPEC:
        setNlSloupec((Number)value);
        return;
      case NLPORADILIST:
        setNlPoradilist((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idDoklad, Number nlRadek, Number nlSloupec, Number nlPoradilist)
  {
    return new Key(new Object[] {idDoklad, nlRadek, nlSloupec, nlPoradilist});
  }
}