package cz.jtbank.konsolidace.mustky;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDefUcet2ucetunifViewRowImpl extends ViewRowImpl 
{


  protected static final int ID = 0;
  protected static final int IDCISUCETUNIF = 1;
  protected static final int SUCETPRIMSYSTEM = 2;
  protected static final int IDCISSUBJECT = 3;
  protected static final int DTPLATNOSTOD = 4;
  protected static final int DTPLATNOSTDO = 5;
  protected static final int CUCETSUMA = 6;
  protected static final int SEVIDOVATPROTISTRANU = 7;
  protected static final int SZKRATKA = 8;
  protected static final int ID1 = 9;
  protected static final int SYMBOLSTRING = 10;
  protected static final int CTESTOVATMAJUCAST = 11;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDefUcet2ucetunifViewRowImpl()
  {
  }

  /**
   * 
   * Gets KpDefUcet2ucetunif entity object.
   */
  public KpDefUcet2ucetunifImpl getKpDefUcet2ucetunif()
  {
    return (KpDefUcet2ucetunifImpl)getEntity(0);
  }

  /**
   * 
   * Gets KpTmpCisucetsumatyp entity object.
   */
  public KpTmpCisucetsumatypImpl getKpTmpCisucetsumatyp()
  {
    return (KpTmpCisucetsumatypImpl)getEntity(1);
  }

  /**
   * 
   * Gets the attribute value for ID using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ID using the alias name Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for ID_CISUCETUNIF using the alias name IdCisucetunif
   */
  public Number getIdCisucetunif()
  {
    return (Number)getAttributeInternal(IDCISUCETUNIF);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ID_CISUCETUNIF using the alias name IdCisucetunif
   */
  public void setIdCisucetunif(Number value)
  {
    setAttributeInternal(IDCISUCETUNIF, value);
  }

  /**
   * 
   * Gets the attribute value for S_UCETPRIMSYSTEM using the alias name SUcetprimsystem
   */
  public String getSUcetprimsystem()
  {
    return (String)getAttributeInternal(SUCETPRIMSYSTEM);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for S_UCETPRIMSYSTEM using the alias name SUcetprimsystem
   */
  public void setSUcetprimsystem(String value)
  {
    setAttributeInternal(SUCETPRIMSYSTEM, value);
  }

  /**
   * 
   * Gets the attribute value for ID_CISSUBJECT using the alias name IdCissubject
   */
  public Number getIdCissubject()
  {
    return (Number)getAttributeInternal(IDCISSUBJECT);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ID_CISSUBJECT using the alias name IdCissubject
   */
  public void setIdCissubject(Number value)
  {
    setAttributeInternal(IDCISSUBJECT, value);
  }

  /**
   * 
   * Gets the attribute value for DT_PLATNOSTOD using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DT_PLATNOSTOD using the alias name DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DT_PLATNOSTDO using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DT_PLATNOSTDO using the alias name DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }

  /**
   * 
   * Gets the attribute value for C_UCETSUMA using the alias name CUcetsuma
   */
  public String getCUcetsuma()
  {
    return (String)getAttributeInternal(CUCETSUMA);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for C_UCETSUMA using the alias name CUcetsuma
   */
  public void setCUcetsuma(String value)
  {
    setAttributeInternal(CUCETSUMA, value);
  }

  /**
   * 
   * Gets the attribute value for S_EVIDOVATPROTISTRANU using the alias name SEvidovatprotistranu
   */
  public String getSEvidovatprotistranu()
  {
    return (String)getAttributeInternal(SEVIDOVATPROTISTRANU);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for S_EVIDOVATPROTISTRANU using the alias name SEvidovatprotistranu
   */
  public void setSEvidovatprotistranu(String value)
  {
    setAttributeInternal(SEVIDOVATPROTISTRANU, value);
  }

  /**
   * 
   * Gets the attribute value for S_ZKRATKA using the alias name SZkratka
   */
  public String getSZkratka()
  {
    return (String)getAttributeInternal(SZKRATKA);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for S_ZKRATKA using the alias name SZkratka
   */
  public void setSZkratka(String value)
  {
    setAttributeInternal(SZKRATKA, value);
  }

  /**
   * 
   * Gets the attribute value for ID using the alias name Id1
   */
  public String getId1()
  {
    return (String)getAttributeInternal(ID1);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ID using the alias name Id1
   */
  public void setId1(String value)
  {
    setAttributeInternal(ID1, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SymbolString
   */
/*
  public String getSymbolString()
  {
    StringBuffer ret = new StringBuffer();
    char ucetSuma = getCUcetsuma().charAt(0);
    
    switch (ucetSuma) {
        case '+':
        case '-':
            ret.append("(");
            break;
    }
    
    ret.append ( getSUcetprimsystem() );
    switch (ucetSuma) {
        case '+':
            ret.append(") SDT");
            break;
        case '-':
            ret.append(") SCR");
            break;                
    }
    
    if ( !"0000".equals(getSEvidovatprotistranu()) ) ret.append(" [").append(getSEvidovatprotistranu()).append("]");
    
    return ( ret.toString() );
  }
*/
  public String getSymbolString() {
    StringBuffer ret = new StringBuffer();
    char ucetSuma = getCUcetsuma().charAt(0);
    
    switch (ucetSuma) {
        case 'd':
        case 'c':
            ret.append("θαst ");
            break;
        case '+':
        case '-':
            ret.append("(");
            break;
    }
    
    ret.append ( getSUcetprimsystem() );
    switch (ucetSuma) {
        case 'D':
        case 'd':
            ret.append ( " DT" );
            break;
        case 'C':
        case 'c':
            ret.append ( " CR" );
            break;
        case '+':
            ret.append(") SDT");
            break;
        case '-':
            ret.append(") SCR");
            break;                
        case '3': //'0'
            ret.append ( " PrDT" );
            break;
        case '9': //'9'
            ret.append ( " PrCR" );
            break;
        case '1': //'1'
            ret.append ( " PrDT_L0" );
            break;
        case '2': //'2'
            ret.append ( " PrDT_L" );
            break;
    }
    
    if ( !"0000".equals(getSEvidovatprotistranu()) ) ret.append(" [").append(getSEvidovatprotistranu()).append("]");
    
    return ( ret.toString() );
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SymbolString
   */
  public void setSymbolString(String value)
  {
    setAttributeInternal(SYMBOLSTRING, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDCISUCETUNIF:
        return getIdCisucetunif();
      case SUCETPRIMSYSTEM:
        return getSUcetprimsystem();
      case IDCISSUBJECT:
        return getIdCissubject();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      case CUCETSUMA:
        return getCUcetsuma();
      case SEVIDOVATPROTISTRANU:
        return getSEvidovatprotistranu();
      case SZKRATKA:
        return getSZkratka();
      case ID1:
        return getId1();
      case SYMBOLSTRING:
        return getSymbolString();
      case CTESTOVATMAJUCAST:
        return getCTestovatmajucast();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDCISUCETUNIF:
        setIdCisucetunif((Number)value);
        return;
      case SUCETPRIMSYSTEM:
        setSUcetprimsystem((String)value);
        return;
      case IDCISSUBJECT:
        setIdCissubject((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      case CUCETSUMA:
        setCUcetsuma((String)value);
        return;
      case SEVIDOVATPROTISTRANU:
        setSEvidovatprotistranu((String)value);
        return;
      case SZKRATKA:
        setSZkratka((String)value);
        return;
      case ID1:
        setId1((String)value);
        return;
      case CTESTOVATMAJUCAST:
        setCTestovatmajucast((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for C_TESTOVATMAJUCAST using the alias name CTestovatmajucast
   */
  public String getCTestovatmajucast()
  {
    return (String)getAttributeInternal(CTESTOVATMAJUCAST);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for C_TESTOVATMAJUCAST using the alias name CTestovatmajucast
   */
  public void setCTestovatmajucast(String value)
  {
    setAttributeInternal(CTESTOVATMAJUCAST, value);
  }
}