package cz.jtbank.konsolidace.kapital;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpCisCpindexImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SEXTID = 1;
  protected static final int SNAZEV = 2;
  protected static final int KPRELCENNYPAPIRINDEX = 3;





  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpCisCpindexImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.kapital.KpCisCpindex");
    }
    return mDefinitionObject;
  }






  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for SExtid, using the alias name SExtid
   */
  public String getSExtid()
  {
    return (String)getAttributeInternal(SEXTID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SExtid
   */
  public void setSExtid(String value)
  {
    setAttributeInternal(SEXTID, value);
  }




  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SEXTID:
        return getSExtid();
      case SNAZEV:
        return getSNazev();
      case KPRELCENNYPAPIRINDEX:
        return getKpRelCennypapirindex();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case SEXTID:
        setSExtid((String)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpRelCennypapirindex()
  {
    return (RowIterator)getAttributeInternal(KPRELCENNYPAPIRINDEX);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }




}