package cz.jtbank.konsolidace.dokument;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpCisTyptransakceImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int SPOPIS = 1;
  protected static final int SKOD = 2;
  protected static final int IDGESTORCZ = 3;
  protected static final int IDGESTORSK = 4;
  protected static final int IDGESTORZ = 5;
  protected static final int IDTYPTRANSAKCEGROUP = 6;
  protected static final int DTPLATNOSTOD = 7;
  protected static final int DTPLATNOSTDO = 8;
  protected static final int CPROZASTUPCE = 9;
  protected static final int NDBUDGETNAVYSENIGESTOR = 10;
  protected static final int CDEVELOPER = 11;
  protected static final int SKOMENTAR = 12;
  protected static final int CSPECIAL = 13;
  protected static final int CPODVOJNEMIS = 14;
  protected static final int NDUROVENPROJEKT = 15;
  protected static final int NDUROVENSPOLECNOST = 16;
  protected static final int NDUROVENTOP = 17;
  protected static final int SMENAUP = 18;
  protected static final int SMENAUS = 19;
  protected static final int SMENAUT = 20;
  protected static final int CTISKMAJETEK = 21;
  protected static final int CBUDGETOVAT = 22;
  protected static final int CCAPEXOPEX = 23;
  protected static final int KPCISMISUCTYMDD = 24;
  protected static final int KPRELMISUROVENSCHVALOVANI = 25;























  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpCisTyptransakceImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.dokument.KpCisTyptransakce");
    }
    return mDefinitionObject;
  }
























  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }

  /**
   * 
   * Gets the attribute value for SKod, using the alias name SKod
   */
  public String getSKod()
  {
    return (String)getAttributeInternal(SKOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SKod
   */
  public void setSKod(String value)
  {
    setAttributeInternal(SKOD, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case SPOPIS:
        return getSPopis();
      case SKOD:
        return getSKod();
      case IDGESTORCZ:
        return getIdGestorCz();
      case IDGESTORSK:
        return getIdGestorSk();
      case IDGESTORZ:
        return getIdGestorZ();
      case IDTYPTRANSAKCEGROUP:
        return getIdTyptransakcegroup();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      case CPROZASTUPCE:
        return getCProzastupce();
      case NDBUDGETNAVYSENIGESTOR:
        return getNdBudgetnavyseniGestor();
      case CDEVELOPER:
        return getCDeveloper();
      case SKOMENTAR:
        return getSKomentar();
      case CSPECIAL:
        return getCSpecial();
      case CPODVOJNEMIS:
        return getCPodvojnemis();
      case NDUROVENPROJEKT:
        return getNdUrovenprojekt();
      case NDUROVENSPOLECNOST:
        return getNdUrovenspolecnost();
      case NDUROVENTOP:
        return getNdUroventop();
      case SMENAUP:
        return getSMenaup();
      case SMENAUS:
        return getSMenaus();
      case SMENAUT:
        return getSMenaut();
      case CTISKMAJETEK:
        return getCTiskmajetek();
      case CBUDGETOVAT:
        return getCBudgetovat();
      case CCAPEXOPEX:
        return getCCapexOpex();
      case KPCISMISUCTYMDD:
        return getKpCisMisuctymdd();
      case KPRELMISUROVENSCHVALOVANI:
        return getKpRelMisurovenschvalovani();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case SPOPIS:
        setSPopis((String)value);
        return;
      case SKOD:
        setSKod((String)value);
        return;
      case IDGESTORCZ:
        setIdGestorCz((Number)value);
        return;
      case IDGESTORSK:
        setIdGestorSk((Number)value);
        return;
      case IDGESTORZ:
        setIdGestorZ((Number)value);
        return;
      case IDTYPTRANSAKCEGROUP:
        setIdTyptransakcegroup((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      case CPROZASTUPCE:
        setCProzastupce((String)value);
        return;
      case NDBUDGETNAVYSENIGESTOR:
        setNdBudgetnavyseniGestor((Number)value);
        return;
      case CDEVELOPER:
        setCDeveloper((String)value);
        return;
      case SKOMENTAR:
        setSKomentar((String)value);
        return;
      case CSPECIAL:
        setCSpecial((String)value);
        return;
      case CPODVOJNEMIS:
        setCPodvojnemis((String)value);
        return;
      case NDUROVENPROJEKT:
        setNdUrovenprojekt((Number)value);
        return;
      case NDUROVENSPOLECNOST:
        setNdUrovenspolecnost((Number)value);
        return;
      case NDUROVENTOP:
        setNdUroventop((Number)value);
        return;
      case SMENAUP:
        setSMenaup((String)value);
        return;
      case SMENAUS:
        setSMenaus((String)value);
        return;
      case SMENAUT:
        setSMenaut((String)value);
        return;
      case CTISKMAJETEK:
        setCTiskmajetek((String)value);
        return;
      case CBUDGETOVAT:
        setCBudgetovat((String)value);
        return;
      case CCAPEXOPEX:
        setCCapexOpex((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }





  /**
   * 
   * Gets the attribute value for IdGestorCz, using the alias name IdGestorCz
   */
  public Number getIdGestorCz()
  {
    return (Number)getAttributeInternal(IDGESTORCZ);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdGestorCz
   */
  public void setIdGestorCz(Number value)
  {
    setAttributeInternal(IDGESTORCZ, value);
  }

  /**
   * 
   * Gets the attribute value for IdGestorSk, using the alias name IdGestorSk
   */
  public Number getIdGestorSk()
  {
    return (Number)getAttributeInternal(IDGESTORSK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdGestorSk
   */
  public void setIdGestorSk(Number value)
  {
    setAttributeInternal(IDGESTORSK, value);
  }

  /**
   * 
   * Gets the attribute value for IdGestorZ, using the alias name IdGestorZ
   */
  public Number getIdGestorZ()
  {
    return (Number)getAttributeInternal(IDGESTORZ);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdGestorZ
   */
  public void setIdGestorZ(Number value)
  {
    setAttributeInternal(IDGESTORZ, value);
  }


  /**
   * 
   * Gets the attribute value for IdTyptransakcegroup, using the alias name IdTyptransakcegroup
   */
  public Number getIdTyptransakcegroup()
  {
    return (Number)getAttributeInternal(IDTYPTRANSAKCEGROUP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTyptransakcegroup
   */
  public void setIdTyptransakcegroup(Number value)
  {
    setAttributeInternal(IDTYPTRANSAKCEGROUP, value);
  }


  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }


  /**
   * 
   * Gets the attribute value for CProzastupce, using the alias name CProzastupce
   */
  public String getCProzastupce()
  {
    return (String)getAttributeInternal(CPROZASTUPCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CProzastupce
   */
  public void setCProzastupce(String value)
  {
    setAttributeInternal(CPROZASTUPCE, value);
  }


  /**
   * 
   * Gets the attribute value for NdBudgetnavyseniGestor, using the alias name NdBudgetnavyseniGestor
   */
  public Number getNdBudgetnavyseniGestor()
  {
    return (Number)getAttributeInternal(NDBUDGETNAVYSENIGESTOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdBudgetnavyseniGestor
   */
  public void setNdBudgetnavyseniGestor(Number value)
  {
    setAttributeInternal(NDBUDGETNAVYSENIGESTOR, value);
  }

  /**
   * 
   * Gets the attribute value for CDeveloper, using the alias name CDeveloper
   */
  public String getCDeveloper()
  {
    return (String)getAttributeInternal(CDEVELOPER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CDeveloper
   */
  public void setCDeveloper(String value)
  {
    setAttributeInternal(CDEVELOPER, value);
  }


  /**
   * 
   * Gets the attribute value for SKomentar, using the alias name SKomentar
   */
  public String getSKomentar()
  {
    return (String)getAttributeInternal(SKOMENTAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SKomentar
   */
  public void setSKomentar(String value)
  {
    setAttributeInternal(SKOMENTAR, value);
  }


  /**
   * 
   * Gets the attribute value for CSpecial, using the alias name CSpecial
   */
  public String getCSpecial()
  {
    return (String)getAttributeInternal(CSPECIAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CSpecial
   */
  public void setCSpecial(String value)
  {
    setAttributeInternal(CSPECIAL, value);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpCisMisuctymdd()
  {
    return (RowIterator)getAttributeInternal(KPCISMISUCTYMDD);
  }


  /**
   * 
   * Gets the attribute value for CPodvojnemis, using the alias name CPodvojnemis
   */
  public String getCPodvojnemis()
  {
    return (String)getAttributeInternal(CPODVOJNEMIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CPodvojnemis
   */
  public void setCPodvojnemis(String value)
  {
    setAttributeInternal(CPODVOJNEMIS, value);
  }


  /**
   * 
   * Gets the attribute value for NdUrovenprojekt, using the alias name NdUrovenprojekt
   */
  public Number getNdUrovenprojekt()
  {
    return (Number)getAttributeInternal(NDUROVENPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdUrovenprojekt
   */
  public void setNdUrovenprojekt(Number value)
  {
    setAttributeInternal(NDUROVENPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for NdUrovenspolecnost, using the alias name NdUrovenspolecnost
   */
  public Number getNdUrovenspolecnost()
  {
    return (Number)getAttributeInternal(NDUROVENSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdUrovenspolecnost
   */
  public void setNdUrovenspolecnost(Number value)
  {
    setAttributeInternal(NDUROVENSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for NdUroventop, using the alias name NdUroventop
   */
  public Number getNdUroventop()
  {
    return (Number)getAttributeInternal(NDUROVENTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdUroventop
   */
  public void setNdUroventop(Number value)
  {
    setAttributeInternal(NDUROVENTOP, value);
  }

  /**
   * 
   * Gets the attribute value for SMenaup, using the alias name SMenaup
   */
  public String getSMenaup()
  {
    return (String)getAttributeInternal(SMENAUP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMenaup
   */
  public void setSMenaup(String value)
  {
    setAttributeInternal(SMENAUP, value);
  }

  /**
   * 
   * Gets the attribute value for SMenaus, using the alias name SMenaus
   */
  public String getSMenaus()
  {
    return (String)getAttributeInternal(SMENAUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMenaus
   */
  public void setSMenaus(String value)
  {
    setAttributeInternal(SMENAUS, value);
  }

  /**
   * 
   * Gets the attribute value for SMenaut, using the alias name SMenaut
   */
  public String getSMenaut()
  {
    return (String)getAttributeInternal(SMENAUT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMenaut
   */
  public void setSMenaut(String value)
  {
    setAttributeInternal(SMENAUT, value);
  }


  /**
   * 
   * Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getKpRelMisurovenschvalovani()
  {
    return (RowIterator)getAttributeInternal(KPRELMISUROVENSCHVALOVANI);
  }


  /**
   * 
   * Gets the attribute value for CTiskmajetek, using the alias name CTiskmajetek
   */
  public String getCTiskmajetek()
  {
    return (String)getAttributeInternal(CTISKMAJETEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CTiskmajetek
   */
  public void setCTiskmajetek(String value)
  {
    setAttributeInternal(CTISKMAJETEK, value);
  }


  /**
   * 
   * Gets the attribute value for CBudgetovat, using the alias name CBudgetovat
   */
  public String getCBudgetovat()
  {
    return (String)getAttributeInternal(CBUDGETOVAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CBudgetovat
   */
  public void setCBudgetovat(String value)
  {
    setAttributeInternal(CBUDGETOVAT, value);
  }


  /**
   * 
   * Gets the attribute value for CCapexOpex, using the alias name CCapexOpex
   */
  public String getCCapexOpex()
  {
    return (String)getAttributeInternal(CCAPEXOPEX);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CCapexOpex
   */
  public void setCCapexOpex(String value)
  {
    setAttributeInternal(CCAPEXOPEX, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }










}