package cz.jtbank.konsolidace.dokument;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatSchvalovakradekImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDDOKUMENT = 1;
  protected static final int IDODBOR = 2;
  protected static final int IDPROJEKT = 3;
  protected static final int NDCASTKA = 4;
  protected static final int IDODBOROO = 5;
  protected static final int DTSCHVALENOODBOR = 6;
  protected static final int IDPROJEKTMAN = 7;
  protected static final int DTSCHVALENOPROJEKT = 8;
  protected static final int IDUCSPOLOO = 9;
  protected static final int DTSCHVALENOUCSPOL = 10;
  protected static final int IDUCSPOLTOP = 11;
  protected static final int DTSCHVALENOTOP = 12;
  protected static final int ODBOR = 13;
  protected static final int PROJEKT = 14;
  protected static final int ODBOROO = 15;
  protected static final int PROJEKTMAN = 16;
  protected static final int UCSPOLOO = 17;
  protected static final int UCSPOLTOP = 18;
  protected static final int ROWID = 19;
  protected static final int SKOMENTAR = 20;
  protected static final int IDKTGUCETNISPOLECNOST = 21;
  protected static final int DTDATUMPREFAKT = 22;
  protected static final int IDPREFAKT = 23;
  protected static final int DTDATUMZADANI = 24;
  protected static final int IDTOP = 25;
  protected static final int CKPREFAKT = 26;
  protected static final int DTDATUMZADANIRADEK = 27;
  protected static final int CREMOVED = 28;
  protected static final int IDCISSTATUS = 29;
  protected static final int CZOBJEDNAVKY = 30;
  protected static final int ODBORKOD = 31;
  protected static final int IDZAMITNUTO = 32;
  protected static final int DTZAMITNUTO = 33;
  protected static final int SZAMITNUTO = 34;
  protected static final int NESCHVALENOTOPPAR = 35;
  protected static final int ZAMITNUTO = 36;
  protected static final int IDZADAVATEL = 37;
  protected static final int IDCISDOKUMENT = 38;
  protected static final int IDGESTOR = 39;
  protected static final int DTGESTORSCHVALENO = 40;
  protected static final int GESTOR = 41;
  protected static final int IDDOKUMENTORIG = 42;
  protected static final int ODBOROOREAL = 43;
  protected static final int PROJEKTMANREAL = 44;
  protected static final int UCSPOLOOREAL = 45;
  protected static final int UCSPOLTOPREAL = 46;
  protected static final int CDOCZAMITNUTO = 47;
  protected static final int IDTYPTRANSAKCE = 48;
  protected static final int TYPTRANSAKCE = 49;
  protected static final int NDDOCUROVEN1 = 50;
  protected static final int NDDOCUROVEN2 = 51;
  protected static final int NDPROJEKTUROVEN = 52;
  protected static final int NDOBJCASTKAVOLNA = 53;
  protected static final int IDOBJRADEK = 54;
  protected static final int IDTYPIZLINK = 55;
  protected static final int NAZEVSPOLECNOSTI = 56;
  protected static final int PROTISTRANA = 57;
  protected static final int MENA = 58;
  protected static final int IDBANKAR = 59;
  protected static final int BANKAR = 60;
  protected static final int ISITBUDGET = 61;





































  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatSchvalovakradekImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.dokument.VwDatSchvalovakradek");
    }
    return mDefinitionObject;
  }






































  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdDokument, using the alias name IdDokument
   */
  public Number getIdDokument()
  {
    return (Number)getAttributeInternal(IDDOKUMENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDokument
   */
  public void setIdDokument(Number value)
  {
    setAttributeInternal(IDDOKUMENT, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdbor, using the alias name IdOdbor
   */
  public Number getIdOdbor()
  {
    return (Number)getAttributeInternal(IDODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdbor
   */
  public void setIdOdbor(Number value)
  {
    setAttributeInternal(IDODBOR, value);
  }



  /**
   * 
   * Gets the attribute value for IdProjekt, using the alias name IdProjekt
   */
  public Number getIdProjekt()
  {
    return (Number)getAttributeInternal(IDPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdProjekt
   */
  public void setIdProjekt(Number value)
  {
    setAttributeInternal(IDPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastka, using the alias name NdCastka
   */
  public Number getNdCastka()
  {
    return (Number)getAttributeInternal(NDCASTKA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastka
   */
  public void setNdCastka(Number value)
  {
    setAttributeInternal(NDCASTKA, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdboroo, using the alias name IdOdboroo
   */
  public Number getIdOdboroo()
  {
    return (Number)getAttributeInternal(IDODBOROO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdboroo
   */
  public void setIdOdboroo(Number value)
  {
    setAttributeInternal(IDODBOROO, value);
  }

  /**
   * 
   * Gets the attribute value for DtSchvalenoodbor, using the alias name DtSchvalenoodbor
   */
  public Date getDtSchvalenoodbor()
  {
    return (Date)getAttributeInternal(DTSCHVALENOODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtSchvalenoodbor
   */
  public void setDtSchvalenoodbor(Date value)
  {
    setAttributeInternal(DTSCHVALENOODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for IdProjektman, using the alias name IdProjektman
   */
  public Number getIdProjektman()
  {
    return (Number)getAttributeInternal(IDPROJEKTMAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdProjektman
   */
  public void setIdProjektman(Number value)
  {
    setAttributeInternal(IDPROJEKTMAN, value);
  }

  /**
   * 
   * Gets the attribute value for DtSchvalenoprojekt, using the alias name DtSchvalenoprojekt
   */
  public Date getDtSchvalenoprojekt()
  {
    return (Date)getAttributeInternal(DTSCHVALENOPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtSchvalenoprojekt
   */
  public void setDtSchvalenoprojekt(Date value)
  {
    setAttributeInternal(DTSCHVALENOPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for IdUcspoloo, using the alias name IdUcspoloo
   */
  public Number getIdUcspoloo()
  {
    return (Number)getAttributeInternal(IDUCSPOLOO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUcspoloo
   */
  public void setIdUcspoloo(Number value)
  {
    setAttributeInternal(IDUCSPOLOO, value);
  }

  /**
   * 
   * Gets the attribute value for DtSchvalenoucspol, using the alias name DtSchvalenoucspol
   */
  public Date getDtSchvalenoucspol()
  {
    return (Date)getAttributeInternal(DTSCHVALENOUCSPOL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtSchvalenoucspol
   */
  public void setDtSchvalenoucspol(Date value)
  {
    setAttributeInternal(DTSCHVALENOUCSPOL, value);
  }

  /**
   * 
   * Gets the attribute value for IdUcspoltop, using the alias name IdUcspoltop
   */
  public Number getIdUcspoltop()
  {
    return (Number)getAttributeInternal(IDUCSPOLTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUcspoltop
   */
  public void setIdUcspoltop(Number value)
  {
    setAttributeInternal(IDUCSPOLTOP, value);
  }

  /**
   * 
   * Gets the attribute value for DtSchvalenotop, using the alias name DtSchvalenotop
   */
  public Date getDtSchvalenotop()
  {
    return (Date)getAttributeInternal(DTSCHVALENOTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtSchvalenotop
   */
  public void setDtSchvalenotop(Date value)
  {
    setAttributeInternal(DTSCHVALENOTOP, value);
  }





  /**
   * 
   * Gets the attribute value for Odbor, using the alias name Odbor
   */
  public String getOdbor()
  {
    return (String)getAttributeInternal(ODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odbor
   */
  public void setOdbor(String value)
  {
    setAttributeInternal(ODBOR, value);
  }



  /**
   * 
   * Gets the attribute value for Projekt, using the alias name Projekt
   */
  public String getProjekt()
  {
    return (String)getAttributeInternal(PROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Projekt
   */
  public void setProjekt(String value)
  {
    setAttributeInternal(PROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for Odboroo, using the alias name Odboroo
   */
  public String getOdboroo()
  {
    return (String)getAttributeInternal(ODBOROO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odboroo
   */
  public void setOdboroo(String value)
  {
    setAttributeInternal(ODBOROO, value);
  }

  /**
   * 
   * Gets the attribute value for Projektman, using the alias name Projektman
   */
  public String getProjektman()
  {
    return (String)getAttributeInternal(PROJEKTMAN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Projektman
   */
  public void setProjektman(String value)
  {
    setAttributeInternal(PROJEKTMAN, value);
  }

  /**
   * 
   * Gets the attribute value for Ucspoloo, using the alias name Ucspoloo
   */
  public String getUcspoloo()
  {
    return (String)getAttributeInternal(UCSPOLOO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Ucspoloo
   */
  public void setUcspoloo(String value)
  {
    setAttributeInternal(UCSPOLOO, value);
  }

  /**
   * 
   * Gets the attribute value for Ucspoltop, using the alias name Ucspoltop
   */
  public String getUcspoltop()
  {
    return (String)getAttributeInternal(UCSPOLTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Ucspoltop
   */
  public void setUcspoltop(String value)
  {
    setAttributeInternal(UCSPOLTOP, value);
  }

  /**
   * 
   * Gets the attribute value for RowID, using the alias name RowID
   */
  public RowID getRowID()
  {
    return (RowID)getAttributeInternal(ROWID);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDDOKUMENT:
        return getIdDokument();
      case IDODBOR:
        return getIdOdbor();
      case IDPROJEKT:
        return getIdProjekt();
      case NDCASTKA:
        return getNdCastka();
      case IDODBOROO:
        return getIdOdboroo();
      case DTSCHVALENOODBOR:
        return getDtSchvalenoodbor();
      case IDPROJEKTMAN:
        return getIdProjektman();
      case DTSCHVALENOPROJEKT:
        return getDtSchvalenoprojekt();
      case IDUCSPOLOO:
        return getIdUcspoloo();
      case DTSCHVALENOUCSPOL:
        return getDtSchvalenoucspol();
      case IDUCSPOLTOP:
        return getIdUcspoltop();
      case DTSCHVALENOTOP:
        return getDtSchvalenotop();
      case ODBOR:
        return getOdbor();
      case PROJEKT:
        return getProjekt();
      case ODBOROO:
        return getOdboroo();
      case PROJEKTMAN:
        return getProjektman();
      case UCSPOLOO:
        return getUcspoloo();
      case UCSPOLTOP:
        return getUcspoltop();
      case ROWID:
        return getRowID();
      case SKOMENTAR:
        return getSKomentar();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case DTDATUMPREFAKT:
        return getDtDatumprefakt();
      case IDPREFAKT:
        return getIdPrefakt();
      case DTDATUMZADANI:
        return getDtDatumzadani();
      case IDTOP:
        return getIdTop();
      case CKPREFAKT:
        return getCKprefakt();
      case DTDATUMZADANIRADEK:
        return getDtDatumzadaniradek();
      case CREMOVED:
        return getCRemoved();
      case IDCISSTATUS:
        return getIdCisstatus();
      case CZOBJEDNAVKY:
        return getCZobjednavky();
      case ODBORKOD:
        return getOdborKod();
      case IDZAMITNUTO:
        return getIdZamitnuto();
      case DTZAMITNUTO:
        return getDtZamitnuto();
      case SZAMITNUTO:
        return getSZamitnuto();
      case NESCHVALENOTOPPAR:
        return getNeschvalenoTopPar();
      case ZAMITNUTO:
        return getZamitnuto();
      case IDZADAVATEL:
        return getIdZadavatel();
      case IDCISDOKUMENT:
        return getIdCisdokument();
      case IDGESTOR:
        return getIdGestor();
      case DTGESTORSCHVALENO:
        return getDtGestorschvaleno();
      case GESTOR:
        return getGestor();
      case IDDOKUMENTORIG:
        return getIdDokumentorig();
      case ODBOROOREAL:
        return getOdborooreal();
      case PROJEKTMANREAL:
        return getProjektmanreal();
      case UCSPOLOOREAL:
        return getUcspolooreal();
      case UCSPOLTOPREAL:
        return getUcspoltopreal();
      case CDOCZAMITNUTO:
        return getCDoczamitnuto();
      case IDTYPTRANSAKCE:
        return getIdTyptransakce();
      case TYPTRANSAKCE:
        return getTyptransakce();
      case NDDOCUROVEN1:
        return getNdDocuroven1();
      case NDDOCUROVEN2:
        return getNdDocuroven2();
      case NDPROJEKTUROVEN:
        return getNdProjekturoven();
      case NDOBJCASTKAVOLNA:
        return getNdObjCastkaVolna();
      case IDOBJRADEK:
        return getIdObjRadek();
      case IDTYPIZLINK:
        return getIdTypizlink();
      case NAZEVSPOLECNOSTI:
        return getNazevSpolecnosti();
      case PROTISTRANA:
        return getProtistrana();
      case MENA:
        return getMena();
      case IDBANKAR:
        return getIdBankar();
      case BANKAR:
        return getBankar();
      case ISITBUDGET:
        return getIsitBudget();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDDOKUMENT:
        setIdDokument((Number)value);
        return;
      case IDODBOR:
        setIdOdbor((Number)value);
        return;
      case IDPROJEKT:
        setIdProjekt((Number)value);
        return;
      case NDCASTKA:
        setNdCastka((Number)value);
        return;
      case IDODBOROO:
        setIdOdboroo((Number)value);
        return;
      case DTSCHVALENOODBOR:
        setDtSchvalenoodbor((Date)value);
        return;
      case IDPROJEKTMAN:
        setIdProjektman((Number)value);
        return;
      case DTSCHVALENOPROJEKT:
        setDtSchvalenoprojekt((Date)value);
        return;
      case IDUCSPOLOO:
        setIdUcspoloo((Number)value);
        return;
      case DTSCHVALENOUCSPOL:
        setDtSchvalenoucspol((Date)value);
        return;
      case IDUCSPOLTOP:
        setIdUcspoltop((Number)value);
        return;
      case DTSCHVALENOTOP:
        setDtSchvalenotop((Date)value);
        return;
      case ODBOR:
        setOdbor((String)value);
        return;
      case PROJEKT:
        setProjekt((String)value);
        return;
      case ODBOROO:
        setOdboroo((String)value);
        return;
      case PROJEKTMAN:
        setProjektman((String)value);
        return;
      case UCSPOLOO:
        setUcspoloo((String)value);
        return;
      case UCSPOLTOP:
        setUcspoltop((String)value);
        return;
      case SKOMENTAR:
        setSKomentar((String)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case DTDATUMPREFAKT:
        setDtDatumprefakt((Date)value);
        return;
      case IDPREFAKT:
        setIdPrefakt((Number)value);
        return;
      case DTDATUMZADANI:
        setDtDatumzadani((Date)value);
        return;
      case IDTOP:
        setIdTop((Number)value);
        return;
      case CKPREFAKT:
        setCKprefakt((String)value);
        return;
      case DTDATUMZADANIRADEK:
        setDtDatumzadaniradek((Date)value);
        return;
      case CREMOVED:
        setCRemoved((String)value);
        return;
      case IDCISSTATUS:
        setIdCisstatus((Number)value);
        return;
      case CZOBJEDNAVKY:
        setCZobjednavky((String)value);
        return;
      case ODBORKOD:
        setOdborKod((String)value);
        return;
      case IDZAMITNUTO:
        setIdZamitnuto((Number)value);
        return;
      case DTZAMITNUTO:
        setDtZamitnuto((Date)value);
        return;
      case SZAMITNUTO:
        setSZamitnuto((String)value);
        return;
      case NESCHVALENOTOPPAR:
        setNeschvalenoTopPar((String)value);
        return;
      case ZAMITNUTO:
        setZamitnuto((String)value);
        return;
      case IDZADAVATEL:
        setIdZadavatel((Number)value);
        return;
      case IDCISDOKUMENT:
        setIdCisdokument((Number)value);
        return;
      case IDGESTOR:
        setIdGestor((Number)value);
        return;
      case DTGESTORSCHVALENO:
        setDtGestorschvaleno((Date)value);
        return;
      case GESTOR:
        setGestor((String)value);
        return;
      case IDDOKUMENTORIG:
        setIdDokumentorig((Number)value);
        return;
      case ODBOROOREAL:
        setOdborooreal((String)value);
        return;
      case PROJEKTMANREAL:
        setProjektmanreal((String)value);
        return;
      case UCSPOLOOREAL:
        setUcspolooreal((String)value);
        return;
      case UCSPOLTOPREAL:
        setUcspoltopreal((String)value);
        return;
      case CDOCZAMITNUTO:
        setCDoczamitnuto((String)value);
        return;
      case IDTYPTRANSAKCE:
        setIdTyptransakce((Number)value);
        return;
      case TYPTRANSAKCE:
        setTyptransakce((String)value);
        return;
      case NDDOCUROVEN1:
        setNdDocuroven1((Number)value);
        return;
      case NDDOCUROVEN2:
        setNdDocuroven2((Number)value);
        return;
      case NDPROJEKTUROVEN:
        setNdProjekturoven((Number)value);
        return;
      case NDOBJCASTKAVOLNA:
        setNdObjCastkaVolna((Number)value);
        return;
      case IDOBJRADEK:
        setIdObjRadek((Number)value);
        return;
      case IDTYPIZLINK:
        setIdTypizlink((Number)value);
        return;
      case NAZEVSPOLECNOSTI:
        setNazevSpolecnosti((String)value);
        return;
      case PROTISTRANA:
        setProtistrana((String)value);
        return;
      case MENA:
        setMena((String)value);
        return;
      case IDBANKAR:
        setIdBankar((Number)value);
        return;
      case BANKAR:
        setBankar((String)value);
        return;
      case ISITBUDGET:
        setIsitBudget((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the attribute value for SKomentar, using the alias name SKomentar
   */
  public String getSKomentar()
  {
    return (String)getAttributeInternal(SKOMENTAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SKomentar
   */
  public void setSKomentar(String value)
  {
    setAttributeInternal(SKOMENTAR, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumprefakt, using the alias name DtDatumprefakt
   */
  public Date getDtDatumprefakt()
  {
    return (Date)getAttributeInternal(DTDATUMPREFAKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumprefakt
   */
  public void setDtDatumprefakt(Date value)
  {
    setAttributeInternal(DTDATUMPREFAKT, value);
  }

  /**
   * 
   * Gets the attribute value for IdPrefakt, using the alias name IdPrefakt
   */
  public Number getIdPrefakt()
  {
    return (Number)getAttributeInternal(IDPREFAKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdPrefakt
   */
  public void setIdPrefakt(Number value)
  {
    setAttributeInternal(IDPREFAKT, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzadani, using the alias name DtDatumzadani
   */
  public Date getDtDatumzadani()
  {
    return (Date)getAttributeInternal(DTDATUMZADANI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzadani
   */
  public void setDtDatumzadani(Date value)
  {
    setAttributeInternal(DTDATUMZADANI, value);
  }

  /**
   * 
   * Gets the attribute value for IdTop, using the alias name IdTop
   */
  public Number getIdTop()
  {
    return (Number)getAttributeInternal(IDTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTop
   */
  public void setIdTop(Number value)
  {
    setAttributeInternal(IDTOP, value);
  }

  /**
   * 
   * Gets the attribute value for CKprefakt, using the alias name CKprefakt
   */
  public String getCKprefakt()
  {
    return (String)getAttributeInternal(CKPREFAKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CKprefakt
   */
  public void setCKprefakt(String value)
  {
    setAttributeInternal(CKPREFAKT, value);
  }

  /**
   * 
   * Gets the attribute value for DtDatumzadaniradek, using the alias name DtDatumzadaniradek
   */
  public Date getDtDatumzadaniradek()
  {
    return (Date)getAttributeInternal(DTDATUMZADANIRADEK);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatumzadaniradek
   */
  public void setDtDatumzadaniradek(Date value)
  {
    setAttributeInternal(DTDATUMZADANIRADEK, value);
  }

  /**
   * 
   * Gets the attribute value for CRemoved, using the alias name CRemoved
   */
  public String getCRemoved()
  {
    return (String)getAttributeInternal(CREMOVED);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CRemoved
   */
  public void setCRemoved(String value)
  {
    setAttributeInternal(CREMOVED, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisstatus, using the alias name IdCisstatus
   */
  public Number getIdCisstatus()
  {
    return (Number)getAttributeInternal(IDCISSTATUS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisstatus
   */
  public void setIdCisstatus(Number value)
  {
    setAttributeInternal(IDCISSTATUS, value);
  }

  /**
   * 
   * Gets the attribute value for CZobjednavky, using the alias name CZobjednavky
   */
  public String getCZobjednavky()
  {
    return (String)getAttributeInternal(CZOBJEDNAVKY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CZobjednavky
   */
  public void setCZobjednavky(String value)
  {
    setAttributeInternal(CZOBJEDNAVKY, value);
  }

  /**
   * 
   * Gets the attribute value for OdborKod, using the alias name OdborKod
   */
  public String getOdborKod()
  {
    return (String)getAttributeInternal(ODBORKOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for OdborKod
   */
  public void setOdborKod(String value)
  {
    setAttributeInternal(ODBORKOD, value);
  }

  /**
   * 
   * Gets the attribute value for IdZamitnuto, using the alias name IdZamitnuto
   */
  public Number getIdZamitnuto()
  {
    return (Number)getAttributeInternal(IDZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZamitnuto
   */
  public void setIdZamitnuto(Number value)
  {
    setAttributeInternal(IDZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for DtZamitnuto, using the alias name DtZamitnuto
   */
  public Date getDtZamitnuto()
  {
    return (Date)getAttributeInternal(DTZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtZamitnuto
   */
  public void setDtZamitnuto(Date value)
  {
    setAttributeInternal(DTZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for SZamitnuto, using the alias name SZamitnuto
   */
  public String getSZamitnuto()
  {
    return (String)getAttributeInternal(SZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SZamitnuto
   */
  public void setSZamitnuto(String value)
  {
    setAttributeInternal(SZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for NeschvalenoTopPar, using the alias name NeschvalenoTopPar
   */
  public String getNeschvalenoTopPar()
  {
    return (String)getAttributeInternal(NESCHVALENOTOPPAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NeschvalenoTopPar
   */
  public void setNeschvalenoTopPar(String value)
  {
    setAttributeInternal(NESCHVALENOTOPPAR, value);
  }

  /**
   * 
   * Gets the attribute value for Zamitnuto, using the alias name Zamitnuto
   */
  public String getZamitnuto()
  {
    return (String)getAttributeInternal(ZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Zamitnuto
   */
  public void setZamitnuto(String value)
  {
    setAttributeInternal(ZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for IdZadavatel, using the alias name IdZadavatel
   */
  public Number getIdZadavatel()
  {
    return (Number)getAttributeInternal(IDZADAVATEL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZadavatel
   */
  public void setIdZadavatel(Number value)
  {
    setAttributeInternal(IDZADAVATEL, value);
  }

  /**
   * 
   * Gets the attribute value for IdCisdokument, using the alias name IdCisdokument
   */
  public Number getIdCisdokument()
  {
    return (Number)getAttributeInternal(IDCISDOKUMENT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCisdokument
   */
  public void setIdCisdokument(Number value)
  {
    setAttributeInternal(IDCISDOKUMENT, value);
  }

  /**
   * 
   * Gets the attribute value for IdGestor, using the alias name IdGestor
   */
  public Number getIdGestor()
  {
    return (Number)getAttributeInternal(IDGESTOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdGestor
   */
  public void setIdGestor(Number value)
  {
    setAttributeInternal(IDGESTOR, value);
  }

  /**
   * 
   * Gets the attribute value for DtGestorschvaleno, using the alias name DtGestorschvaleno
   */
  public Date getDtGestorschvaleno()
  {
    return (Date)getAttributeInternal(DTGESTORSCHVALENO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtGestorschvaleno
   */
  public void setDtGestorschvaleno(Date value)
  {
    setAttributeInternal(DTGESTORSCHVALENO, value);
  }

  /**
   * 
   * Gets the attribute value for Gestor, using the alias name Gestor
   */
  public String getGestor()
  {
    return (String)getAttributeInternal(GESTOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Gestor
   */
  public void setGestor(String value)
  {
    setAttributeInternal(GESTOR, value);
  }

  /**
   * 
   * Gets the attribute value for IdDokumentorig, using the alias name IdDokumentorig
   */
  public Number getIdDokumentorig()
  {
    return (Number)getAttributeInternal(IDDOKUMENTORIG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDokumentorig
   */
  public void setIdDokumentorig(Number value)
  {
    setAttributeInternal(IDDOKUMENTORIG, value);
  }

  /**
   * 
   * Gets the attribute value for Odborooreal, using the alias name Odborooreal
   */
  public String getOdborooreal()
  {
    return (String)getAttributeInternal(ODBOROOREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Odborooreal
   */
  public void setOdborooreal(String value)
  {
    setAttributeInternal(ODBOROOREAL, value);
  }

  /**
   * 
   * Gets the attribute value for Projektmanreal, using the alias name Projektmanreal
   */
  public String getProjektmanreal()
  {
    return (String)getAttributeInternal(PROJEKTMANREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Projektmanreal
   */
  public void setProjektmanreal(String value)
  {
    setAttributeInternal(PROJEKTMANREAL, value);
  }

  /**
   * 
   * Gets the attribute value for Ucspolooreal, using the alias name Ucspolooreal
   */
  public String getUcspolooreal()
  {
    return (String)getAttributeInternal(UCSPOLOOREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Ucspolooreal
   */
  public void setUcspolooreal(String value)
  {
    setAttributeInternal(UCSPOLOOREAL, value);
  }

  /**
   * 
   * Gets the attribute value for Ucspoltopreal, using the alias name Ucspoltopreal
   */
  public String getUcspoltopreal()
  {
    return (String)getAttributeInternal(UCSPOLTOPREAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Ucspoltopreal
   */
  public void setUcspoltopreal(String value)
  {
    setAttributeInternal(UCSPOLTOPREAL, value);
  }

  /**
   * 
   * Gets the attribute value for CDoczamitnuto, using the alias name CDoczamitnuto
   */
  public String getCDoczamitnuto()
  {
    return (String)getAttributeInternal(CDOCZAMITNUTO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CDoczamitnuto
   */
  public void setCDoczamitnuto(String value)
  {
    setAttributeInternal(CDOCZAMITNUTO, value);
  }

  /**
   * 
   * Gets the attribute value for IdTyptransakce, using the alias name IdTyptransakce
   */
  public Number getIdTyptransakce()
  {
    return (Number)getAttributeInternal(IDTYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdTyptransakce
   */
  public void setIdTyptransakce(Number value)
  {
    setAttributeInternal(IDTYPTRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for Typtransakce, using the alias name Typtransakce
   */
  public String getTyptransakce()
  {
    return (String)getAttributeInternal(TYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Typtransakce
   */
  public void setTyptransakce(String value)
  {
    setAttributeInternal(TYPTRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for NdDocuroven1, using the alias name NdDocuroven1
   */
  public Number getNdDocuroven1()
  {
    return (Number)getAttributeInternal(NDDOCUROVEN1);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdDocuroven1
   */
  public void setNdDocuroven1(Number value)
  {
    setAttributeInternal(NDDOCUROVEN1, value);
  }

  /**
   * 
   * Gets the attribute value for NdDocuroven2, using the alias name NdDocuroven2
   */
  public Number getNdDocuroven2()
  {
    return (Number)getAttributeInternal(NDDOCUROVEN2);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdDocuroven2
   */
  public void setNdDocuroven2(Number value)
  {
    setAttributeInternal(NDDOCUROVEN2, value);
  }

  /**
   * 
   * Gets the attribute value for NdProjekturoven, using the alias name NdProjekturoven
   */
  public Number getNdProjekturoven()
  {
    return (Number)getAttributeInternal(NDPROJEKTUROVEN);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdProjekturoven
   */
  public void setNdProjekturoven(Number value)
  {
    setAttributeInternal(NDPROJEKTUROVEN, value);
  }

	/**
	 * 
	 * Gets the attribute value for NdObjCastkaVolna, using the alias name NdObjCastkaVolna
	 */
	public Number getNdObjCastkaVolna() {
		return (Number)getAttributeInternal(NDOBJCASTKAVOLNA);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for NdObjCastkaVolna
	 */
	public void setNdObjCastkaVolna(Number value) {
		setAttributeInternal(NDOBJCASTKAVOLNA, value);
	}

	/**
	 * 
	 * Gets the attribute value for IdObjRadek, using the alias name IdObjRadek
	 */
	public Number getIdObjRadek() {
		return (Number)getAttributeInternal(IDOBJRADEK);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for IdObjRadek
	 */
	public void setIdObjRadek(Number value) {
		setAttributeInternal(IDOBJRADEK, value);
	}

	/**
	 * 
	 * Gets the attribute value for IdTypizlink, using the alias name IdTypizlink
	 */
	public Number getIdTypizlink() {
		return (Number)getAttributeInternal(IDTYPIZLINK);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for IdTypizlink
	 */
	public void setIdTypizlink(Number value) {
		setAttributeInternal(IDTYPIZLINK, value);
	}

	/**
	 * 
	 * Gets the attribute value for NazevSpolecnosti, using the alias name NazevSpolecnosti
	 */
	public String getNazevSpolecnosti() {
		return (String)getAttributeInternal(NAZEVSPOLECNOSTI);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for NazevSpolecnosti
	 */
	public void setNazevSpolecnosti(String value) {
		setAttributeInternal(NAZEVSPOLECNOSTI, value);
	}

	/**
	 * 
	 * Gets the attribute value for Protistrana, using the alias name Protistrana
	 */
	public String getProtistrana() {
		return (String)getAttributeInternal(PROTISTRANA);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for Protistrana
	 */
	public void setProtistrana(String value) {
		setAttributeInternal(PROTISTRANA, value);
	}

	/**
	 * 
	 * Gets the attribute value for Mena, using the alias name Mena
	 */
	public String getMena() {
		return (String)getAttributeInternal(MENA);
	}

	/**
	 * 
	 * Sets <code>value</code> as the attribute value for Mena
	 */
	public void setMena(String value) {
		setAttributeInternal(MENA, value);
	}

  /**
   * 
   * Gets the attribute value for IdBankar, using the alias name IdBankar
   */
  public Number getIdBankar()
  {
    return (Number)getAttributeInternal(IDBANKAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdBankar
   */
  public void setIdBankar(Number value)
  {
    setAttributeInternal(IDBANKAR, value);
  }

  /**
   * 
   * Gets the attribute value for Bankar, using the alias name Bankar
   */
  public String getBankar()
  {
    return (String)getAttributeInternal(BANKAR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Bankar
   */
  public void setBankar(String value)
  {
    setAttributeInternal(BANKAR, value);
  }

  /**
   * 
   * Gets the attribute value for IsitBudget, using the alias name IsitBudget
   */
  public String getIsitBudget()
  {
    return (String)getAttributeInternal(ISITBUDGET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IsitBudget
   */
  public void setIsitBudget(String value)
  {
    setAttributeInternal(ISITBUDGET, value);
  }
}