package cz.jtbank.konsolidace.kapital;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpKtgZisksrImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDSKUPINA = 1;
  protected static final int DTPLATNOSTOD = 2;
  protected static final int DTPLATNOSTDO = 3;
  protected static final int CKONTROLAVYUZITI = 4;




  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpKtgZisksrImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.kapital.KpKtgZisksr");
    }
    return mDefinitionObject;
  }





  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdSkupina, using the alias name IdSkupina
   */
  public Number getIdSkupina()
  {
    return (Number)getAttributeInternal(IDSKUPINA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdSkupina
   */
  public void setIdSkupina(Number value)
  {
    setAttributeInternal(IDSKUPINA, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }

  /**
   * 
   * Gets the attribute value for CKontrolavyuziti, using the alias name CKontrolavyuziti
   */
  public String getCKontrolavyuziti()
  {
    return (String)getAttributeInternal(CKONTROLAVYUZITI);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CKontrolavyuziti
   */
  public void setCKontrolavyuziti(String value)
  {
    setAttributeInternal(CKONTROLAVYUZITI, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDSKUPINA:
        return getIdSkupina();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      case CKONTROLAVYUZITI:
        return getCKontrolavyuziti();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDSKUPINA:
        setIdSkupina((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      case CKONTROLAVYUZITI:
        setCKontrolavyuziti((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }








}