package cz.jtbank.konsolidace.kapital;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwKpKpduplicitydetailImpl extends EntityImpl 
{
  protected static final int DTDATUM = 0;
  protected static final int IDKTGUCETNISPOLECNOST = 1;
  protected static final int IDDUPLICITA = 2;
  protected static final int IDZDROJDAT = 3;
  protected static final int SMENA = 4;
  protected static final int CSTRANA = 5;
  protected static final int SUCET = 6;
  protected static final int NDCASTKAMENA = 7;
  protected static final int NDCASTKALOCAL = 8;
  protected static final int SPOPIS = 9;
  protected static final int DATUM = 10;
  protected static final int NUMBER0 = 11;
  protected static final int IDKTGSPOLECNOST = 12;
  protected static final int PROTISTRANA = 13;
  protected static final int PCPRODKIND = 14;
  protected static final int PCPRODTYPE = 15;
  protected static final int SUCETORIGINAL = 16;
  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwKpKpduplicitydetailImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.kapital.VwKpKpduplicitydetail");
    }
    return mDefinitionObject;
  }

  /**
   * 
   * Gets the attribute value for DtDatum, using the alias name DtDatum
   */
  public Date getDtDatum()
  {
    return (Date)getAttributeInternal(DTDATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtDatum
   */
  public void setDtDatum(Date value)
  {
    setAttributeInternal(DTDATUM, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for IdDuplicita, using the alias name IdDuplicita
   */
  public Number getIdDuplicita()
  {
    return (Number)getAttributeInternal(IDDUPLICITA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdDuplicita
   */
  public void setIdDuplicita(Number value)
  {
    setAttributeInternal(IDDUPLICITA, value);
  }

  /**
   * 
   * Gets the attribute value for IdZdrojdat, using the alias name IdZdrojdat
   */
  public Number getIdZdrojdat()
  {
    return (Number)getAttributeInternal(IDZDROJDAT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdZdrojdat
   */
  public void setIdZdrojdat(Number value)
  {
    setAttributeInternal(IDZDROJDAT, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for CStrana, using the alias name CStrana
   */
  public String getCStrana()
  {
    return (String)getAttributeInternal(CSTRANA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for CStrana
   */
  public void setCStrana(String value)
  {
    setAttributeInternal(CSTRANA, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }

  /**
   * 
   * Gets the attribute value for Datum, using the alias name Datum
   */
  public Date getDatum()
  {
    return (Date)getAttributeInternal(DATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Datum
   */
  public void setDatum(Date value)
  {
    setAttributeInternal(DATUM, value);
  }

  /**
   * 
   * Gets the attribute value for Number0, using the alias name Number0
   */
  public String getNumber0()
  {
    return (String)getAttributeInternal(NUMBER0);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Number0
   */
  public void setNumber0(String value)
  {
    setAttributeInternal(NUMBER0, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgspolecnost, using the alias name IdKtgspolecnost
   */
  public Number getIdKtgspolecnost()
  {
    return (Number)getAttributeInternal(IDKTGSPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgspolecnost
   */
  public void setIdKtgspolecnost(Number value)
  {
    setAttributeInternal(IDKTGSPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Protistrana, using the alias name Protistrana
   */
  public String getProtistrana()
  {
    return (String)getAttributeInternal(PROTISTRANA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Protistrana
   */
  public void setProtistrana(String value)
  {
    setAttributeInternal(PROTISTRANA, value);
  }

  /**
   * 
   * Gets the attribute value for PcProdKind, using the alias name PcProdKind
   */
  public String getPcProdKind()
  {
    return (String)getAttributeInternal(PCPRODKIND);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PcProdKind
   */
  public void setPcProdKind(String value)
  {
    setAttributeInternal(PCPRODKIND, value);
  }

  /**
   * 
   * Gets the attribute value for PcProdType, using the alias name PcProdType
   */
  public String getPcProdType()
  {
    return (String)getAttributeInternal(PCPRODTYPE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for PcProdType
   */
  public void setPcProdType(String value)
  {
    setAttributeInternal(PCPRODTYPE, value);
  }

  /**
   * 
   * Gets the attribute value for SUcetoriginal, using the alias name SUcetoriginal
   */
  public String getSUcetoriginal()
  {
    return (String)getAttributeInternal(SUCETORIGINAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcetoriginal
   */
  public void setSUcetoriginal(String value)
  {
    setAttributeInternal(SUCETORIGINAL, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DTDATUM:
        return getDtDatum();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case IDDUPLICITA:
        return getIdDuplicita();
      case IDZDROJDAT:
        return getIdZdrojdat();
      case SMENA:
        return getSMena();
      case CSTRANA:
        return getCStrana();
      case SUCET:
        return getSUcet();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case SPOPIS:
        return getSPopis();
      case DATUM:
        return getDatum();
      case NUMBER0:
        return getNumber0();
      case IDKTGSPOLECNOST:
        return getIdKtgspolecnost();
      case PROTISTRANA:
        return getProtistrana();
      case PCPRODKIND:
        return getPcProdKind();
      case PCPRODTYPE:
        return getPcProdType();
      case SUCETORIGINAL:
        return getSUcetoriginal();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case DTDATUM:
        setDtDatum((Date)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case IDDUPLICITA:
        setIdDuplicita((Number)value);
        return;
      case IDZDROJDAT:
        setIdZdrojdat((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case CSTRANA:
        setCStrana((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case SPOPIS:
        setSPopis((String)value);
        return;
      case DATUM:
        setDatum((Date)value);
        return;
      case NUMBER0:
        setNumber0((String)value);
        return;
      case IDKTGSPOLECNOST:
        setIdKtgspolecnost((Number)value);
        return;
      case PROTISTRANA:
        setProtistrana((String)value);
        return;
      case PCPRODKIND:
        setPcProdKind((String)value);
        return;
      case PCPRODTYPE:
        setPcProdType((String)value);
        return;
      case SUCETORIGINAL:
        setSUcetoriginal((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number idZdrojdat)
  {
    return new Key(new Object[] {idZdrojdat});
  }
}