package cz.jtbank.konsolidace.budget;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class KpDefBudgetmustekImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDCISSUBJECT = 1;
  protected static final int IDCISTYPTRANSAKCE = 2;
  protected static final int SUCET = 3;
  protected static final int DTPLATNOSTOD = 4;
  protected static final int DTPLATNOSTDO = 5;


  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public KpDefBudgetmustekImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.budget.KpDefBudgetmustek");
    }
    return mDefinitionObject;
  }



  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdCissubject, using the alias name IdCissubject
   */
  public Number getIdCissubject()
  {
    return (Number)getAttributeInternal(IDCISSUBJECT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCissubject
   */
  public void setIdCissubject(Number value)
  {
    setAttributeInternal(IDCISSUBJECT, value);
  }

  /**
   * 
   * Gets the attribute value for IdCistyptransakce, using the alias name IdCistyptransakce
   */
  public Number getIdCistyptransakce()
  {
    return (Number)getAttributeInternal(IDCISTYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCistyptransakce
   */
  public void setIdCistyptransakce(Number value)
  {
    setAttributeInternal(IDCISTYPTRANSAKCE, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDCISSUBJECT:
        return getIdCissubject();
      case IDCISTYPTRANSAKCE:
        return getIdCistyptransakce();
      case SUCET:
        return getSUcet();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDCISSUBJECT:
        setIdCissubject((Number)value);
        return;
      case IDCISTYPTRANSAKCE:
        setIdCistyptransakce((Number)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }


  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }


}