package cz.jtbank.konsolidace.budget;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatBudgettransakceImpl extends EntityImpl 
{
  protected static final int SPOPIS = 0;
  protected static final int NDCASTKAMENA = 1;
  protected static final int SMENA = 2;
  protected static final int NDCASTKALOCAL = 3;
  protected static final int UCSPOLMENA = 4;
  protected static final int DATUM = 5;
  protected static final int SPOLECNOST = 6;
  protected static final int SUCET = 7;
  protected static final int SUNIFSPOL = 8;
  protected static final int IDBUDGET = 9;
  protected static final int IDCISTYPTRANSAKCE = 10;
  protected static final int ID = 11;
  protected static final int IDKTGPROJEKT = 12;
  protected static final int SPOLDOC = 13;
  protected static final int XIDSL = 14;







  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatBudgettransakceImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.budget.VwDatBudgettransakce");
    }
    return mDefinitionObject;
  }








  /**
   * 
   * Gets the attribute value for SPopis, using the alias name SPopis
   */
  public String getSPopis()
  {
    return (String)getAttributeInternal(SPOPIS);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SPopis
   */
  public void setSPopis(String value)
  {
    setAttributeInternal(SPOPIS, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkamena, using the alias name NdCastkamena
   */
  public Number getNdCastkamena()
  {
    return (Number)getAttributeInternal(NDCASTKAMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkamena
   */
  public void setNdCastkamena(Number value)
  {
    setAttributeInternal(NDCASTKAMENA, value);
  }

  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }

  /**
   * 
   * Gets the attribute value for NdCastkalocal, using the alias name NdCastkalocal
   */
  public Number getNdCastkalocal()
  {
    return (Number)getAttributeInternal(NDCASTKALOCAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for NdCastkalocal
   */
  public void setNdCastkalocal(Number value)
  {
    setAttributeInternal(NDCASTKALOCAL, value);
  }

  /**
   * 
   * Gets the attribute value for UcspolMena, using the alias name UcspolMena
   */
  public String getUcspolMena()
  {
    return (String)getAttributeInternal(UCSPOLMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for UcspolMena
   */
  public void setUcspolMena(String value)
  {
    setAttributeInternal(UCSPOLMENA, value);
  }

  /**
   * 
   * Gets the attribute value for Datum, using the alias name Datum
   */
  public Date getDatum()
  {
    return (Date)getAttributeInternal(DATUM);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Datum
   */
  public void setDatum(Date value)
  {
    setAttributeInternal(DATUM, value);
  }

  /**
   * 
   * Gets the attribute value for Spolecnost, using the alias name Spolecnost
   */
  public String getSpolecnost()
  {
    return (String)getAttributeInternal(SPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Spolecnost
   */
  public void setSpolecnost(String value)
  {
    setAttributeInternal(SPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for SUcet, using the alias name SUcet
   */
  public String getSUcet()
  {
    return (String)getAttributeInternal(SUCET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUcet
   */
  public void setSUcet(String value)
  {
    setAttributeInternal(SUCET, value);
  }

  /**
   * 
   * Gets the attribute value for SUnifspol, using the alias name SUnifspol
   */
  public String getSUnifspol()
  {
    return (String)getAttributeInternal(SUNIFSPOL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SUnifspol
   */
  public void setSUnifspol(String value)
  {
    setAttributeInternal(SUNIFSPOL, value);
  }

  /**
   * 
   * Gets the attribute value for IdBudget, using the alias name IdBudget
   */
  public Number getIdBudget()
  {
    return (Number)getAttributeInternal(IDBUDGET);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdBudget
   */
  public void setIdBudget(Number value)
  {
    setAttributeInternal(IDBUDGET, value);
  }

  /**
   * 
   * Gets the attribute value for IdCistyptransakce, using the alias name IdCistyptransakce
   */
  public Number getIdCistyptransakce()
  {
    return (Number)getAttributeInternal(IDCISTYPTRANSAKCE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdCistyptransakce
   */
  public void setIdCistyptransakce(Number value)
  {
    setAttributeInternal(IDCISTYPTRANSAKCE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPOPIS:
        return getSPopis();
      case NDCASTKAMENA:
        return getNdCastkamena();
      case SMENA:
        return getSMena();
      case NDCASTKALOCAL:
        return getNdCastkalocal();
      case UCSPOLMENA:
        return getUcspolMena();
      case DATUM:
        return getDatum();
      case SPOLECNOST:
        return getSpolecnost();
      case SUCET:
        return getSUcet();
      case SUNIFSPOL:
        return getSUnifspol();
      case IDBUDGET:
        return getIdBudget();
      case IDCISTYPTRANSAKCE:
        return getIdCistyptransakce();
      case ID:
        return getId();
      case IDKTGPROJEKT:
        return getIdKtgprojekt();
      case SPOLDOC:
        return getSpolDoc();
      case XIDSL:
        return getXidsl();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SPOPIS:
        setSPopis((String)value);
        return;
      case NDCASTKAMENA:
        setNdCastkamena((Number)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case NDCASTKALOCAL:
        setNdCastkalocal((Number)value);
        return;
      case UCSPOLMENA:
        setUcspolMena((String)value);
        return;
      case DATUM:
        setDatum((Date)value);
        return;
      case SPOLECNOST:
        setSpolecnost((String)value);
        return;
      case SUCET:
        setSUcet((String)value);
        return;
      case SUNIFSPOL:
        setSUnifspol((String)value);
        return;
      case IDBUDGET:
        setIdBudget((Number)value);
        return;
      case IDCISTYPTRANSAKCE:
        setIdCistyptransakce((Number)value);
        return;
      case ID:
        setId((Number)value);
        return;
      case IDKTGPROJEKT:
        setIdKtgprojekt((Number)value);
        return;
      case SPOLDOC:
        setSpolDoc((String)value);
        return;
      case XIDSL:
        setXidsl((Number)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }


  /**
   * 
   * Gets the attribute value for IdKtgprojekt, using the alias name IdKtgprojekt
   */
  public Number getIdKtgprojekt()
  {
    return (Number)getAttributeInternal(IDKTGPROJEKT);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgprojekt
   */
  public void setIdKtgprojekt(Number value)
  {
    setAttributeInternal(IDKTGPROJEKT, value);
  }

  /**
   * 
   * Gets the attribute value for SpolDoc, using the alias name SpolDoc
   */
  public String getSpolDoc()
  {
    return (String)getAttributeInternal(SPOLDOC);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SpolDoc
   */
  public void setSpolDoc(String value)
  {
    setAttributeInternal(SPOLDOC, value);
  }


  /**
   * 
   * Gets the attribute value for Xidsl, using the alias name Xidsl
   */
  public Number getXidsl()
  {
    return (Number)getAttributeInternal(XIDSL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Xidsl
   */
  public void setXidsl(Number value)
  {
    setAttributeInternal(XIDSL, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }





}