package cz.jtbank.konsolidace.budget;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class VwDatBudgetImpl extends EntityImpl 
{
  protected static final int ID = 0;
  protected static final int IDKTGODBOR = 1;
  protected static final int DTPLATNOSTOD = 2;
  protected static final int DTPLATNOSTDO = 3;
  protected static final int IDODBOROO = 4;
  protected static final int IDUCSPOLOO = 5;
  protected static final int IDUCSPOLTOP = 6;
  protected static final int SKOD = 7;
  protected static final int SNAZEV = 8;
  protected static final int SMENA = 9;
  protected static final int IDKTGUCETNISPOLECNOST = 10;
  protected static final int NAZEVUCSPOL = 11;
  protected static final int DTSCHVALITDO = 12;





  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public VwDatBudgetImpl()
  {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("cz.jtbank.konsolidace.budget.VwDatBudget");
    }
    return mDefinitionObject;
  }






  /**
   * 
   * Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**
   * 
   * Gets the attribute value for IdKtgodbor, using the alias name IdKtgodbor
   */
  public Number getIdKtgodbor()
  {
    return (Number)getAttributeInternal(IDKTGODBOR);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgodbor
   */
  public void setIdKtgodbor(Number value)
  {
    setAttributeInternal(IDKTGODBOR, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostod, using the alias name DtPlatnostod
   */
  public Date getDtPlatnostod()
  {
    return (Date)getAttributeInternal(DTPLATNOSTOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostod
   */
  public void setDtPlatnostod(Date value)
  {
    setAttributeInternal(DTPLATNOSTOD, value);
  }

  /**
   * 
   * Gets the attribute value for DtPlatnostdo, using the alias name DtPlatnostdo
   */
  public Date getDtPlatnostdo()
  {
    return (Date)getAttributeInternal(DTPLATNOSTDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtPlatnostdo
   */
  public void setDtPlatnostdo(Date value)
  {
    setAttributeInternal(DTPLATNOSTDO, value);
  }

  /**
   * 
   * Gets the attribute value for IdOdboroo, using the alias name IdOdboroo
   */
  public Number getIdOdboroo()
  {
    return (Number)getAttributeInternal(IDODBOROO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdOdboroo
   */
  public void setIdOdboroo(Number value)
  {
    setAttributeInternal(IDODBOROO, value);
  }

  /**
   * 
   * Gets the attribute value for IdUcspoloo, using the alias name IdUcspoloo
   */
  public Number getIdUcspoloo()
  {
    return (Number)getAttributeInternal(IDUCSPOLOO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUcspoloo
   */
  public void setIdUcspoloo(Number value)
  {
    setAttributeInternal(IDUCSPOLOO, value);
  }

  /**
   * 
   * Gets the attribute value for IdUcspoltop, using the alias name IdUcspoltop
   */
  public Number getIdUcspoltop()
  {
    return (Number)getAttributeInternal(IDUCSPOLTOP);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdUcspoltop
   */
  public void setIdUcspoltop(Number value)
  {
    setAttributeInternal(IDUCSPOLTOP, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        return getId();
      case IDKTGODBOR:
        return getIdKtgodbor();
      case DTPLATNOSTOD:
        return getDtPlatnostod();
      case DTPLATNOSTDO:
        return getDtPlatnostdo();
      case IDODBOROO:
        return getIdOdboroo();
      case IDUCSPOLOO:
        return getIdUcspoloo();
      case IDUCSPOLTOP:
        return getIdUcspoltop();
      case SKOD:
        return getSKod();
      case SNAZEV:
        return getSNazev();
      case SMENA:
        return getSMena();
      case IDKTGUCETNISPOLECNOST:
        return getIdKtgucetnispolecnost();
      case NAZEVUCSPOL:
        return getNazevucspol();
      case DTSCHVALITDO:
        return getDtSchvalitdo();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case ID:
        setId((Number)value);
        return;
      case IDKTGODBOR:
        setIdKtgodbor((Number)value);
        return;
      case DTPLATNOSTOD:
        setDtPlatnostod((Date)value);
        return;
      case DTPLATNOSTDO:
        setDtPlatnostdo((Date)value);
        return;
      case IDODBOROO:
        setIdOdboroo((Number)value);
        return;
      case IDUCSPOLOO:
        setIdUcspoloo((Number)value);
        return;
      case IDUCSPOLTOP:
        setIdUcspoltop((Number)value);
        return;
      case SKOD:
        setSKod((String)value);
        return;
      case SNAZEV:
        setSNazev((String)value);
        return;
      case SMENA:
        setSMena((String)value);
        return;
      case IDKTGUCETNISPOLECNOST:
        setIdKtgucetnispolecnost((Number)value);
        return;
      case NAZEVUCSPOL:
        setNazevucspol((String)value);
        return;
      case DTSCHVALITDO:
        setDtSchvalitdo((Date)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for SKod, using the alias name SKod
   */
  public String getSKod()
  {
    return (String)getAttributeInternal(SKOD);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SKod
   */
  public void setSKod(String value)
  {
    setAttributeInternal(SKOD, value);
  }

  /**
   * 
   * Gets the attribute value for SNazev, using the alias name SNazev
   */
  public String getSNazev()
  {
    return (String)getAttributeInternal(SNAZEV);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SNazev
   */
  public void setSNazev(String value)
  {
    setAttributeInternal(SNAZEV, value);
  }



  /**
   * 
   * Gets the attribute value for SMena, using the alias name SMena
   */
  public String getSMena()
  {
    return (String)getAttributeInternal(SMENA);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for SMena
   */
  public void setSMena(String value)
  {
    setAttributeInternal(SMENA, value);
  }



  /**
   * 
   * Gets the attribute value for IdKtgucetnispolecnost, using the alias name IdKtgucetnispolecnost
   */
  public Number getIdKtgucetnispolecnost()
  {
    return (Number)getAttributeInternal(IDKTGUCETNISPOLECNOST);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for IdKtgucetnispolecnost
   */
  public void setIdKtgucetnispolecnost(Number value)
  {
    setAttributeInternal(IDKTGUCETNISPOLECNOST, value);
  }

  /**
   * 
   * Gets the attribute value for Nazevucspol, using the alias name Nazevucspol
   */
  public String getNazevucspol()
  {
    return (String)getAttributeInternal(NAZEVUCSPOL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for Nazevucspol
   */
  public void setNazevucspol(String value)
  {
    setAttributeInternal(NAZEVUCSPOL, value);
  }


  /**
   * 
   * Gets the attribute value for DtSchvalitdo, using the alias name DtSchvalitdo
   */
  public Date getDtSchvalitdo()
  {
    return (Date)getAttributeInternal(DTSCHVALITDO);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for DtSchvalitdo
   */
  public void setDtSchvalitdo(Date value)
  {
    setAttributeInternal(DTSCHVALITDO, value);
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[] {id});
  }


}